/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as WorkoutsIndexImport } from './routes/workouts/index'
import { Route as WorkoutsWorkoutIdImport } from './routes/workouts/$workoutId'
import { Route as ExercisesExerciseIdImport } from './routes/exercises/$exerciseId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkoutsIndexRoute = WorkoutsIndexImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRoute,
} as any)

const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesExerciseIdRoute = ExercisesExerciseIdImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdImport
      parentRoute: typeof rootRoute
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdImport
      parentRoute: typeof rootRoute
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts': typeof WorkoutsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts': typeof WorkoutsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/': typeof WorkoutsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/exercises/$exerciseId'
    | '/workouts/$workoutId'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/exercises/$exerciseId'
    | '/workouts/$workoutId'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/exercises/$exerciseId'
    | '/workouts/$workoutId'
    | '/workouts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/exercises/$exerciseId",
        "/workouts/$workoutId",
        "/workouts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/exercises/$exerciseId": {
      "filePath": "exercises/$exerciseId.tsx"
    },
    "/workouts/$workoutId": {
      "filePath": "workouts/$workoutId.tsx"
    },
    "/workouts/": {
      "filePath": "workouts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
