// This file is auto-generated by @hey-api/openapi-ts

export const aichat_ChatMessageSchema = {
  type: "object",
  properties: {
    completed_at: {
      type: "string",
    },
    content: {
      type: "string",
    },
    conversation_id: {
      type: "integer",
    },
    created_at: {
      type: "string",
    },
    error_message: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    role: {
      type: "string",
    },
    status: {
      type: "string",
    },
    updated_at: {
      type: "string",
    },
  },
} as const;

export const aichat_ConversationSchema = {
  type: "object",
  properties: {
    created_at: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    last_message_at: {
      type: "string",
    },
    title: {
      type: "string",
    },
    updated_at: {
      type: "string",
    },
  },
} as const;

export const aichat_ConversationDetailSchema = {
  type: "object",
  properties: {
    conversation: {
      $ref: "#/definitions/aichat.Conversation",
    },
    messages: {
      type: "array",
      items: {
        $ref: "#/definitions/aichat.ChatMessage",
      },
    },
  },
} as const;

export const aichat_SendMessageRequestSchema = {
  type: "object",
  properties: {
    prompt: {
      type: "string",
    },
  },
} as const;

export const aichat_StreamEventSchema = {
  type: "object",
  properties: {
    conversation_id: {
      type: "integer",
    },
    delta: {
      type: "string",
    },
    message: {
      type: "string",
    },
    message_id: {
      type: "integer",
    },
    model: {
      type: "string",
    },
    request_id: {
      type: "string",
    },
    run_id: {
      type: "integer",
    },
    text: {
      type: "string",
    },
    type: {
      type: "string",
    },
  },
} as const;

export const aichat_ValidateRequestSchema = {
  type: "object",
  properties: {
    prompt: {
      type: "string",
    },
  },
} as const;

export const aichat_ValidateResponseSchema = {
  type: "object",
  properties: {
    model: {
      type: "string",
    },
    output: {
      $ref: "#/definitions/aichat.ValidationOutput",
    },
  },
} as const;

export const aichat_ValidationOutputSchema = {
  type: "object",
  properties: {
    next_step: {
      type: "string",
    },
    summary: {
      type: "string",
    },
  },
} as const;

export const exercise_CreateExerciseRequestSchema = {
  type: "object",
  required: ["name"],
  properties: {
    name: {
      type: "string",
    },
  },
} as const;

export const exercise_CreateExerciseResponseSchema = {
  type: "object",
  required: ["created_at", "id", "name", "updated_at", "user_id"],
  properties: {
    created_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    id: {
      type: "integer",
      example: 1,
    },
    name: {
      type: "string",
      example: "Bench Press",
    },
    updated_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    user_id: {
      type: "string",
      example: "user-123",
    },
  },
} as const;

export const exercise_ExerciseDetailExerciseResponseSchema = {
  type: "object",
  required: ["created_at", "id", "name", "updated_at", "user_id"],
  properties: {
    best_e1rm: {
      type: "number",
      example: 305,
    },
    created_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    historical_1rm: {
      type: "number",
      example: 315,
    },
    historical_1rm_source_workout_id: {
      type: "integer",
      example: 42,
    },
    historical_1rm_updated_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    id: {
      type: "integer",
      example: 1,
    },
    name: {
      type: "string",
      example: "Bench Press",
    },
    updated_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    user_id: {
      type: "string",
      example: "user-123",
    },
  },
} as const;

export const exercise_ExerciseDetailResponseSchema = {
  type: "object",
  required: ["exercise", "sets"],
  properties: {
    exercise: {
      $ref: "#/definitions/exercise.ExerciseDetailExerciseResponse",
    },
    sets: {
      type: "array",
      items: {
        $ref: "#/definitions/exercise.ExerciseWithSetsResponse",
      },
    },
  },
} as const;

export const exercise_ExerciseMetricsHistoryPointSchema = {
  type: "object",
  properties: {
    date: {
      type: "string",
    },
    session_avg_e1rm: {
      type: "number",
    },
    session_avg_intensity: {
      type: "number",
    },
    session_best_e1rm: {
      type: "number",
    },
    session_best_intensity: {
      type: "number",
    },
    total_volume_working: {
      type: "number",
    },
    workout_id: {
      type: "integer",
    },
    x: {
      type: "string",
    },
  },
} as const;

export const exercise_ExerciseMetricsHistoryResponseSchema = {
  type: "object",
  properties: {
    bucket: {
      $ref: "#/definitions/exercise.MetricsHistoryBucket",
    },
    points: {
      type: "array",
      items: {
        $ref: "#/definitions/exercise.ExerciseMetricsHistoryPoint",
      },
    },
    range: {
      type: "string",
    },
  },
} as const;

export const exercise_ExerciseResponseSchema = {
  type: "object",
  required: ["created_at", "id", "name", "updated_at", "user_id"],
  properties: {
    created_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    id: {
      type: "integer",
      example: 1,
    },
    name: {
      type: "string",
      example: "Bench Press",
    },
    updated_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    user_id: {
      type: "string",
      example: "user-123",
    },
  },
} as const;

export const exercise_ExerciseWithSetsResponseSchema = {
  type: "object",
  required: [
    "exercise_id",
    "exercise_name",
    "reps",
    "set_id",
    "set_type",
    "volume",
    "workout_date",
    "workout_id",
  ],
  properties: {
    exercise_id: {
      type: "integer",
      example: 1,
    },
    exercise_name: {
      type: "string",
      example: "Bench Press",
    },
    exercise_order: {
      type: "integer",
      example: 0,
    },
    reps: {
      type: "integer",
      example: 10,
    },
    set_id: {
      type: "integer",
      example: 1,
    },
    set_order: {
      type: "integer",
      example: 1,
    },
    set_type: {
      type: "string",
      example: "working",
    },
    volume: {
      type: "number",
      example: 2250.5,
    },
    weight: {
      type: "number",
      example: 225.5,
    },
    workout_date: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    workout_id: {
      type: "integer",
      example: 1,
    },
    workout_notes: {
      type: "string",
      example: "Great workout today",
    },
  },
} as const;

export const exercise_MetricsHistoryBucketSchema = {
  type: "string",
  enum: ["workout"],
  "x-enum-varnames": ["MetricsHistoryBucketWorkout"],
} as const;

export const exercise_RecentSetsResponseSchema = {
  type: "object",
  required: ["created_at", "reps", "set_id", "workout_date", "workout_id"],
  properties: {
    created_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    exercise_order: {
      type: "integer",
      example: 0,
    },
    reps: {
      type: "integer",
      example: 10,
    },
    set_id: {
      type: "integer",
      example: 1,
    },
    set_order: {
      type: "integer",
      example: 2,
    },
    weight: {
      type: "number",
      example: 225.5,
    },
    workout_date: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    workout_id: {
      type: "integer",
      example: 1,
    },
  },
} as const;

export const exercise_UpdateExerciseHistorical1RMRequestSchema = {
  type: "object",
  properties: {
    historical_1rm: {
      type: "number",
      maximum: 999999.99,
      minimum: 0,
    },
    mode: {
      type: "string",
      enum: ["manual", "recompute"],
    },
  },
} as const;

export const exercise_UpdateExerciseNameRequestSchema = {
  type: "object",
  required: ["name"],
  properties: {
    name: {
      type: "string",
      maxLength: 256,
    },
  },
} as const;

export const featureaccess_FeatureAccessResponseSchema = {
  type: "object",
  required: ["created_at", "feature_key", "source", "starts_at"],
  properties: {
    created_at: {
      type: "string",
      example: "2026-03-25T12:00:00Z",
    },
    expires_at: {
      type: "string",
      example: "2026-04-25T12:00:00Z",
    },
    feature_key: {
      type: "string",
      example: "ai_chatbot",
    },
    granted_by: {
      type: "string",
      example: "andy",
    },
    note: {
      type: "string",
      example: "dev demo access",
    },
    source: {
      type: "string",
      example: "manual",
    },
    source_reference: {
      type: "string",
      example: "sub_123",
    },
    starts_at: {
      type: "string",
      example: "2026-03-25T12:00:00Z",
    },
  },
} as const;

export const health_HealthResponseSchema = {
  type: "object",
  properties: {
    status: {
      type: "string",
    },
    timestamp: {
      type: "string",
    },
    version: {
      type: "string",
    },
  },
} as const;

export const health_ReadyResponseSchema = {
  type: "object",
  properties: {
    checks: {
      type: "object",
      additionalProperties: {
        type: "string",
      },
    },
    status: {
      type: "string",
    },
    timestamp: {
      type: "string",
    },
  },
} as const;

export const response_ErrorSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
    },
    request_id: {
      type: "string",
    },
  },
} as const;

export const response_ErrorResponseSchema = {
  type: "object",
  properties: {
    message: {
      type: "string",
      example: "Error message",
    },
    request_id: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
  },
} as const;

export const response_SuccessResponseSchema = {
  type: "object",
  properties: {
    success: {
      type: "boolean",
      example: true,
    },
  },
} as const;

export const workout_ContributionDataResponseSchema = {
  type: "object",
  properties: {
    days: {
      type: "array",
      items: {
        $ref: "#/definitions/workout.ContributionDay",
      },
    },
  },
} as const;

export const workout_ContributionDaySchema = {
  type: "object",
  properties: {
    count: {
      type: "integer",
    },
    date: {
      type: "string",
    },
    level: {
      type: "integer",
    },
    workouts: {
      type: "array",
      items: {
        $ref: "#/definitions/workout.WorkoutSummary",
      },
    },
  },
} as const;

export const workout_CreateWorkoutRequestSchema = {
  type: "object",
  required: ["date", "exercises"],
  properties: {
    date: {
      type: "string",
    },
    exercises: {
      type: "array",
      minItems: 1,
      items: {
        $ref: "#/definitions/workout.ExerciseInput",
      },
    },
    notes: {
      type: "string",
      maxLength: 256,
    },
    workoutFocus: {
      type: "string",
      maxLength: 256,
    },
  },
} as const;

export const workout_ExerciseInputSchema = {
  type: "object",
  required: ["name", "sets"],
  properties: {
    name: {
      type: "string",
      maxLength: 256,
      minLength: 1,
    },
    sets: {
      type: "array",
      minItems: 1,
      items: {
        $ref: "#/definitions/workout.SetInput",
      },
    },
  },
} as const;

export const workout_SetInputSchema = {
  type: "object",
  required: ["reps", "setType"],
  properties: {
    reps: {
      type: "integer",
      minimum: 1,
    },
    setType: {
      type: "string",
      enum: ["warmup", "working"],
    },
    weight: {
      type: "number",
      maximum: 999999999.9,
      minimum: 0,
    },
  },
} as const;

export const workout_UpdateExerciseSchema = {
  type: "object",
  required: ["name", "sets"],
  properties: {
    name: {
      type: "string",
      maxLength: 256,
      minLength: 1,
    },
    sets: {
      type: "array",
      minItems: 1,
      items: {
        $ref: "#/definitions/workout.UpdateSet",
      },
    },
  },
} as const;

export const workout_UpdateSetSchema = {
  type: "object",
  required: ["reps", "setType"],
  properties: {
    reps: {
      type: "integer",
      minimum: 1,
    },
    setType: {
      type: "string",
      enum: ["warmup", "working"],
    },
    weight: {
      type: "number",
      maximum: 999999999.9,
      minimum: 0,
    },
  },
} as const;

export const workout_UpdateWorkoutRequestSchema = {
  type: "object",
  required: ["date", "exercises"],
  properties: {
    date: {
      type: "string",
    },
    exercises: {
      type: "array",
      minItems: 1,
      items: {
        $ref: "#/definitions/workout.UpdateExercise",
      },
    },
    notes: {
      type: "string",
      maxLength: 256,
    },
    workoutFocus: {
      type: "string",
      maxLength: 256,
    },
  },
} as const;

export const workout_WorkoutResponseSchema = {
  description: "Workout response model",
  type: "object",
  required: ["created_at", "date", "id", "updated_at", "user_id"],
  properties: {
    created_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    date: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    id: {
      type: "integer",
      example: 1,
    },
    notes: {
      type: "string",
      example: "Great workout today",
    },
    updated_at: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    user_id: {
      type: "string",
      example: "user-123",
    },
    workout_focus: {
      type: "string",
      example: "Upper Body",
    },
  },
} as const;

export const workout_WorkoutSummarySchema = {
  type: "object",
  properties: {
    focus: {
      type: "string",
    },
    id: {
      type: "integer",
    },
    time: {
      type: "string",
    },
    volume: {
      type: "number",
    },
  },
} as const;

export const workout_WorkoutWithSetsResponseSchema = {
  type: "object",
  required: [
    "exercise_id",
    "exercise_name",
    "reps",
    "set_id",
    "set_type",
    "volume",
    "workout_date",
    "workout_id",
  ],
  properties: {
    exercise_id: {
      type: "integer",
      example: 1,
    },
    exercise_name: {
      type: "string",
      example: "Bench Press",
    },
    exercise_order: {
      type: "integer",
      example: 0,
    },
    reps: {
      type: "integer",
      example: 10,
    },
    set_id: {
      type: "integer",
      example: 1,
    },
    set_order: {
      type: "integer",
      example: 1,
    },
    set_type: {
      type: "string",
      example: "working",
    },
    volume: {
      type: "number",
      example: 2250.5,
    },
    weight: {
      type: "number",
      example: 225.5,
    },
    workout_date: {
      type: "string",
      example: "2023-01-01T15:04:05Z",
    },
    workout_focus: {
      type: "string",
      example: "Upper Body",
    },
    workout_id: {
      type: "integer",
      example: 1,
    },
    workout_notes: {
      type: "string",
      example: "Great workout today",
    },
  },
} as const;
