// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  ServerSentEventsResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  DeleteAiConversationsByIdData,
  DeleteAiConversationsByIdErrors,
  DeleteAiConversationsByIdResponses,
  DeleteAiConversationsData,
  DeleteAiConversationsErrors,
  DeleteAiConversationsResponses,
  DeleteExercisesByIdData,
  DeleteExercisesByIdErrors,
  DeleteExercisesByIdResponses,
  DeleteWorkoutsByIdData,
  DeleteWorkoutsByIdErrors,
  DeleteWorkoutsByIdResponses,
  GetAiConversationsByIdData,
  GetAiConversationsByIdErrors,
  GetAiConversationsByIdMessagesStreamResumeData,
  GetAiConversationsByIdMessagesStreamResumeErrors,
  GetAiConversationsByIdMessagesStreamResumeResponse,
  GetAiConversationsByIdMessagesStreamResumeResponses,
  GetAiConversationsByIdResponses,
  GetAiConversationsData,
  GetAiConversationsErrors,
  GetAiConversationsResponses,
  GetExerciseCatalogData,
  GetExerciseCatalogErrors,
  GetExerciseCatalogResponses,
  GetExercisesByIdData,
  GetExercisesByIdErrors,
  GetExercisesByIdMetricsHistoryData,
  GetExercisesByIdMetricsHistoryErrors,
  GetExercisesByIdMetricsHistoryResponses,
  GetExercisesByIdRecentSetsData,
  GetExercisesByIdRecentSetsErrors,
  GetExercisesByIdRecentSetsResponses,
  GetExercisesByIdRecommendationData,
  GetExercisesByIdRecommendationErrors,
  GetExercisesByIdRecommendationResponses,
  GetExercisesByIdResponses,
  GetExercisesData,
  GetExercisesErrors,
  GetExercisesResponses,
  GetFeaturesAccessData,
  GetFeaturesAccessErrors,
  GetFeaturesAccessResponses,
  GetTrainingProfileData,
  GetTrainingProfileErrors,
  GetTrainingProfileResponses,
  GetWorkoutsByIdData,
  GetWorkoutsByIdErrors,
  GetWorkoutsByIdResponses,
  GetWorkoutsContributionDataData,
  GetWorkoutsContributionDataErrors,
  GetWorkoutsContributionDataResponses,
  GetWorkoutsData,
  GetWorkoutsErrors,
  GetWorkoutsFocusValuesData,
  GetWorkoutsFocusValuesErrors,
  GetWorkoutsFocusValuesResponses,
  GetWorkoutsNewWorkoutContextData,
  GetWorkoutsNewWorkoutContextErrors,
  GetWorkoutsNewWorkoutContextResponses,
  GetWorkoutsResponses,
  PatchExercisesByIdData,
  PatchExercisesByIdErrors,
  PatchExercisesByIdHistorical1RmData,
  PatchExercisesByIdHistorical1RmErrors,
  PatchExercisesByIdHistorical1RmResponses,
  PatchExercisesByIdResponses,
  PostAiChatTelemetryData,
  PostAiChatTelemetryErrors,
  PostAiChatTelemetryResponses,
  PostAiConversationsByIdLatestWorkoutDraftSaveData,
  PostAiConversationsByIdLatestWorkoutDraftSaveErrors,
  PostAiConversationsByIdLatestWorkoutDraftSaveResponses,
  PostAiConversationsByIdMessagesRecoverData,
  PostAiConversationsByIdMessagesRecoverErrors,
  PostAiConversationsByIdMessagesRecoverResponses,
  PostAiConversationsByIdMessagesStreamData,
  PostAiConversationsByIdMessagesStreamErrors,
  PostAiConversationsByIdMessagesStreamResponse,
  PostAiConversationsByIdMessagesStreamResponses,
  PostAiConversationsByIdRunsByRunIdStopData,
  PostAiConversationsByIdRunsByRunIdStopErrors,
  PostAiConversationsByIdRunsByRunIdStopResponses,
  PostAiConversationsData,
  PostAiConversationsErrors,
  PostAiConversationsResponses,
  PostExercisesData,
  PostExercisesErrors,
  PostExercisesResponses,
  PostWorkoutsData,
  PostWorkoutsErrors,
  PostWorkoutsResponses,
  PutExercisesByIdCatalogData,
  PutExercisesByIdCatalogErrors,
  PutExercisesByIdCatalogResponses,
  PutTrainingProfileData,
  PutTrainingProfileErrors,
  PutTrainingProfileResponses,
  PutWorkoutsByIdData,
  PutWorkoutsByIdErrors,
  PutWorkoutsByIdResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Record AI chat telemetry
 *
 * Records authenticated client-observed AI chat outcomes for observability and rollout gating.
 */
export const postAiChatTelemetry = <ThrowOnError extends boolean = false>(
  options: Options<PostAiChatTelemetryData, ThrowOnError>,
): RequestResult<
  PostAiChatTelemetryResponses,
  PostAiChatTelemetryErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostAiChatTelemetryResponses,
    PostAiChatTelemetryErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/chat/telemetry",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete all AI chat history
 *
 * Permanently deletes every AI chat conversation owned by the authenticated user without requiring current AI chat feature access. Training profile values and saved workouts remain.
 */
export const deleteAiConversations = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteAiConversationsData, ThrowOnError>,
): RequestResult<
  DeleteAiConversationsResponses,
  DeleteAiConversationsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteAiConversationsResponses,
    DeleteAiConversationsErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations",
    ...options,
  });

/**
 * List AI chat conversations
 *
 * Returns lightweight AI chat conversation summaries for the authenticated user, newest activity first.
 */
export const getAiConversations = <ThrowOnError extends boolean = false>(
  options?: Options<GetAiConversationsData, ThrowOnError>,
): RequestResult<
  GetAiConversationsResponses,
  GetAiConversationsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetAiConversationsResponses,
    GetAiConversationsErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations",
    ...options,
  });

/**
 * Create AI chat conversation
 *
 * Creates an empty persisted AI chat conversation for the authenticated user.
 */
export const postAiConversations = <ThrowOnError extends boolean = false>(
  options?: Options<PostAiConversationsData, ThrowOnError>,
): RequestResult<
  PostAiConversationsResponses,
  PostAiConversationsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostAiConversationsResponses,
    PostAiConversationsErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations",
    ...options,
  });

/**
 * Delete AI chat conversation
 *
 * Deletes an AI chat conversation and its associated messages, runs, and stream chunks. Only the owner can delete it, and active streams must finish first.
 */
export const deleteAiConversationsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAiConversationsByIdData, ThrowOnError>,
): RequestResult<
  DeleteAiConversationsByIdResponses,
  DeleteAiConversationsByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteAiConversationsByIdResponses,
    DeleteAiConversationsByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations/{id}",
    ...options,
  });

/**
 * Get AI chat conversation
 *
 * Returns a persisted AI chat conversation with its messages.
 */
export const getAiConversationsById = <ThrowOnError extends boolean = false>(
  options: Options<GetAiConversationsByIdData, ThrowOnError>,
): RequestResult<
  GetAiConversationsByIdResponses,
  GetAiConversationsByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAiConversationsByIdResponses,
    GetAiConversationsByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations/{id}",
    ...options,
  });

/**
 * Save the latest AI chat workout draft
 *
 * Creates a workout from the conversation's latest structured workout draft and marks that draft as saved.
 */
export const postAiConversationsByIdLatestWorkoutDraftSave = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PostAiConversationsByIdLatestWorkoutDraftSaveData,
    ThrowOnError
  >,
): RequestResult<
  PostAiConversationsByIdLatestWorkoutDraftSaveResponses,
  PostAiConversationsByIdLatestWorkoutDraftSaveErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostAiConversationsByIdLatestWorkoutDraftSaveResponses,
    PostAiConversationsByIdLatestWorkoutDraftSaveErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations/{id}/latest-workout-draft/save",
    ...options,
  });

/**
 * Recover AI chat message stream
 *
 * Queues recovery for an active streaming AI chat run so persisted updates can continue after a disconnect.
 */
export const postAiConversationsByIdMessagesRecover = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostAiConversationsByIdMessagesRecoverData, ThrowOnError>,
): RequestResult<
  PostAiConversationsByIdMessagesRecoverResponses,
  PostAiConversationsByIdMessagesRecoverErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostAiConversationsByIdMessagesRecoverResponses,
    PostAiConversationsByIdMessagesRecoverErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations/{id}/messages/recover",
    ...options,
  });

/**
 * Stream AI chat message
 *
 * Persists a user message and run, then streams normalized assistant events over SSE. Preflight failures stay JSON.
 */
export const postAiConversationsByIdMessagesStream = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PostAiConversationsByIdMessagesStreamData,
    ThrowOnError,
    PostAiConversationsByIdMessagesStreamResponse
  >,
): Promise<
  ServerSentEventsResult<PostAiConversationsByIdMessagesStreamResponses>
> =>
  (options.client ?? client).sse.post<
    PostAiConversationsByIdMessagesStreamResponses,
    PostAiConversationsByIdMessagesStreamErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations/{id}/messages/stream",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Resume AI chat message stream
 *
 * Replays persisted AI chat output after a sequence cursor and continues streaming while the run is still active.
 */
export const getAiConversationsByIdMessagesStreamResume = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetAiConversationsByIdMessagesStreamResumeData,
    ThrowOnError,
    GetAiConversationsByIdMessagesStreamResumeResponse
  >,
): Promise<
  ServerSentEventsResult<GetAiConversationsByIdMessagesStreamResumeResponses>
> =>
  (options.client ?? client).sse.get<
    GetAiConversationsByIdMessagesStreamResumeResponses,
    GetAiConversationsByIdMessagesStreamResumeErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations/{id}/messages/stream/resume",
    ...options,
  });

/**
 * Stop an AI chat run
 *
 * Idempotently stops the authenticated user's exact streaming run while preserving partial output.
 */
export const postAiConversationsByIdRunsByRunIdStop = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostAiConversationsByIdRunsByRunIdStopData, ThrowOnError>,
): RequestResult<
  PostAiConversationsByIdRunsByRunIdStopResponses,
  PostAiConversationsByIdRunsByRunIdStopErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostAiConversationsByIdRunsByRunIdStopResponses,
    PostAiConversationsByIdRunsByRunIdStopErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/ai/conversations/{id}/runs/{runID}/stop",
    ...options,
  });

/**
 * List reviewed exercise catalog
 */
export const getExerciseCatalog = <ThrowOnError extends boolean = false>(
  options?: Options<GetExerciseCatalogData, ThrowOnError>,
): RequestResult<
  GetExerciseCatalogResponses,
  GetExerciseCatalogErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetExerciseCatalogResponses,
    GetExerciseCatalogErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercise-catalog",
    ...options,
  });

/**
 * List exercises
 *
 * Get all exercises for the authenticated user
 */
export const getExercises = <ThrowOnError extends boolean = false>(
  options?: Options<GetExercisesData, ThrowOnError>,
): RequestResult<GetExercisesResponses, GetExercisesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetExercisesResponses,
    GetExercisesErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises",
    ...options,
  });

/**
 * Get or create exercise
 *
 * Get an existing exercise by name or create it if it doesn't exist
 */
export const postExercises = <ThrowOnError extends boolean = false>(
  options: Options<PostExercisesData, ThrowOnError>,
): RequestResult<PostExercisesResponses, PostExercisesErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostExercisesResponses,
    PostExercisesErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete an exercise
 *
 * Delete a specific exercise and all its associated sets. Only the owner of the exercise can delete it.
 */
export const deleteExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteExercisesByIdData, ThrowOnError>,
): RequestResult<
  DeleteExercisesByIdResponses,
  DeleteExercisesByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteExercisesByIdResponses,
    DeleteExercisesByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}",
    ...options,
  });

/**
 * Get exercise with sets
 *
 * Get a specific exercise (metadata) plus all its sets from workouts. Sets is empty when exercise exists but has no sets.
 */
export const getExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<GetExercisesByIdData, ThrowOnError>,
): RequestResult<
  GetExercisesByIdResponses,
  GetExercisesByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetExercisesByIdResponses,
    GetExercisesByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}",
    ...options,
  });

/**
 * Update an exercise name
 *
 * Update the name of an exercise by ID (must belong to authenticated user)
 */
export const patchExercisesById = <ThrowOnError extends boolean = false>(
  options: Options<PatchExercisesByIdData, ThrowOnError>,
): RequestResult<
  PatchExercisesByIdResponses,
  PatchExercisesByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchExercisesByIdResponses,
    PatchExercisesByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Classify an exercise or clear its classification
 *
 * Changes only the catalog link. An empty catalog_id clears it; name and history are preserved.
 */
export const putExercisesByIdCatalog = <ThrowOnError extends boolean = false>(
  options: Options<PutExercisesByIdCatalogData, ThrowOnError>,
): RequestResult<
  PutExercisesByIdCatalogResponses,
  PutExercisesByIdCatalogErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutExercisesByIdCatalogResponses,
    PutExercisesByIdCatalogErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}/catalog",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update exercise historical 1RM
 *
 * Set a manual historical 1RM (clears source workout) or recompute from best working-set e1RM across history.
 */
export const patchExercisesByIdHistorical1Rm = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchExercisesByIdHistorical1RmData, ThrowOnError>,
): RequestResult<
  PatchExercisesByIdHistorical1RmResponses,
  PatchExercisesByIdHistorical1RmErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchExercisesByIdHistorical1RmResponses,
    PatchExercisesByIdHistorical1RmErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}/historical-1rm",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get exercise metrics history
 *
 * Get the complete time-series of per-workout session metrics for an exercise.
 */
export const getExercisesByIdMetricsHistory = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetExercisesByIdMetricsHistoryData, ThrowOnError>,
): RequestResult<
  GetExercisesByIdMetricsHistoryResponses,
  GetExercisesByIdMetricsHistoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetExercisesByIdMetricsHistoryResponses,
    GetExercisesByIdMetricsHistoryErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}/metrics-history",
    ...options,
  });

/**
 * Get recent sets for exercise
 *
 * Get the 3 most recent sets for a specific exercise. Returns empty array when exercise has no sets.
 */
export const getExercisesByIdRecentSets = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetExercisesByIdRecentSetsData, ThrowOnError>,
): RequestResult<
  GetExercisesByIdRecentSetsResponses,
  GetExercisesByIdRecentSetsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetExercisesByIdRecentSetsResponses,
    GetExercisesByIdRecentSetsErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}/recent-sets",
    ...options,
  });

/**
 * Recommend today's sets, reps, and weight for an owned exercise
 */
export const getExercisesByIdRecommendation = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetExercisesByIdRecommendationData, ThrowOnError>,
): RequestResult<
  GetExercisesByIdRecommendationResponses,
  GetExercisesByIdRecommendationErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetExercisesByIdRecommendationResponses,
    GetExercisesByIdRecommendationErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/exercises/{id}/recommendation",
    ...options,
  });

/**
 * List active feature access grants
 *
 * Get all active feature access grants for the authenticated user
 */
export const getFeaturesAccess = <ThrowOnError extends boolean = false>(
  options?: Options<GetFeaturesAccessData, ThrowOnError>,
): RequestResult<
  GetFeaturesAccessResponses,
  GetFeaturesAccessErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetFeaturesAccessResponses,
    GetFeaturesAccessErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/features/access",
    ...options,
  });

/**
 * Get training profile
 *
 * Returns the authenticated user's durable AI training profile. First-time users receive an empty profile shape.
 */
export const getTrainingProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetTrainingProfileData, ThrowOnError>,
): RequestResult<
  GetTrainingProfileResponses,
  GetTrainingProfileErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetTrainingProfileResponses,
    GetTrainingProfileErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/training-profile",
    ...options,
  });

/**
 * Update training profile
 *
 * Replaces the authenticated user's durable AI training profile with the full submitted document.
 */
export const putTrainingProfile = <ThrowOnError extends boolean = false>(
  options: Options<PutTrainingProfileData, ThrowOnError>,
): RequestResult<
  PutTrainingProfileResponses,
  PutTrainingProfileErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutTrainingProfileResponses,
    PutTrainingProfileErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/training-profile",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List workouts
 *
 * Get all workouts for the authenticated user
 */
export const getWorkouts = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkoutsData, ThrowOnError>,
): RequestResult<GetWorkoutsResponses, GetWorkoutsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetWorkoutsResponses,
    GetWorkoutsErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts",
    ...options,
  });

/**
 * Create a new workout
 *
 * Create a new workout with exercises and sets
 */
export const postWorkouts = <ThrowOnError extends boolean = false>(
  options: Options<PostWorkoutsData, ThrowOnError>,
): RequestResult<PostWorkoutsResponses, PostWorkoutsErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostWorkoutsResponses,
    PostWorkoutsErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get contribution graph data
 *
 * Get complete workout contribution history, including daily working set counts and intensity levels (0-4) for analytics visualizations
 */
export const getWorkoutsContributionData = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetWorkoutsContributionDataData, ThrowOnError>,
): RequestResult<
  GetWorkoutsContributionDataResponses,
  GetWorkoutsContributionDataErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetWorkoutsContributionDataResponses,
    GetWorkoutsContributionDataErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts/contribution-data",
    ...options,
  });

/**
 * List workout focus values
 *
 * Get all distinct workout focus values for the authenticated user. Returns 200 OK with an empty array if no workout focus values exist.
 */
export const getWorkoutsFocusValues = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkoutsFocusValuesData, ThrowOnError>,
): RequestResult<
  GetWorkoutsFocusValuesResponses,
  GetWorkoutsFocusValuesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetWorkoutsFocusValuesResponses,
    GetWorkoutsFocusValuesErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts/focus-values",
    ...options,
  });

/**
 * Get new workout context
 *
 * Get the newest reusable workout per focus area plus the latest workout note for the authenticated user.
 */
export const getWorkoutsNewWorkoutContext = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetWorkoutsNewWorkoutContextData, ThrowOnError>,
): RequestResult<
  GetWorkoutsNewWorkoutContextResponses,
  GetWorkoutsNewWorkoutContextErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetWorkoutsNewWorkoutContextResponses,
    GetWorkoutsNewWorkoutContextErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts/new-workout-context",
    ...options,
  });

/**
 * Delete a workout
 *
 * Delete a specific workout and all its associated sets. Only the owner of the workout can delete it.
 */
export const deleteWorkoutsById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkoutsByIdData, ThrowOnError>,
): RequestResult<
  DeleteWorkoutsByIdResponses,
  DeleteWorkoutsByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteWorkoutsByIdResponses,
    DeleteWorkoutsByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts/{id}",
    ...options,
  });

/**
 * Get workout with sets
 *
 * Get a specific workout with all its sets and exercises
 */
export const getWorkoutsById = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkoutsByIdData, ThrowOnError>,
): RequestResult<
  GetWorkoutsByIdResponses,
  GetWorkoutsByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetWorkoutsByIdResponses,
    GetWorkoutsByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts/{id}",
    ...options,
  });

/**
 * Update an existing workout (full replacement)
 *
 * Updates a workout using full replacement semantics. The client must provide the complete workout data including date and at least one exercise with sets. This endpoint replaces the entire workout, deleting existing exercises/sets and creating new ones. For partial updates, PATCH will be implemented in a future version. Returns 204 No Content on success.
 */
export const putWorkoutsById = <ThrowOnError extends boolean = false>(
  options: Options<PutWorkoutsByIdData, ThrowOnError>,
): RequestResult<
  PutWorkoutsByIdResponses,
  PutWorkoutsByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutWorkoutsByIdResponses,
    PutWorkoutsByIdErrors,
    ThrowOnError
  >({
    security: [{ name: "x-stack-access-token", type: "apiKey" }],
    url: "/workouts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
