// This file is auto-generated by @hey-api/openapi-ts

export type ExerciseCreateExerciseRequest = {
  name: string;
};

export type ExerciseCreateExerciseResponse = {
  created_at: string;
  id: number;
  name: string;
  updated_at: string;
  user_id: string;
};

export type ExerciseExerciseResponse = {
  created_at: string;
  id: number;
  name: string;
  updated_at: string;
  user_id: string;
};

export type ExerciseExerciseWithSetsResponse = {
  exercise_id: number;
  exercise_name: string;
  exercise_order?: number;
  reps: number;
  set_id: number;
  set_order?: number;
  set_type: string;
  volume: number;
  weight?: number;
  workout_date: string;
  workout_id: number;
  workout_notes?: string;
};

export type ExerciseRecentSetsResponse = {
  created_at: string;
  exercise_order?: number;
  reps: number;
  set_id: number;
  set_order?: number;
  weight?: number;
  workout_date: string;
  workout_id: number;
};

export type ResponseErrorResponse = {
  message?: string;
};

export type ResponseSuccessResponse = {
  success?: boolean;
};

export type WorkoutCreateWorkoutRequest = {
  date: string;
  exercises: Array<WorkoutExerciseInput>;
  notes?: string;
};

export type WorkoutExerciseInput = {
  name: string;
  sets: Array<WorkoutSetInput>;
};

export type WorkoutSetInput = {
  reps: number;
  setType: "warmup" | "working";
  weight?: number;
};

export type WorkoutUpdateExercise = {
  name: string;
  sets: Array<WorkoutUpdateSet>;
};

export type WorkoutUpdateSet = {
  reps: number;
  setType: "warmup" | "working";
  weight?: number;
};

export type WorkoutUpdateWorkoutRequest = {
  date: string;
  exercises: Array<WorkoutUpdateExercise>;
  notes?: string;
};

/**
 * Workout response model
 */
export type WorkoutWorkoutResponse = {
  created_at: string;
  date: string;
  id: number;
  notes?: string;
  updated_at: string;
  user_id: string;
};

export type WorkoutWorkoutWithSetsResponse = {
  exercise_id: number;
  exercise_name: string;
  exercise_order?: number;
  reps: number;
  set_id: number;
  set_order?: number;
  set_type: string;
  volume: number;
  weight?: number;
  workout_date: string;
  workout_id: number;
  workout_notes?: string;
};

export type GetExercisesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/exercises";
};

export type GetExercisesErrors = {
  /**
   * Unauthorized
   */
  401: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type GetExercisesError = GetExercisesErrors[keyof GetExercisesErrors];

export type GetExercisesResponses = {
  /**
   * OK
   */
  200: Array<ExerciseExerciseResponse>;
};

export type GetExercisesResponse =
  GetExercisesResponses[keyof GetExercisesResponses];

export type PostExercisesData = {
  /**
   * Exercise data
   */
  body: ExerciseCreateExerciseRequest;
  path?: never;
  query?: never;
  url: "/exercises";
};

export type PostExercisesErrors = {
  /**
   * Bad Request
   */
  400: ResponseErrorResponse;
  /**
   * Unauthorized
   */
  401: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type PostExercisesError = PostExercisesErrors[keyof PostExercisesErrors];

export type PostExercisesResponses = {
  /**
   * OK
   */
  200: ExerciseCreateExerciseResponse;
};

export type PostExercisesResponse =
  PostExercisesResponses[keyof PostExercisesResponses];

export type GetExercisesByIdData = {
  body?: never;
  path: {
    /**
     * Exercise ID
     */
    id: number;
  };
  query?: never;
  url: "/exercises/{id}";
};

export type GetExercisesByIdErrors = {
  /**
   * Bad Request
   */
  400: ResponseErrorResponse;
  /**
   * Unauthorized
   */
  401: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type GetExercisesByIdError =
  GetExercisesByIdErrors[keyof GetExercisesByIdErrors];

export type GetExercisesByIdResponses = {
  /**
   * Success (may be empty array)
   */
  200: Array<ExerciseExerciseWithSetsResponse>;
};

export type GetExercisesByIdResponse =
  GetExercisesByIdResponses[keyof GetExercisesByIdResponses];

export type GetExercisesByIdRecentSetsData = {
  body?: never;
  path: {
    /**
     * Exercise ID
     */
    id: number;
  };
  query?: never;
  url: "/exercises/{id}/recent-sets";
};

export type GetExercisesByIdRecentSetsErrors = {
  /**
   * Bad Request
   */
  400: ResponseErrorResponse;
  /**
   * Unauthorized
   */
  401: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type GetExercisesByIdRecentSetsError =
  GetExercisesByIdRecentSetsErrors[keyof GetExercisesByIdRecentSetsErrors];

export type GetExercisesByIdRecentSetsResponses = {
  /**
   * Success (may be empty array)
   */
  200: Array<ExerciseRecentSetsResponse>;
};

export type GetExercisesByIdRecentSetsResponse =
  GetExercisesByIdRecentSetsResponses[keyof GetExercisesByIdRecentSetsResponses];

export type GetWorkoutsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/workouts";
};

export type GetWorkoutsErrors = {
  /**
   * Unauthorized
   */
  401: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type GetWorkoutsError = GetWorkoutsErrors[keyof GetWorkoutsErrors];

export type GetWorkoutsResponses = {
  /**
   * OK
   */
  200: Array<WorkoutWorkoutResponse>;
};

export type GetWorkoutsResponse =
  GetWorkoutsResponses[keyof GetWorkoutsResponses];

export type PostWorkoutsData = {
  /**
   * Workout data
   */
  body: WorkoutCreateWorkoutRequest;
  path?: never;
  query?: never;
  url: "/workouts";
};

export type PostWorkoutsErrors = {
  /**
   * Bad Request
   */
  400: ResponseErrorResponse;
  /**
   * Unauthorized
   */
  401: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type PostWorkoutsError = PostWorkoutsErrors[keyof PostWorkoutsErrors];

export type PostWorkoutsResponses = {
  /**
   * OK
   */
  200: ResponseSuccessResponse;
};

export type PostWorkoutsResponse =
  PostWorkoutsResponses[keyof PostWorkoutsResponses];

export type DeleteWorkoutsByIdData = {
  body?: never;
  path: {
    /**
     * Workout ID
     */
    id: number;
  };
  query?: never;
  url: "/workouts/{id}";
};

export type DeleteWorkoutsByIdErrors = {
  /**
   * Bad Request - Invalid workout ID
   */
  400: ResponseErrorResponse;
  /**
   * Unauthorized - Invalid token
   */
  401: ResponseErrorResponse;
  /**
   * Not Found - Workout not found or doesn't belong to user
   */
  404: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type DeleteWorkoutsByIdError =
  DeleteWorkoutsByIdErrors[keyof DeleteWorkoutsByIdErrors];

export type DeleteWorkoutsByIdResponses = {
  /**
   * No Content - Workout deleted successfully
   */
  204: unknown;
};

export type GetWorkoutsByIdData = {
  body?: never;
  path: {
    /**
     * Workout ID
     */
    id: number;
  };
  query?: never;
  url: "/workouts/{id}";
};

export type GetWorkoutsByIdErrors = {
  /**
   * Bad Request
   */
  400: ResponseErrorResponse;
  /**
   * Unauthorized
   */
  401: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type GetWorkoutsByIdError =
  GetWorkoutsByIdErrors[keyof GetWorkoutsByIdErrors];

export type GetWorkoutsByIdResponses = {
  /**
   * OK
   */
  200: Array<WorkoutWorkoutWithSetsResponse>;
};

export type GetWorkoutsByIdResponse =
  GetWorkoutsByIdResponses[keyof GetWorkoutsByIdResponses];

export type PutWorkoutsByIdData = {
  /**
   * Complete workout data for replacement
   */
  body: WorkoutUpdateWorkoutRequest;
  path: {
    /**
     * Workout ID
     */
    id: number;
  };
  query?: never;
  url: "/workouts/{id}";
};

export type PutWorkoutsByIdErrors = {
  /**
   * Bad Request - Invalid input or validation error
   */
  400: ResponseErrorResponse;
  /**
   * Unauthorized - Invalid token
   */
  401: ResponseErrorResponse;
  /**
   * Not Found - Workout not found or doesn't belong to user
   */
  404: ResponseErrorResponse;
  /**
   * Internal Server Error
   */
  500: ResponseErrorResponse;
};

export type PutWorkoutsByIdError =
  PutWorkoutsByIdErrors[keyof PutWorkoutsByIdErrors];

export type PutWorkoutsByIdResponses = {
  /**
   * No Content - Workout updated successfully
   */
  204: unknown;
};

export type ClientOptions = {
  baseUrl: "http://localhost:8080/api" | (string & {});
};
