// Package docs registers the generated Swagger document for the in-process Swagger UI.
package docs

import (
	_ "embed"

	"github.com/swaggo/swag"
)

// swaggerJSON is generated by `make swagger`. Embedding the authority-free JSON
// avoids swag's Go template output, which emits invalid empty host and schemes
// fields when those optional Swagger 2 fields are intentionally unspecified.
//
//go:embed swagger.json
var swaggerJSON string

// SwaggerInfo is registered under swag's default instance name.
var SwaggerInfo = &swag.Spec{
	InfoInstanceName: "swagger",
	SwaggerTemplate:  swaggerJSON,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
