import { type ReactNode, useEffect, useRef, useState } from "react";
import { CheckCircle } from "lucide-react";
import { useTheme } from "@/components/theme-provider";
import { useMediaQuery } from "@/hooks/use-media-query";
import { cn } from "@/lib/utils";

// Clips are real recordings of guest demo mode, regenerated by
// `bun run media:capture` (see client/scripts/capture-landing-media.mjs).
const STEPS = [
  {
    id: "log",
    eyebrow: "Log",
    title: "Log a set in seconds.",
    body: "Pick an exercise and your recent sets are right there. Save weight and reps, then repeat the last set with one tap.",
    points: [
      "Recent sets beside every exercise",
      "One tap to repeat the last set",
    ],
    caption: "Adding Bench Press to today's workout and logging three sets.",
  },
  {
    id: "repeat",
    eyebrow: "Repeat",
    title: "Start from what already worked.",
    body: "Open any past session and repeat it. Exercises and sets come back as today's draft, with your last note on top.",
    points: ["Copies exercises and sets", "Your last workout note resurfaces"],
    caption:
      "Opening Sunday's upper-body session and repeating it as a new draft.",
  },
  {
    id: "review",
    eyebrow: "Review",
    title: "See where training is going.",
    body: "Weekly pace, an activity map, and volume trends live together, so progress is visible without digging through old sessions.",
    points: [
      "Activity across the last few months",
      "Volume by week, month, or year",
    ],
    caption:
      "Scrolling analytics: workout pace, the activity map, and daily volume.",
  },
] as const;

type Step = (typeof STEPS)[number];

function StepClip({
  step,
  theme,
  playing,
  reducedMotion,
  className,
}: {
  step: Step;
  theme: "light" | "dark";
  playing: boolean;
  reducedMotion: boolean;
  className?: string;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const base = `/media/how-it-works/${step.id}-${theme}`;

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    if (playing && !reducedMotion) {
      video.currentTime = 0;
      video.play().catch(() => {
        // Autoplay can be refused (e.g. data saver); the poster stays visible.
      });
    } else if (!video.paused) {
      video.pause();
    }
  }, [playing, reducedMotion, base]);

  return (
    <video
      ref={videoRef}
      key={base}
      className={className}
      poster={`${base}.webp`}
      muted
      loop
      playsInline
      preload="none"
      aria-hidden="true"
    >
      <source
        src={`${base}.mp4`}
        type="video/mp4"
      />
    </video>
  );
}

function PhoneFrame({
  className,
  children,
}: {
  className?: string;
  children: ReactNode;
}) {
  return (
    <div
      className={cn(
        "relative w-[17rem] shrink-0 rounded-[2.75rem] bg-neutral-900 p-2 shadow-2xl ring-1 ring-black/10 dark:bg-neutral-800 dark:ring-white/10",
        className,
      )}
    >
      <div className="relative aspect-[390/844] overflow-hidden rounded-[2.25rem] bg-background">
        {children}
      </div>
    </div>
  );
}

export function HowItWorks() {
  const { theme } = useTheme();
  const reducedMotion = useMediaQuery("(prefers-reduced-motion: reduce)");
  const isDesktop = useMediaQuery("(min-width: 1024px)");
  const [activeIndex, setActiveIndex] = useState(0);
  const [inView, setInView] = useState(false);
  const sectionRef = useRef<HTMLElement>(null);
  const stepsRef = useRef<HTMLOListElement>(null);
  const railRef = useRef<HTMLDivElement>(null);
  const stepRefs = useRef<(HTMLLIElement | null)[]>([]);

  // The step crossing the middle of the viewport is the active one.
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          const index = stepRefs.current.findIndex(
            (step) => step === entry.target,
          );
          if (entry.isIntersecting && index >= 0) setActiveIndex(index);
        }
      },
      { rootMargin: "-45% 0px -45% 0px" },
    );
    for (const step of stepRefs.current) {
      if (step) observer.observe(step);
    }
    return () => observer.disconnect();
  }, []);

  // Only play while the section is on screen.
  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;
    const observer = new IntersectionObserver(([entry]) =>
      setInView(entry.isIntersecting),
    );
    observer.observe(section);
    return () => observer.disconnect();
  }, []);

  // Progress rail follows scroll position through the steps (no re-renders).
  useEffect(() => {
    let frame = 0;
    const update = () => {
      frame = 0;
      const steps = stepsRef.current;
      const rail = railRef.current;
      if (!steps || !rail) return;
      const rect = steps.getBoundingClientRect();
      const progress = (window.innerHeight / 2 - rect.top) / rect.height;
      rail.style.setProperty(
        "--progress",
        String(Math.min(1, Math.max(0, progress))),
      );
    };
    const onScroll = () => {
      if (!frame) frame = requestAnimationFrame(update);
    };
    update();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll);
    return () => {
      cancelAnimationFrame(frame);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    };
  }, []);

  const goToStep = (index: number) => {
    stepRefs.current[index]?.scrollIntoView({
      block: "center",
      behavior: reducedMotion ? "auto" : "smooth",
    });
  };

  return (
    <section
      ref={sectionRef}
      aria-labelledby="how-it-works-heading"
      className="px-6 py-16"
    >
      <div className="mx-auto max-w-7xl">
        <div className="mb-8 text-center lg:mb-0">
          <p className="mb-4 text-sm font-semibold uppercase tracking-widest text-primary">
            How it works
          </p>
          <h2
            id="how-it-works-heading"
            className="text-4xl font-bold leading-snug tracking-wide text-foreground md:text-6xl"
          >
            Log it. Repeat it.
            <br />
            <span className="text-muted-foreground">
              See where it&apos;s going.
            </span>
          </h2>
        </div>

        <div className="mx-auto grid max-w-6xl gap-16 lg:grid-cols-2">
          <ol
            ref={stepsRef}
            className="lg:py-[10vh]"
          >
            {STEPS.map((step, index) => (
              <li
                key={step.id}
                ref={(node) => {
                  stepRefs.current[index] = node;
                }}
                aria-current={index === activeIndex ? "step" : undefined}
                className={cn(
                  "flex flex-col justify-center py-10 transition-opacity duration-500 motion-reduce:transition-none lg:min-h-[75vh] lg:max-w-lg lg:py-0",
                  index === activeIndex ? "lg:opacity-100" : "lg:opacity-35",
                )}
              >
                <p className="text-sm font-semibold uppercase tracking-widest text-primary">
                  {String(index + 1).padStart(2, "0")} · {step.eyebrow}
                </p>
                <h3 className="mt-3 text-3xl font-bold leading-tight text-foreground md:text-4xl">
                  {step.title}
                </h3>
                <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
                  {step.body}
                </p>
                <ul className="mt-6 space-y-3 text-muted-foreground">
                  {step.points.map((point) => (
                    <li
                      key={point}
                      className="flex items-center gap-3"
                    >
                      <CheckCircle className="h-5 w-5 shrink-0 text-primary" />
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
                <p className="sr-only">{step.caption}</p>

                {/* Below lg each step carries its own phone; lg+ uses the pinned one. */}
                <PhoneFrame className="mx-auto mt-10 lg:hidden">
                  <StepClip
                    step={step}
                    theme={theme}
                    playing={!isDesktop && inView && index === activeIndex}
                    reducedMotion={reducedMotion}
                    className="absolute inset-0 h-full w-full object-cover"
                  />
                </PhoneFrame>
              </li>
            ))}
          </ol>

          {/* Starts level with step 1 (10vh list padding + half a 75vh step,
              minus half the ~38rem phone), then pins mid-screen while scrolling. */}
          <div className="sticky top-[max(5rem,calc(50vh-18rem))] mt-[max(4rem,calc(47.5vh-19rem))] hidden h-fit items-center justify-center gap-6 self-start lg:flex">
            <PhoneFrame>
              {STEPS.map((step, index) => (
                <StepClip
                  key={step.id}
                  step={step}
                  theme={theme}
                  playing={isDesktop && inView && index === activeIndex}
                  reducedMotion={reducedMotion}
                  className={cn(
                    "absolute inset-0 h-full w-full object-cover transition-opacity duration-500 motion-reduce:transition-none",
                    index === activeIndex ? "opacity-100" : "opacity-0",
                  )}
                />
              ))}
            </PhoneFrame>

            <div
              ref={railRef}
              className="flex flex-col items-center gap-3"
            >
              {STEPS.map((step, index) => (
                <button
                  key={step.id}
                  type="button"
                  onClick={() => goToStep(index)}
                  aria-label={`Show step ${index + 1}: ${step.eyebrow}`}
                  className={cn(
                    "h-8 w-8 rounded-full border text-xs font-semibold transition-colors",
                    index <= activeIndex
                      ? "border-primary bg-primary text-primary-foreground"
                      : "border-border bg-card text-muted-foreground hover:text-foreground",
                  )}
                >
                  {index + 1}
                </button>
              ))}
              <div className="relative mt-1 h-24 w-0.5 overflow-hidden rounded-full bg-border">
                <div className="absolute inset-0 origin-top scale-y-[var(--progress,0)] bg-primary" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
