import { type ReactNode, useEffect, useRef, useState } from "react";
import { CheckCircle, Pause, Play } from "lucide-react";
import { useTheme } from "@/components/theme-provider";
import { useMediaQuery } from "@/hooks/use-media-query";
import { cn } from "@/lib/utils";

// Clips are real recordings of guest demo mode, regenerated by
// `bun run media:capture` (see client/scripts/capture-landing-media.mjs).
const STEPS = [
  {
    id: "log",
    eyebrow: "Log",
    title: "Log a set in seconds.",
    body: "Pick an exercise and your recent sets are right there. Save weight and reps, then repeat the last set with one tap.",
    points: [
      "Recent sets beside every exercise",
      "One tap to repeat the last set",
    ],
    caption: "Adding Bench Press to today's workout and logging three sets.",
  },
  {
    id: "repeat",
    eyebrow: "Repeat",
    title: "Start from what already worked.",
    body: "Open any past session and repeat it. Exercises and sets come back as today's draft, with your last note on top.",
    points: ["Copies exercises and sets", "Your last workout note resurfaces"],
    caption:
      "Opening Sunday's upper-body session and repeating it as a new draft.",
  },
  {
    id: "review",
    eyebrow: "Review",
    title: "See where training is going.",
    body: "Weekly pace, an activity map, and volume trends live together, so progress is visible without digging through old sessions.",
    points: [
      "Activity across the last few months",
      "Volume by week, month, or year",
    ],
    caption:
      "Scrolling analytics: workout pace, the activity map, and daily volume.",
  },
] as const;

type Step = (typeof STEPS)[number];

function StepClip({
  step,
  theme,
  active,
  playing,
  reducedMotion,
  className,
}: {
  step: Step;
  theme: "light" | "dark";
  active: boolean;
  playing: boolean;
  reducedMotion: boolean;
  className?: string;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const base = `/media/how-it-works/${step.id}-${theme}`;

  // Rewind when the step stops being current, so it starts fresh next time
  // while a pause/resume on the current step continues where it left off.
  useEffect(() => {
    const video = videoRef.current;
    if (video && !active) video.currentTime = 0;
  }, [active]);

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    if (playing && !reducedMotion) {
      video.play().catch(() => {
        // Autoplay can be refused (e.g. data saver); the poster stays visible.
      });
    } else if (!video.paused) {
      video.pause();
    }
  }, [playing, reducedMotion, base]);

  return (
    <video
      ref={videoRef}
      key={base}
      className={className}
      poster={`${base}.webp`}
      muted
      loop
      playsInline
      preload="none"
      aria-hidden="true"
    >
      <source
        src={`${base}.mp4`}
        type="video/mp4"
      />
    </video>
  );
}

// Looping clips run longer than five seconds, so visitors need a way to stop
// them (WCAG 2.2.2). One shared state drives every phone's toggle.
function PlaybackToggle({
  paused,
  onToggle,
}: {
  paused: boolean;
  onToggle: () => void;
}) {
  const Icon = paused ? Play : Pause;
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-label={paused ? "Play demo videos" : "Pause demo videos"}
      className="absolute bottom-3 right-3 z-10 grid h-9 w-9 place-items-center rounded-full border border-border bg-background/85 text-foreground shadow-md backdrop-blur hover:bg-background focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
    >
      <Icon className="h-4 w-4" />
    </button>
  );
}

function PhoneFrame({
  className,
  children,
}: {
  className?: string;
  children: ReactNode;
}) {
  return (
    <div
      className={cn(
        "relative w-[17rem] shrink-0 rounded-[2.75rem] bg-neutral-900 p-2 shadow-2xl ring-1 ring-black/10 dark:bg-neutral-800 dark:ring-white/10",
        className,
      )}
    >
      <div className="relative aspect-[390/844] overflow-hidden rounded-[2.25rem] bg-background">
        {children}
      </div>
    </div>
  );
}

export function HowItWorks() {
  const { theme } = useTheme();
  const reducedMotion = useMediaQuery("(prefers-reduced-motion: reduce)");
  const isDesktop = useMediaQuery("(min-width: 1024px)");
  const [activeIndex, setActiveIndex] = useState(0);
  const [inView, setInView] = useState(false);
  const [userPaused, setUserPaused] = useState(false);
  const canPlay = inView && !userPaused;
  const togglePlayback = () => setUserPaused((paused) => !paused);
  const sectionRef = useRef<HTMLElement>(null);
  const stepsRef = useRef<HTMLOListElement>(null);
  const railRef = useRef<HTMLDivElement>(null);
  const stepRefs = useRef<(HTMLLIElement | null)[]>([]);

  // The step crossing the middle of the viewport is the active one. Margins
  // are pixels from the viewport height (percentage margins are not resolved
  // against height consistently), so the observer is rebuilt when it changes.
  useEffect(() => {
    let observer: IntersectionObserver | undefined;
    let observedHeight = 0;
    const observe = () => {
      if (window.innerHeight === observedHeight) return;
      observedHeight = window.innerHeight;
      observer?.disconnect();
      const margin = Math.round(observedHeight * 0.45);
      observer = new IntersectionObserver(
        (entries) => {
          for (const entry of entries) {
            const index = stepRefs.current.findIndex(
              (step) => step === entry.target,
            );
            if (entry.isIntersecting && index >= 0) setActiveIndex(index);
          }
        },
        { rootMargin: `-${margin}px 0px -${margin}px 0px` },
      );
      for (const step of stepRefs.current) {
        if (step) observer.observe(step);
      }
    };
    observe();
    window.addEventListener("resize", observe);
    return () => {
      window.removeEventListener("resize", observe);
      observer?.disconnect();
    };
  }, []);

  // Only play while the section is on screen.
  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;
    const observer = new IntersectionObserver(([entry]) =>
      setInView(entry.isIntersecting),
    );
    observer.observe(section);
    return () => observer.disconnect();
  }, []);

  // Progress rail follows scroll position through the steps (no re-renders).
  useEffect(() => {
    let frame = 0;
    const update = () => {
      frame = 0;
      const steps = stepsRef.current;
      const rail = railRef.current;
      if (!steps || !rail) return;
      const rect = steps.getBoundingClientRect();
      const progress = (window.innerHeight / 2 - rect.top) / rect.height;
      rail.style.setProperty(
        "--progress",
        String(Math.min(1, Math.max(0, progress))),
      );
    };
    const onScroll = () => {
      if (!frame) frame = requestAnimationFrame(update);
    };
    update();
    window.addEventListener("scroll", onScroll, { passive: true });
    window.addEventListener("resize", onScroll);
    return () => {
      cancelAnimationFrame(frame);
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
    };
  }, []);

  const goToStep = (index: number) => {
    stepRefs.current[index]?.scrollIntoView({
      block: "center",
      behavior: reducedMotion ? "auto" : "smooth",
    });
  };

  return (
    <section
      ref={sectionRef}
      aria-labelledby="how-it-works-heading"
      className="px-6 py-16"
    >
      <div className="mx-auto max-w-7xl">
        <div className="mb-8 text-center lg:mb-0">
          <p className="mb-4 text-sm font-semibold uppercase tracking-widest text-primary">
            How it works
          </p>
          <h2
            id="how-it-works-heading"
            className="text-4xl font-bold leading-snug tracking-wide text-foreground md:text-6xl"
          >
            Log it. Repeat it.
            <br />
            <span className="text-muted-foreground">
              See where it&apos;s going.
            </span>
          </h2>
        </div>

        <div className="mx-auto grid max-w-6xl gap-16 lg:grid-cols-2">
          <ol
            ref={stepsRef}
            className="lg:py-[10vh]"
          >
            {STEPS.map((step, index) => (
              <li
                key={step.id}
                ref={(node) => {
                  stepRefs.current[index] = node;
                }}
                aria-current={index === activeIndex ? "step" : undefined}
                className={cn(
                  "flex flex-col justify-center py-10 transition-colors duration-500 motion-reduce:transition-none lg:min-h-[75vh] lg:max-w-lg lg:border-l-2 lg:py-0 lg:pl-8",
                  index === activeIndex
                    ? "lg:border-primary"
                    : "lg:border-border",
                )}
              >
                <p
                  className={cn(
                    "text-sm font-semibold uppercase tracking-widest text-primary",
                    index !== activeIndex && "lg:text-muted-foreground",
                  )}
                >
                  {String(index + 1).padStart(2, "0")} · {step.eyebrow}
                </p>
                <h3 className="mt-3 text-3xl font-bold leading-tight text-foreground md:text-4xl">
                  {step.title}
                </h3>
                <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
                  {step.body}
                </p>
                <ul className="mt-6 space-y-3 text-muted-foreground">
                  {step.points.map((point) => (
                    <li
                      key={point}
                      className="flex items-center gap-3"
                    >
                      <CheckCircle className="h-5 w-5 shrink-0 text-primary" />
                      <span>{point}</span>
                    </li>
                  ))}
                </ul>
                <p className="sr-only">{step.caption}</p>

                {/* Below lg each step carries its own phone; lg+ uses the pinned one. */}
                <PhoneFrame className="mx-auto mt-10 lg:hidden">
                  <StepClip
                    step={step}
                    theme={theme}
                    active={index === activeIndex}
                    playing={!isDesktop && canPlay && index === activeIndex}
                    reducedMotion={reducedMotion}
                    className="absolute inset-0 h-full w-full object-cover"
                  />
                  {reducedMotion ? null : (
                    <PlaybackToggle
                      paused={userPaused}
                      onToggle={togglePlayback}
                    />
                  )}
                </PhoneFrame>
              </li>
            ))}
          </ol>

          {/* Starts level with step 1 (10vh list padding + half a 75vh step,
              minus half the ~38rem phone), then pins mid-screen while scrolling.
              On short viewports the width shrinks so the whole phone fits below
              the 5rem sticky offset: height = (w - 1rem) * 844/390 + 1rem. */}
          <div className="sticky top-[max(5rem,calc(50vh-18rem))] mt-[max(4rem,calc(47.5vh-19rem))] hidden h-fit items-center justify-center gap-6 self-start lg:flex">
            <PhoneFrame className="w-[min(17rem,calc((100vh-9rem)*0.4621+1rem))]">
              {STEPS.map((step, index) => (
                <StepClip
                  key={step.id}
                  step={step}
                  theme={theme}
                  active={index === activeIndex}
                  playing={isDesktop && canPlay && index === activeIndex}
                  reducedMotion={reducedMotion}
                  className={cn(
                    "absolute inset-0 h-full w-full object-cover transition-opacity duration-500 motion-reduce:transition-none",
                    index === activeIndex ? "opacity-100" : "opacity-0",
                  )}
                />
              ))}
              {reducedMotion ? null : (
                <PlaybackToggle
                  paused={userPaused}
                  onToggle={togglePlayback}
                />
              )}
            </PhoneFrame>

            <div
              ref={railRef}
              className="flex flex-col items-center gap-3"
            >
              {STEPS.map((step, index) => (
                <button
                  key={step.id}
                  type="button"
                  onClick={() => goToStep(index)}
                  aria-label={`Show step ${index + 1}: ${step.eyebrow}`}
                  aria-current={index === activeIndex ? "step" : undefined}
                  className={cn(
                    "h-8 w-8 rounded-full border text-xs font-semibold transition-colors",
                    index === activeIndex &&
                      "border-primary bg-primary text-primary-foreground",
                    index < activeIndex &&
                      "border-primary bg-primary/10 text-primary",
                    index > activeIndex &&
                      "border-border bg-card text-muted-foreground hover:text-foreground",
                  )}
                >
                  {index + 1}
                </button>
              ))}
              <div className="relative mt-1 h-24 w-0.5 overflow-hidden rounded-full bg-border">
                <div className="absolute inset-0 origin-top scale-y-[var(--progress,0)] bg-primary" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
