name: fittrack-local-pg15

services:
  postgres:
    image: postgres:15.19-bookworm@sha256:539ceaaae49b3a7c8a04467cf00cc6788d8e3f1675df41860d86eebc4c40524f
    labels:
      fittrack.local-postgres: "15.19"
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./_db-data-pg15:/var/lib/postgresql/data
    container_name: fittrack-postgres15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
