import type { ExerciseExerciseResponse, ExerciseExerciseWithSetsResponse } from '@/client';

export const DEMO_EXERCISES: ExerciseExerciseResponse[] = [
  { id: 1, name: "Bench Press" },
  { id: 2, name: "Squat" },
  { id: 3, name: "Deadlift" },
  { id: 4, name: "Pull-ups" },
  { id: 5, name: "Overhead Press" },
];

export const DEMO_EXERCISE_SETS: ExerciseExerciseWithSetsResponse[] = [
  // Bench Press - Recent 3 workouts
  {
    set_id: 1,
    workout_id: 1,
    exercise_id: 1,
    exercise_name: "Bench Press",
    weight: 135,
    reps: 10,
    volume: 1350,
    set_type: "normal",
    set_order: 1,
    exercise_order: 1,
    workout_date: "2025-01-20T10:30:00Z",
    workout_notes: "Push",
  },
  {
    set_id: 2,
    workout_id: 1,
    exercise_id: 1,
    exercise_name: "Bench Press",
    weight: 145,
    reps: 8,
    volume: 1160,
    set_type: "normal",
    set_order: 2,
    exercise_order: 1,
    workout_date: "2025-01-20T10:30:00Z",
    workout_notes: "Push",
  },
  {
    set_id: 3,
    workout_id: 1,
    exercise_id: 1,
    exercise_name: "Bench Press",
    weight: 155,
    reps: 6,
    volume: 930,
    set_type: "normal",
    set_order: 3,
    exercise_order: 1,
    workout_date: "2025-01-20T10:30:00Z",
    workout_notes: "Push",
  },
  {
    set_id: 13,
    workout_id: 4,
    exercise_id: 1,
    exercise_name: "Bench Press",
    weight: 125,
    reps: 12,
    volume: 1500,
    set_type: "normal",
    set_order: 1,
    exercise_order: 1,
    workout_date: "2025-01-17T11:00:00Z",
    workout_notes: "Push",
  },
  {
    set_id: 14,
    workout_id: 4,
    exercise_id: 1,
    exercise_name: "Bench Press",
    weight: 135,
    reps: 10,
    volume: 1350,
    set_type: "normal",
    set_order: 2,
    exercise_order: 1,
    workout_date: "2025-01-17T11:00:00Z",
    workout_notes: "Push",
  },
  {
    set_id: 15,
    workout_id: 4,
    exercise_id: 1,
    exercise_name: "Bench Press",
    weight: 145,
    reps: 8,
    volume: 1160,
    set_type: "normal",
    set_order: 3,
    exercise_order: 1,
    workout_date: "2025-01-17T11:00:00Z",
    workout_notes: "Push",
  },

  // Squat - Recent 2 workouts
  {
    set_id: 4,
    workout_id: 2,
    exercise_id: 2,
    exercise_name: "Squat",
    weight: 185,
    reps: 8,
    volume: 1480,
    set_type: "normal",
    set_order: 1,
    exercise_order: 1,
    workout_date: "2025-01-18T14:00:00Z",
    workout_notes: "Legs",
  },
  {
    set_id: 5,
    workout_id: 2,
    exercise_id: 2,
    exercise_name: "Squat",
    weight: 205,
    reps: 6,
    volume: 1230,
    set_type: "normal",
    set_order: 2,
    exercise_order: 1,
    workout_date: "2025-01-18T14:00:00Z",
    workout_notes: "Legs",
  },
  {
    set_id: 6,
    workout_id: 2,
    exercise_id: 2,
    exercise_name: "Squat",
    weight: 225,
    reps: 4,
    volume: 900,
    set_type: "normal",
    set_order: 3,
    exercise_order: 1,
    workout_date: "2025-01-18T14:00:00Z",
    workout_notes: "Legs",
  },

  // Deadlift - Recent workout
  {
    set_id: 7,
    workout_id: 3,
    exercise_id: 3,
    exercise_name: "Deadlift",
    weight: 225,
    reps: 5,
    volume: 1125,
    set_type: "normal",
    set_order: 1,
    exercise_order: 1,
    workout_date: "2025-01-19T16:30:00Z",
    workout_notes: "Pull",
  },
  {
    set_id: 8,
    workout_id: 3,
    exercise_id: 3,
    exercise_name: "Deadlift",
    weight: 245,
    reps: 3,
    volume: 735,
    set_type: "normal",
    set_order: 2,
    exercise_order: 1,
    workout_date: "2025-01-19T16:30:00Z",
    workout_notes: "Pull",
  },
  {
    set_id: 9,
    workout_id: 3,
    exercise_id: 3,
    exercise_name: "Deadlift",
    weight: 265,
    reps: 1,
    volume: 265,
    set_type: "normal",
    set_order: 3,
    exercise_order: 1,
    workout_date: "2025-01-19T16:30:00Z",
    workout_notes: "Pull",
  },

  // Pull-ups - Recent workout
  {
    set_id: 10,
    workout_id: 3,
    exercise_id: 4,
    exercise_name: "Pull-ups",
    weight: 0,
    reps: 12,
    volume: 0,
    set_type: "normal",
    set_order: 1,
    exercise_order: 2,
    workout_date: "2025-01-19T16:30:00Z",
    workout_notes: "Pull",
  },
  {
    set_id: 11,
    workout_id: 3,
    exercise_id: 4,
    exercise_name: "Pull-ups",
    weight: 0,
    reps: 10,
    volume: 0,
    set_type: "normal",
    set_order: 2,
    exercise_order: 2,
    workout_date: "2025-01-19T16:30:00Z",
    workout_notes: "Pull",
  },
  {
    set_id: 12,
    workout_id: 3,
    exercise_id: 4,
    exercise_name: "Pull-ups",
    weight: 0,
    reps: 8,
    volume: 0,
    set_type: "normal",
    set_order: 3,
    exercise_order: 2,
    workout_date: "2025-01-19T16:30:00Z",
    workout_notes: "Pull",
  },

  // Overhead Press - Recent workout
  {
    set_id: 16,
    workout_id: 1,
    exercise_id: 5,
    exercise_name: "Overhead Press",
    weight: 95,
    reps: 8,
    volume: 760,
    set_type: "normal",
    set_order: 1,
    exercise_order: 2,
    workout_date: "2025-01-20T10:30:00Z",
    workout_notes: "Push",
  },
  {
    set_id: 17,
    workout_id: 1,
    exercise_id: 5,
    exercise_name: "Overhead Press",
    weight: 105,
    reps: 6,
    volume: 630,
    set_type: "normal",
    set_order: 2,
    exercise_order: 2,
    workout_date: "2025-01-20T10:30:00Z",
    workout_notes: "Push",
  },
  {
    set_id: 18,
    workout_id: 1,
    exercise_id: 5,
    exercise_name: "Overhead Press",
    weight: 115,
    reps: 4,
    volume: 460,
    set_type: "normal",
    set_order: 3,
    exercise_order: 2,
    workout_date: "2025-01-20T10:30:00Z",
    workout_notes: "Push",
  },
];

export function getDemoExerciseById(id: number): ExerciseExerciseWithSetsResponse[] {
  return DEMO_EXERCISE_SETS.filter(set => set.exercise_id === id);
}

export function getDemoRecentSetsForExercise(id: number): ExerciseExerciseWithSetsResponse[] {
  // Return the last 5 sets for the exercise
  return DEMO_EXERCISE_SETS
    .filter(set => set.exercise_id === id)
    .sort((a, b) => new Date(b.workout_date).getTime() - new Date(a.workout_date).getTime())
    .slice(0, 5);
}