// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  deleteAiConversationsById,
  deleteExercisesById,
  deleteWorkoutsById,
  getAiConversations,
  getAiConversationsById,
  getExercises,
  getExercisesById,
  getExercisesByIdMetricsHistory,
  getExercisesByIdRecentSets,
  getFeaturesAccess,
  getHealth,
  getReady,
  getTrainingProfile,
  getWorkouts,
  getWorkoutsById,
  getWorkoutsContributionData,
  getWorkoutsFocusValues,
  getWorkoutsNewWorkoutContext,
  type Options,
  patchExercisesById,
  patchExercisesByIdHistorical1Rm,
  postAiChatTelemetry,
  postAiChatValidate,
  postAiConversations,
  postAiConversationsByIdLatestWorkoutDraftSave,
  postAiConversationsByIdMessagesRecover,
  postExercises,
  postWorkouts,
  putTrainingProfile,
  putWorkoutsById,
} from "../sdk.gen";
import type {
  DeleteAiConversationsByIdData,
  DeleteAiConversationsByIdError,
  DeleteExercisesByIdData,
  DeleteExercisesByIdError,
  DeleteWorkoutsByIdData,
  DeleteWorkoutsByIdError,
  GetAiConversationsByIdData,
  GetAiConversationsByIdError,
  GetAiConversationsByIdResponse,
  GetAiConversationsData,
  GetAiConversationsError,
  GetAiConversationsResponse,
  GetExercisesByIdData,
  GetExercisesByIdError,
  GetExercisesByIdMetricsHistoryData,
  GetExercisesByIdMetricsHistoryError,
  GetExercisesByIdMetricsHistoryResponse,
  GetExercisesByIdRecentSetsData,
  GetExercisesByIdRecentSetsError,
  GetExercisesByIdRecentSetsResponse,
  GetExercisesByIdResponse,
  GetExercisesData,
  GetExercisesError,
  GetExercisesResponse,
  GetFeaturesAccessData,
  GetFeaturesAccessError,
  GetFeaturesAccessResponse,
  GetHealthData,
  GetHealthResponse,
  GetReadyData,
  GetReadyError,
  GetReadyResponse,
  GetTrainingProfileData,
  GetTrainingProfileError,
  GetTrainingProfileResponse,
  GetWorkoutsByIdData,
  GetWorkoutsByIdError,
  GetWorkoutsByIdResponse,
  GetWorkoutsContributionDataData,
  GetWorkoutsContributionDataError,
  GetWorkoutsContributionDataResponse,
  GetWorkoutsData,
  GetWorkoutsError,
  GetWorkoutsFocusValuesData,
  GetWorkoutsFocusValuesError,
  GetWorkoutsFocusValuesResponse,
  GetWorkoutsNewWorkoutContextData,
  GetWorkoutsNewWorkoutContextError,
  GetWorkoutsNewWorkoutContextResponse,
  GetWorkoutsResponse,
  PatchExercisesByIdData,
  PatchExercisesByIdError,
  PatchExercisesByIdHistorical1RmData,
  PatchExercisesByIdHistorical1RmError,
  PostAiChatTelemetryData,
  PostAiChatTelemetryError,
  PostAiChatValidateData,
  PostAiChatValidateError,
  PostAiChatValidateResponse,
  PostAiConversationsByIdLatestWorkoutDraftSaveData,
  PostAiConversationsByIdLatestWorkoutDraftSaveError,
  PostAiConversationsByIdLatestWorkoutDraftSaveResponse,
  PostAiConversationsByIdMessagesRecoverData,
  PostAiConversationsByIdMessagesRecoverError,
  PostAiConversationsByIdMessagesRecoverResponse,
  PostAiConversationsData,
  PostAiConversationsError,
  PostAiConversationsResponse,
  PostExercisesData,
  PostExercisesError,
  PostExercisesResponse,
  PostWorkoutsData,
  PostWorkoutsError,
  PostWorkoutsResponse,
  PutTrainingProfileData,
  PutTrainingProfileError,
  PutTrainingProfileResponse,
  PutWorkoutsByIdData,
  PutWorkoutsByIdError,
} from "../types.gen";

/**
 * Record AI chat telemetry
 *
 * Records authenticated client-observed AI chat outcomes for observability and rollout gating.
 */
export const postAiChatTelemetryMutation = (
  options?: Partial<Options<PostAiChatTelemetryData>>,
): UseMutationOptions<
  unknown,
  PostAiChatTelemetryError,
  Options<PostAiChatTelemetryData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostAiChatTelemetryError,
    Options<PostAiChatTelemetryData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAiChatTelemetry({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Validate AI chat architecture
 *
 * Phase-0 validation endpoint for FitTrack AI chat architecture.
 */
export const postAiChatValidateMutation = (
  options?: Partial<Options<PostAiChatValidateData>>,
): UseMutationOptions<
  PostAiChatValidateResponse,
  PostAiChatValidateError,
  Options<PostAiChatValidateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAiChatValidateResponse,
    PostAiChatValidateError,
    Options<PostAiChatValidateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAiChatValidate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getAiConversationsQueryKey = (
  options?: Options<GetAiConversationsData>,
) => createQueryKey("getAiConversations", options, false, ["ai-chat"]);

/**
 * List AI chat conversations
 *
 * Returns lightweight AI chat conversation summaries for the authenticated user, newest activity first.
 */
export const getAiConversationsQueryOptions = (
  options?: Options<GetAiConversationsData>,
) =>
  queryOptions<
    GetAiConversationsResponse,
    GetAiConversationsError,
    GetAiConversationsResponse,
    ReturnType<typeof getAiConversationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiConversations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiConversationsQueryKey(options),
  });

/**
 * Create AI chat conversation
 *
 * Creates an empty persisted AI chat conversation for the authenticated user.
 */
export const postAiConversationsMutation = (
  options?: Partial<Options<PostAiConversationsData>>,
): UseMutationOptions<
  PostAiConversationsResponse,
  PostAiConversationsError,
  Options<PostAiConversationsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAiConversationsResponse,
    PostAiConversationsError,
    Options<PostAiConversationsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAiConversations({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete AI chat conversation
 *
 * Deletes an AI chat conversation and its associated messages, runs, and stream chunks. Only the owner can delete it, and active streams must finish first.
 */
export const deleteAiConversationsByIdMutation = (
  options?: Partial<Options<DeleteAiConversationsByIdData>>,
): UseMutationOptions<
  unknown,
  DeleteAiConversationsByIdError,
  Options<DeleteAiConversationsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteAiConversationsByIdError,
    Options<DeleteAiConversationsByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAiConversationsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiConversationsByIdQueryKey = (
  options: Options<GetAiConversationsByIdData>,
) => createQueryKey("getAiConversationsById", options, false, ["ai-chat"]);

/**
 * Get AI chat conversation
 *
 * Returns a persisted AI chat conversation with its messages.
 */
export const getAiConversationsByIdQueryOptions = (
  options: Options<GetAiConversationsByIdData>,
) =>
  queryOptions<
    GetAiConversationsByIdResponse,
    GetAiConversationsByIdError,
    GetAiConversationsByIdResponse,
    ReturnType<typeof getAiConversationsByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiConversationsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiConversationsByIdQueryKey(options),
  });

/**
 * Save the latest AI chat workout draft
 *
 * Creates a workout from the conversation's latest structured workout draft and marks that draft as saved.
 */
export const postAiConversationsByIdLatestWorkoutDraftSaveMutation = (
  options?: Partial<Options<PostAiConversationsByIdLatestWorkoutDraftSaveData>>,
): UseMutationOptions<
  PostAiConversationsByIdLatestWorkoutDraftSaveResponse,
  PostAiConversationsByIdLatestWorkoutDraftSaveError,
  Options<PostAiConversationsByIdLatestWorkoutDraftSaveData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAiConversationsByIdLatestWorkoutDraftSaveResponse,
    PostAiConversationsByIdLatestWorkoutDraftSaveError,
    Options<PostAiConversationsByIdLatestWorkoutDraftSaveData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAiConversationsByIdLatestWorkoutDraftSave({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Recover AI chat message stream
 *
 * Queues recovery for an active streaming AI chat run so persisted updates can continue after a disconnect.
 */
export const postAiConversationsByIdMessagesRecoverMutation = (
  options?: Partial<Options<PostAiConversationsByIdMessagesRecoverData>>,
): UseMutationOptions<
  PostAiConversationsByIdMessagesRecoverResponse,
  PostAiConversationsByIdMessagesRecoverError,
  Options<PostAiConversationsByIdMessagesRecoverData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAiConversationsByIdMessagesRecoverResponse,
    PostAiConversationsByIdMessagesRecoverError,
    Options<PostAiConversationsByIdMessagesRecoverData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAiConversationsByIdMessagesRecover({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesQueryKey = (options?: Options<GetExercisesData>) =>
  createQueryKey("getExercises", options, false, ["exercises"]);

/**
 * List exercises
 *
 * Get all exercises for the authenticated user
 */
export const getExercisesQueryOptions = (options?: Options<GetExercisesData>) =>
  queryOptions<
    GetExercisesResponse,
    GetExercisesError,
    GetExercisesResponse,
    ReturnType<typeof getExercisesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercises({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesQueryKey(options),
  });

/**
 * Get or create exercise
 *
 * Get an existing exercise by name or create it if it doesn't exist
 */
export const postExercisesMutation = (
  options?: Partial<Options<PostExercisesData>>,
): UseMutationOptions<
  PostExercisesResponse,
  PostExercisesError,
  Options<PostExercisesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostExercisesResponse,
    PostExercisesError,
    Options<PostExercisesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postExercises({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an exercise
 *
 * Delete a specific exercise and all its associated sets. Only the owner of the exercise can delete it.
 */
export const deleteExercisesByIdMutation = (
  options?: Partial<Options<DeleteExercisesByIdData>>,
): UseMutationOptions<
  unknown,
  DeleteExercisesByIdError,
  Options<DeleteExercisesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteExercisesByIdError,
    Options<DeleteExercisesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteExercisesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesByIdQueryKey = (
  options: Options<GetExercisesByIdData>,
) => createQueryKey("getExercisesById", options, false, ["exercises"]);

/**
 * Get exercise with sets
 *
 * Get a specific exercise (metadata) plus all its sets from workouts. Sets is empty when exercise exists but has no sets.
 */
export const getExercisesByIdQueryOptions = (
  options: Options<GetExercisesByIdData>,
) =>
  queryOptions<
    GetExercisesByIdResponse,
    GetExercisesByIdError,
    GetExercisesByIdResponse,
    ReturnType<typeof getExercisesByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercisesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesByIdQueryKey(options),
  });

/**
 * Update an exercise name
 *
 * Update the name of an exercise by ID (must belong to authenticated user)
 */
export const patchExercisesByIdMutation = (
  options?: Partial<Options<PatchExercisesByIdData>>,
): UseMutationOptions<
  unknown,
  PatchExercisesByIdError,
  Options<PatchExercisesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PatchExercisesByIdError,
    Options<PatchExercisesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchExercisesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update exercise historical 1RM
 *
 * Set a manual historical 1RM (clears source workout) or recompute from best working-set e1RM across history.
 */
export const patchExercisesByIdHistorical1RmMutation = (
  options?: Partial<Options<PatchExercisesByIdHistorical1RmData>>,
): UseMutationOptions<
  unknown,
  PatchExercisesByIdHistorical1RmError,
  Options<PatchExercisesByIdHistorical1RmData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PatchExercisesByIdHistorical1RmError,
    Options<PatchExercisesByIdHistorical1RmData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchExercisesByIdHistorical1Rm({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getExercisesByIdMetricsHistoryQueryKey = (
  options: Options<GetExercisesByIdMetricsHistoryData>,
) =>
  createQueryKey("getExercisesByIdMetricsHistory", options, false, [
    "exercises",
  ]);

/**
 * Get exercise metrics history
 *
 * Get time-series session metrics for an exercise. All ranges return per-workout session points filtered to the selected window.
 */
export const getExercisesByIdMetricsHistoryQueryOptions = (
  options: Options<GetExercisesByIdMetricsHistoryData>,
) =>
  queryOptions<
    GetExercisesByIdMetricsHistoryResponse,
    GetExercisesByIdMetricsHistoryError,
    GetExercisesByIdMetricsHistoryResponse,
    ReturnType<typeof getExercisesByIdMetricsHistoryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercisesByIdMetricsHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesByIdMetricsHistoryQueryKey(options),
  });

export const getExercisesByIdRecentSetsQueryKey = (
  options: Options<GetExercisesByIdRecentSetsData>,
) =>
  createQueryKey("getExercisesByIdRecentSets", options, false, ["exercises"]);

/**
 * Get recent sets for exercise
 *
 * Get the 3 most recent sets for a specific exercise. Returns empty array when exercise has no sets.
 */
export const getExercisesByIdRecentSetsQueryOptions = (
  options: Options<GetExercisesByIdRecentSetsData>,
) =>
  queryOptions<
    GetExercisesByIdRecentSetsResponse,
    GetExercisesByIdRecentSetsError,
    GetExercisesByIdRecentSetsResponse,
    ReturnType<typeof getExercisesByIdRecentSetsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getExercisesByIdRecentSets({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getExercisesByIdRecentSetsQueryKey(options),
  });

export const getFeaturesAccessQueryKey = (
  options?: Options<GetFeaturesAccessData>,
) => createQueryKey("getFeaturesAccess", options, false, ["feature-access"]);

/**
 * List active feature access grants
 *
 * Get all active feature access grants for the authenticated user
 */
export const getFeaturesAccessQueryOptions = (
  options?: Options<GetFeaturesAccessData>,
) =>
  queryOptions<
    GetFeaturesAccessResponse,
    GetFeaturesAccessError,
    GetFeaturesAccessResponse,
    ReturnType<typeof getFeaturesAccessQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFeaturesAccess({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFeaturesAccessQueryKey(options),
  });

export const getHealthQueryKey = (options?: Options<GetHealthData>) =>
  createQueryKey("getHealth", options, false, ["health"]);

/**
 * Health check
 *
 * Returns the health status of the API
 */
export const getHealthQueryOptions = (options?: Options<GetHealthData>) =>
  queryOptions<
    GetHealthResponse,
    DefaultError,
    GetHealthResponse,
    ReturnType<typeof getHealthQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthQueryKey(options),
  });

export const getReadyQueryKey = (options?: Options<GetReadyData>) =>
  createQueryKey("getReady", options, false, ["health"]);

/**
 * Readiness check
 *
 * Returns the readiness status of the API including database connectivity
 */
export const getReadyQueryOptions = (options?: Options<GetReadyData>) =>
  queryOptions<
    GetReadyResponse,
    GetReadyError,
    GetReadyResponse,
    ReturnType<typeof getReadyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getReady({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getReadyQueryKey(options),
  });

export const getTrainingProfileQueryKey = (
  options?: Options<GetTrainingProfileData>,
) => createQueryKey("getTrainingProfile", options, false, ["training-profile"]);

/**
 * Get training profile
 *
 * Returns the authenticated user's durable AI training profile. First-time users receive an empty profile shape.
 */
export const getTrainingProfileQueryOptions = (
  options?: Options<GetTrainingProfileData>,
) =>
  queryOptions<
    GetTrainingProfileResponse,
    GetTrainingProfileError,
    GetTrainingProfileResponse,
    ReturnType<typeof getTrainingProfileQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTrainingProfile({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTrainingProfileQueryKey(options),
  });

/**
 * Update training profile
 *
 * Replaces the authenticated user's durable AI training profile with the full submitted document.
 */
export const putTrainingProfileMutation = (
  options?: Partial<Options<PutTrainingProfileData>>,
): UseMutationOptions<
  PutTrainingProfileResponse,
  PutTrainingProfileError,
  Options<PutTrainingProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    PutTrainingProfileResponse,
    PutTrainingProfileError,
    Options<PutTrainingProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putTrainingProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutsQueryKey = (options?: Options<GetWorkoutsData>) =>
  createQueryKey("getWorkouts", options, false, ["workouts"]);

/**
 * List workouts
 *
 * Get all workouts for the authenticated user
 */
export const getWorkoutsQueryOptions = (options?: Options<GetWorkoutsData>) =>
  queryOptions<
    GetWorkoutsResponse,
    GetWorkoutsError,
    GetWorkoutsResponse,
    ReturnType<typeof getWorkoutsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkouts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsQueryKey(options),
  });

/**
 * Create a new workout
 *
 * Create a new workout with exercises and sets
 */
export const postWorkoutsMutation = (
  options?: Partial<Options<PostWorkoutsData>>,
): UseMutationOptions<
  PostWorkoutsResponse,
  PostWorkoutsError,
  Options<PostWorkoutsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostWorkoutsResponse,
    PostWorkoutsError,
    Options<PostWorkoutsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postWorkouts({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutsContributionDataQueryKey = (
  options?: Options<GetWorkoutsContributionDataData>,
) =>
  createQueryKey("getWorkoutsContributionData", options, false, ["workouts"]);

/**
 * Get contribution graph data
 *
 * Get workout contribution data for the past 52 weeks, including daily working set counts and intensity levels (0-4) for visualization in a contribution graph
 */
export const getWorkoutsContributionDataQueryOptions = (
  options?: Options<GetWorkoutsContributionDataData>,
) =>
  queryOptions<
    GetWorkoutsContributionDataResponse,
    GetWorkoutsContributionDataError,
    GetWorkoutsContributionDataResponse,
    ReturnType<typeof getWorkoutsContributionDataQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutsContributionData({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsContributionDataQueryKey(options),
  });

export const getWorkoutsFocusValuesQueryKey = (
  options?: Options<GetWorkoutsFocusValuesData>,
) => createQueryKey("getWorkoutsFocusValues", options, false, ["workouts"]);

/**
 * List workout focus values
 *
 * Get all distinct workout focus values for the authenticated user. Returns 200 OK with an empty array if no workout focus values exist.
 */
export const getWorkoutsFocusValuesQueryOptions = (
  options?: Options<GetWorkoutsFocusValuesData>,
) =>
  queryOptions<
    GetWorkoutsFocusValuesResponse,
    GetWorkoutsFocusValuesError,
    GetWorkoutsFocusValuesResponse,
    ReturnType<typeof getWorkoutsFocusValuesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutsFocusValues({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsFocusValuesQueryKey(options),
  });

export const getWorkoutsNewWorkoutContextQueryKey = (
  options?: Options<GetWorkoutsNewWorkoutContextData>,
) =>
  createQueryKey("getWorkoutsNewWorkoutContext", options, false, ["workouts"]);

/**
 * Get new workout context
 *
 * Get the newest reusable workout per focus area plus the latest workout note for the authenticated user.
 */
export const getWorkoutsNewWorkoutContextQueryOptions = (
  options?: Options<GetWorkoutsNewWorkoutContextData>,
) =>
  queryOptions<
    GetWorkoutsNewWorkoutContextResponse,
    GetWorkoutsNewWorkoutContextError,
    GetWorkoutsNewWorkoutContextResponse,
    ReturnType<typeof getWorkoutsNewWorkoutContextQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutsNewWorkoutContext({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsNewWorkoutContextQueryKey(options),
  });

/**
 * Delete a workout
 *
 * Delete a specific workout and all its associated sets. Only the owner of the workout can delete it.
 */
export const deleteWorkoutsByIdMutation = (
  options?: Partial<Options<DeleteWorkoutsByIdData>>,
): UseMutationOptions<
  unknown,
  DeleteWorkoutsByIdError,
  Options<DeleteWorkoutsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteWorkoutsByIdError,
    Options<DeleteWorkoutsByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteWorkoutsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkoutsByIdQueryKey = (
  options: Options<GetWorkoutsByIdData>,
) => createQueryKey("getWorkoutsById", options, false, ["workouts"]);

/**
 * Get workout with sets
 *
 * Get a specific workout with all its sets and exercises
 */
export const getWorkoutsByIdQueryOptions = (
  options: Options<GetWorkoutsByIdData>,
) =>
  queryOptions<
    GetWorkoutsByIdResponse,
    GetWorkoutsByIdError,
    GetWorkoutsByIdResponse,
    ReturnType<typeof getWorkoutsByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkoutsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkoutsByIdQueryKey(options),
  });

/**
 * Update an existing workout (full replacement)
 *
 * Updates a workout using full replacement semantics. The client must provide the complete workout data including date and at least one exercise with sets. This endpoint replaces the entire workout, deleting existing exercises/sets and creating new ones. For partial updates, PATCH will be implemented in a future version. Returns 204 No Content on success.
 */
export const putWorkoutsByIdMutation = (
  options?: Partial<Options<PutWorkoutsByIdData>>,
): UseMutationOptions<
  unknown,
  PutWorkoutsByIdError,
  Options<PutWorkoutsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PutWorkoutsByIdError,
    Options<PutWorkoutsByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putWorkoutsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
