// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ai_chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAIChatRunGeneration = `-- name: ClaimAIChatRunGeneration :one
UPDATE ai_chat_run
SET generation_status = 'generating',
    generation_owner = $3,
    generation_lease_expires_at = $4,
    generation_heartbeat_at = $5,
    generation_attempt = generation_attempt + 1,
    error_message = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND generation_attempt < $6
  AND (
    generation_status = 'queued'
    OR (
      generation_status = 'generating'
      AND generation_lease_expires_at IS NOT NULL
      AND generation_lease_expires_at < $5
    )
  )
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type ClaimAIChatRunGenerationParams struct {
	ID                       int32              `json:"id"`
	UserID                   string             `json:"user_id"`
	GenerationOwner          pgtype.Text        `json:"generation_owner"`
	GenerationLeaseExpiresAt pgtype.Timestamptz `json:"generation_lease_expires_at"`
	GenerationHeartbeatAt    pgtype.Timestamptz `json:"generation_heartbeat_at"`
	GenerationAttempt        int32              `json:"generation_attempt"`
}

func (q *Queries) ClaimAIChatRunGeneration(ctx context.Context, arg ClaimAIChatRunGenerationParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, claimAIChatRunGeneration,
		arg.ID,
		arg.UserID,
		arg.GenerationOwner,
		arg.GenerationLeaseExpiresAt,
		arg.GenerationHeartbeatAt,
		arg.GenerationAttempt,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const clearUserTrainingProfileConversationSource = `-- name: ClearUserTrainingProfileConversationSource :exec
UPDATE user_training_profile
SET
    source_conversation_id = NULL,
    source_message_id = NULL
WHERE user_id = $1
  AND source_conversation_id = $2
`

type ClearUserTrainingProfileConversationSourceParams struct {
	UserID               string      `json:"user_id"`
	SourceConversationID pgtype.Int4 `json:"source_conversation_id"`
}

func (q *Queries) ClearUserTrainingProfileConversationSource(ctx context.Context, arg ClearUserTrainingProfileConversationSourceParams) error {
	_, err := q.db.Exec(ctx, clearUserTrainingProfileConversationSource, arg.UserID, arg.SourceConversationID)
	return err
}

const clearUserTrainingProfileSourcesByUser = `-- name: ClearUserTrainingProfileSourcesByUser :exec
UPDATE user_training_profile
SET
    source_conversation_id = NULL,
    source_message_id = NULL
WHERE user_id = $1
  AND (source_conversation_id IS NOT NULL OR source_message_id IS NOT NULL)
`

func (q *Queries) ClearUserTrainingProfileSourcesByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearUserTrainingProfileSourcesByUser, userID)
	return err
}

const createAIChatConversation = `-- name: CreateAIChatConversation :one
INSERT INTO ai_chat_conversation (
    user_id,
    title
)
VALUES ($1, $2)
RETURNING
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
`

type CreateAIChatConversationParams struct {
	UserID string      `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) CreateAIChatConversation(ctx context.Context, arg CreateAIChatConversationParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, createAIChatConversation, arg.UserID, arg.Title)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const createAIChatMessage = `-- name: CreateAIChatMessage :one
INSERT INTO ai_chat_message (
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type CreateAIChatMessageParams struct {
	ConversationID int32              `json:"conversation_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateAIChatMessage(ctx context.Context, arg CreateAIChatMessageParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, createAIChatMessage,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.Status,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAIChatRun = `-- name: CreateAIChatRun :one
INSERT INTO ai_chat_run (
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type CreateAIChatRunParams struct {
	ConversationID     int32              `json:"conversation_id"`
	UserID             string             `json:"user_id"`
	UserMessageID      int32              `json:"user_message_id"`
	AssistantMessageID int32              `json:"assistant_message_id"`
	Model              string             `json:"model"`
	Status             string             `json:"status"`
	RequestID          pgtype.Text        `json:"request_id"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateAIChatRun(ctx context.Context, arg CreateAIChatRunParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, createAIChatRun,
		arg.ConversationID,
		arg.UserID,
		arg.UserMessageID,
		arg.AssistantMessageID,
		arg.Model,
		arg.Status,
		arg.RequestID,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAIChatStreamChunk = `-- name: CreateAIChatStreamChunk :one
INSERT INTO ai_chat_stream_chunk (
    run_id,
    user_id,
    sequence,
    delta_text
)
SELECT
    $1,
    $2::varchar,
    $3,
    $4
WHERE (
    NULLIF($5::text, '') IS NULL
    OR EXISTS (
        SELECT 1
        FROM ai_chat_run
        WHERE id = $1
          AND user_id = $2::varchar
          AND status = 'streaming'
          AND generation_status = 'generating'
          AND generation_owner = $5::varchar
    )
)
RETURNING
    run_id,
    user_id,
    sequence,
    delta_text,
    created_at
`

type CreateAIChatStreamChunkParams struct {
	RunID           int32  `json:"run_id"`
	UserID          string `json:"user_id"`
	Sequence        int32  `json:"sequence"`
	DeltaText       string `json:"delta_text"`
	GenerationOwner string `json:"generation_owner"`
}

func (q *Queries) CreateAIChatStreamChunk(ctx context.Context, arg CreateAIChatStreamChunkParams) (AiChatStreamChunk, error) {
	row := q.db.QueryRow(ctx, createAIChatStreamChunk,
		arg.RunID,
		arg.UserID,
		arg.Sequence,
		arg.DeltaText,
		arg.GenerationOwner,
	)
	var i AiChatStreamChunk
	err := row.Scan(
		&i.RunID,
		&i.UserID,
		&i.Sequence,
		&i.DeltaText,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAIChatConversation = `-- name: DeleteAIChatConversation :execrows
DELETE FROM ai_chat_conversation
WHERE id = $1 AND user_id = $2
`

type DeleteAIChatConversationParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAIChatConversation(ctx context.Context, arg DeleteAIChatConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAIChatConversation, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAIChatConversationsByUser = `-- name: DeleteAIChatConversationsByUser :execrows
DELETE FROM ai_chat_conversation
WHERE user_id = $1
`

func (q *Queries) DeleteAIChatConversationsByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAIChatConversationsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAIChatConversation = `-- name: GetAIChatConversation :one
SELECT
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
FROM ai_chat_conversation
WHERE id = $1 AND user_id = $2
`

type GetAIChatConversationParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatConversation(ctx context.Context, arg GetAIChatConversationParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, getAIChatConversation, arg.ID, arg.UserID)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getAIChatConversationForUpdate = `-- name: GetAIChatConversationForUpdate :one
SELECT
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
FROM ai_chat_conversation
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetAIChatConversationForUpdateParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatConversationForUpdate(ctx context.Context, arg GetAIChatConversationForUpdateParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, getAIChatConversationForUpdate, arg.ID, arg.UserID)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getAIChatMessage = `-- name: GetAIChatMessage :one
SELECT
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
FROM ai_chat_message
WHERE id = $1 AND user_id = $2
`

type GetAIChatMessageParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatMessage(ctx context.Context, arg GetAIChatMessageParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, getAIChatMessage, arg.ID, arg.UserID)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAIChatRun = `-- name: GetAIChatRun :one
SELECT
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
FROM ai_chat_run
WHERE id = $1
  AND user_id = $2
`

type GetAIChatRunParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatRun(ctx context.Context, arg GetAIChatRunParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, getAIChatRun, arg.ID, arg.UserID)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAIChatRunForUpdate = `-- name: GetAIChatRunForUpdate :one
SELECT id, conversation_id, user_id, user_message_id, assistant_message_id,
       model, status, request_id, error_message, workout_draft,
       generation_status, generation_owner, generation_lease_expires_at,
       generation_heartbeat_at, generation_attempt, interrupted_at,
       interruption_reason, created_at, updated_at, started_at, completed_at
FROM ai_chat_run
WHERE id = $1 AND conversation_id = $2 AND user_id = $3
FOR UPDATE
`

type GetAIChatRunForUpdateParams struct {
	ID             int32  `json:"id"`
	ConversationID int32  `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetAIChatRunForUpdate(ctx context.Context, arg GetAIChatRunForUpdateParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, getAIChatRunForUpdate, arg.ID, arg.ConversationID, arg.UserID)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getActiveAIChatRunForConversation = `-- name: GetActiveAIChatRunForConversation :one
SELECT
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
FROM ai_chat_run
WHERE conversation_id = $1
  AND user_id = $2
  AND status = 'streaming'
ORDER BY id DESC
LIMIT 1
`

type GetActiveAIChatRunForConversationParams struct {
	ConversationID int32  `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetActiveAIChatRunForConversation(ctx context.Context, arg GetActiveAIChatRunForConversationParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, getActiveAIChatRunForConversation, arg.ConversationID, arg.UserID)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getChatWorkoutSnapshotStats = `-- name: GetChatWorkoutSnapshotStats :one
SELECT
    MAX(date)::timestamptz AS last_workout_date,
    COUNT(*) FILTER (WHERE date >= now() - interval '30 days') AS workouts_last_30d
FROM workout
WHERE user_id = $1
`

type GetChatWorkoutSnapshotStatsRow struct {
	LastWorkoutDate pgtype.Timestamptz `json:"last_workout_date"`
	WorkoutsLast30d int64              `json:"workouts_last_30d"`
}

func (q *Queries) GetChatWorkoutSnapshotStats(ctx context.Context, userID string) (GetChatWorkoutSnapshotStatsRow, error) {
	row := q.db.QueryRow(ctx, getChatWorkoutSnapshotStats, userID)
	var i GetChatWorkoutSnapshotStatsRow
	err := row.Scan(&i.LastWorkoutDate, &i.WorkoutsLast30d)
	return i, err
}

const getLastSessionSetsForExerciseChat = `-- name: GetLastSessionSetsForExerciseChat :many
WITH latest_workout AS (
    SELECT s.workout_id
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id AND w.user_id = s.user_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
    ORDER BY w.date DESC, w.id DESC
    LIMIT 1
)
SELECT
    s.id AS set_id,
    w.id AS workout_id,
    w.date AS workout_date,
    w.workout_focus AS workout_focus,
    s.weight,
    s.reps,
    s.exercise_order,
    s.set_order,
    s.created_at
FROM "set" s
JOIN latest_workout lw ON lw.workout_id = s.workout_id
JOIN workout w ON w.id = s.workout_id AND w.user_id = s.user_id
WHERE s.exercise_id = $1
  AND s.user_id = $2
  AND s.set_type = 'working'
ORDER BY s.set_order ASC
`

type GetLastSessionSetsForExerciseChatParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetLastSessionSetsForExerciseChatRow struct {
	SetID         int32              `json:"set_id"`
	WorkoutID     int32              `json:"workout_id"`
	WorkoutDate   pgtype.Timestamptz `json:"workout_date"`
	WorkoutFocus  pgtype.Text        `json:"workout_focus"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLastSessionSetsForExerciseChat(ctx context.Context, arg GetLastSessionSetsForExerciseChatParams) ([]GetLastSessionSetsForExerciseChatRow, error) {
	rows, err := q.db.Query(ctx, getLastSessionSetsForExerciseChat, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLastSessionSetsForExerciseChatRow
	for rows.Next() {
		var i GetLastSessionSetsForExerciseChatRow
		if err := rows.Scan(
			&i.SetID,
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.WorkoutFocus,
			&i.Weight,
			&i.Reps,
			&i.ExerciseOrder,
			&i.SetOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAIChatStreamChunkSequence = `-- name: GetLatestAIChatStreamChunkSequence :one
SELECT COALESCE(MAX(sequence), 0)::INTEGER
FROM ai_chat_stream_chunk
WHERE run_id = $1
  AND user_id = $2
`

type GetLatestAIChatStreamChunkSequenceParams struct {
	RunID  int32  `json:"run_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetLatestAIChatStreamChunkSequence(ctx context.Context, arg GetLatestAIChatStreamChunkSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestAIChatStreamChunkSequence, arg.RunID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const heartbeatAIChatRunGeneration = `-- name: HeartbeatAIChatRunGeneration :execrows
UPDATE ai_chat_run
SET generation_lease_expires_at = $3,
    generation_heartbeat_at = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND generation_status = 'generating'
  AND generation_owner = $5
`

type HeartbeatAIChatRunGenerationParams struct {
	ID                       int32              `json:"id"`
	UserID                   string             `json:"user_id"`
	GenerationLeaseExpiresAt pgtype.Timestamptz `json:"generation_lease_expires_at"`
	GenerationHeartbeatAt    pgtype.Timestamptz `json:"generation_heartbeat_at"`
	GenerationOwner          pgtype.Text        `json:"generation_owner"`
}

func (q *Queries) HeartbeatAIChatRunGeneration(ctx context.Context, arg HeartbeatAIChatRunGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatAIChatRunGeneration,
		arg.ID,
		arg.UserID,
		arg.GenerationLeaseExpiresAt,
		arg.GenerationHeartbeatAt,
		arg.GenerationOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAIChatConversationsByUser = `-- name: ListAIChatConversationsByUser :many
SELECT
    id,
    user_id,
    title,
    created_at,
    updated_at,
    last_message_at
FROM ai_chat_conversation
WHERE user_id = $1
ORDER BY COALESCE(last_message_at, updated_at) DESC, updated_at DESC, id DESC
LIMIT $2
`

type ListAIChatConversationsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type ListAIChatConversationsByUserRow struct {
	ID            int32              `json:"id"`
	UserID        string             `json:"user_id"`
	Title         pgtype.Text        `json:"title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) ListAIChatConversationsByUser(ctx context.Context, arg ListAIChatConversationsByUserParams) ([]ListAIChatConversationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAIChatConversationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIChatConversationsByUserRow
	for rows.Next() {
		var i ListAIChatConversationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIChatMessagesByConversation = `-- name: ListAIChatMessagesByConversation :many
SELECT
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
FROM ai_chat_message
WHERE conversation_id = $1 AND user_id = $2
ORDER BY id ASC
`

type ListAIChatMessagesByConversationParams struct {
	ConversationID int32  `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) ListAIChatMessagesByConversation(ctx context.Context, arg ListAIChatMessagesByConversationParams) ([]AiChatMessage, error) {
	rows, err := q.db.Query(ctx, listAIChatMessagesByConversation, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiChatMessage
	for rows.Next() {
		var i AiChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIChatStreamChunksAfter = `-- name: ListAIChatStreamChunksAfter :many
SELECT
    run_id,
    user_id,
    sequence,
    delta_text,
    created_at
FROM ai_chat_stream_chunk
WHERE run_id = $1
  AND user_id = $2
  AND sequence > $3
ORDER BY sequence ASC
`

type ListAIChatStreamChunksAfterParams struct {
	RunID    int32  `json:"run_id"`
	UserID   string `json:"user_id"`
	Sequence int32  `json:"sequence"`
}

func (q *Queries) ListAIChatStreamChunksAfter(ctx context.Context, arg ListAIChatStreamChunksAfterParams) ([]AiChatStreamChunk, error) {
	rows, err := q.db.Query(ctx, listAIChatStreamChunksAfter, arg.RunID, arg.UserID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiChatStreamChunk
	for rows.Next() {
		var i AiChatStreamChunk
		if err := rows.Scan(
			&i.RunID,
			&i.UserID,
			&i.Sequence,
			&i.DeltaText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseNameMatches = `-- name: ListExerciseNameMatches :many
SELECT id, name
FROM exercise
WHERE user_id = $1
  AND name ILIKE '%' || $2::text || '%'
ORDER BY name
LIMIT 8
`

type ListExerciseNameMatchesParams struct {
	UserID    string `json:"user_id"`
	NameQuery string `json:"name_query"`
}

type ListExerciseNameMatchesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListExerciseNameMatches(ctx context.Context, arg ListExerciseNameMatchesParams) ([]ListExerciseNameMatchesRow, error) {
	rows, err := q.db.Query(ctx, listExerciseNameMatches, arg.UserID, arg.NameQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExerciseNameMatchesRow
	for rows.Next() {
		var i ListExerciseNameMatchesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopExercisesByFrequency = `-- name: ListTopExercisesByFrequency :many
SELECT
    e.name,
    COUNT(DISTINCT s.workout_id)::integer AS workout_count
FROM "set" s
JOIN exercise e ON e.id = s.exercise_id AND e.user_id = s.user_id
JOIN workout w ON w.id = s.workout_id AND w.user_id = s.user_id
WHERE s.user_id = $1
  AND w.date >= now() - interval '90 days'
GROUP BY e.name
ORDER BY workout_count DESC, e.name
LIMIT 5
`

type ListTopExercisesByFrequencyRow struct {
	Name         string `json:"name"`
	WorkoutCount int32  `json:"workout_count"`
}

func (q *Queries) ListTopExercisesByFrequency(ctx context.Context, userID string) ([]ListTopExercisesByFrequencyRow, error) {
	rows, err := q.db.Query(ctx, listTopExercisesByFrequency, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopExercisesByFrequencyRow
	for rows.Next() {
		var i ListTopExercisesByFrequencyRow
		if err := rows.Scan(&i.Name, &i.WorkoutCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsWithSetsForChat = `-- name: ListWorkoutsWithSetsForChat :many
WITH matching_workouts AS (
    SELECT w.id
    FROM workout w
    WHERE w.user_id = $2
      AND ($3::timestamptz IS NULL OR w.date >= $3::timestamptz)
      AND ($4::timestamptz IS NULL OR w.date <= $4::timestamptz)
      AND (
          NULLIF($1::text, '') IS NULL
          OR EXISTS (
              SELECT 1
              FROM "set" filter_set
              JOIN exercise filter_exercise ON filter_exercise.id = filter_set.exercise_id
              WHERE filter_set.workout_id = w.id
                AND filter_set.user_id = w.user_id
                AND filter_exercise.user_id = w.user_id
                AND filter_exercise.name = $1::text
          )
      )
      AND (
          NULLIF($5::text, '') IS NULL
          OR w.workout_focus ILIKE '%' || $5::text || '%'
      )
    ORDER BY w.date DESC, w.id DESC
    LIMIT $6
)
SELECT
    w.id AS workout_id,
    w.date,
    w.notes,
    w.workout_focus,
    e.name AS exercise_name,
    s.exercise_order,
    s.set_order,
    s.weight,
    s.reps,
    s.set_type
FROM matching_workouts mw
JOIN workout w ON w.id = mw.id
LEFT JOIN "set" s ON s.workout_id = w.id
    AND s.user_id = w.user_id
    AND (
        NULLIF($1::text, '') IS NULL
        OR EXISTS (
            SELECT 1
            FROM exercise selected_exercise
            WHERE selected_exercise.id = s.exercise_id
              AND selected_exercise.user_id = s.user_id
              AND selected_exercise.name = $1::text
        )
    )
LEFT JOIN exercise e ON e.id = s.exercise_id AND e.user_id = w.user_id
ORDER BY w.date DESC, w.id DESC, s.exercise_order, s.set_order, s.id
`

type ListWorkoutsWithSetsForChatParams struct {
	ExerciseName pgtype.Text        `json:"exercise_name"`
	UserID       string             `json:"user_id"`
	StartDate    pgtype.Timestamptz `json:"start_date"`
	EndDate      pgtype.Timestamptz `json:"end_date"`
	WorkoutFocus pgtype.Text        `json:"workout_focus"`
	RowLimit     int32              `json:"row_limit"`
}

type ListWorkoutsWithSetsForChatRow struct {
	WorkoutID     int32              `json:"workout_id"`
	Date          pgtype.Timestamptz `json:"date"`
	Notes         pgtype.Text        `json:"notes"`
	WorkoutFocus  pgtype.Text        `json:"workout_focus"`
	ExerciseName  pgtype.Text        `json:"exercise_name"`
	ExerciseOrder pgtype.Int4        `json:"exercise_order"`
	SetOrder      pgtype.Int4        `json:"set_order"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          pgtype.Int4        `json:"reps"`
	SetType       pgtype.Text        `json:"set_type"`
}

func (q *Queries) ListWorkoutsWithSetsForChat(ctx context.Context, arg ListWorkoutsWithSetsForChatParams) ([]ListWorkoutsWithSetsForChatRow, error) {
	rows, err := q.db.Query(ctx, listWorkoutsWithSetsForChat,
		arg.ExerciseName,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.WorkoutFocus,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutsWithSetsForChatRow
	for rows.Next() {
		var i ListWorkoutsWithSetsForChatRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.Date,
			&i.Notes,
			&i.WorkoutFocus,
			&i.ExerciseName,
			&i.ExerciseOrder,
			&i.SetOrder,
			&i.Weight,
			&i.Reps,
			&i.SetType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAIChatConversationsByUser = `-- name: LockAIChatConversationsByUser :many
SELECT id
FROM ai_chat_conversation
WHERE user_id = $1
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockAIChatConversationsByUser(ctx context.Context, userID string) ([]int32, error) {
	rows, err := q.db.Query(ctx, lockAIChatConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAIChatRunsByUser = `-- name: LockAIChatRunsByUser :many
SELECT id, conversation_id, assistant_message_id, status
FROM ai_chat_run
WHERE user_id = $1
ORDER BY conversation_id, id
FOR UPDATE
`

type LockAIChatRunsByUserRow struct {
	ID                 int32  `json:"id"`
	ConversationID     int32  `json:"conversation_id"`
	AssistantMessageID int32  `json:"assistant_message_id"`
	Status             string `json:"status"`
}

func (q *Queries) LockAIChatRunsByUser(ctx context.Context, userID string) ([]LockAIChatRunsByUserRow, error) {
	rows, err := q.db.Query(ctx, lockAIChatRunsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAIChatRunsByUserRow
	for rows.Next() {
		var i LockAIChatRunsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.AssistantMessageID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAIChatUserMutation = `-- name: LockAIChatUserMutation :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 250))
`

// Serializes conversation creation, stream start, and deletion for one owner.
func (q *Queries) LockAIChatUserMutation(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, lockAIChatUserMutation, userID)
	return err
}

const markAIChatConversationLatestWorkoutDraftSaved = `-- name: MarkAIChatConversationLatestWorkoutDraftSaved :one
UPDATE ai_chat_conversation
SET latest_workout_draft_saved_workout_id = $4,
    latest_workout_draft_saved_at = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND latest_workout_draft IS NOT NULL
  AND (
    latest_workout_draft_source_run_id = $3
    OR ($3::integer IS NULL AND latest_workout_draft_source_run_id IS NULL)
  )
RETURNING
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
`

type MarkAIChatConversationLatestWorkoutDraftSavedParams struct {
	ID                               int32              `json:"id"`
	UserID                           string             `json:"user_id"`
	LatestWorkoutDraftSourceRunID    pgtype.Int4        `json:"latest_workout_draft_source_run_id"`
	LatestWorkoutDraftSavedWorkoutID pgtype.Int4        `json:"latest_workout_draft_saved_workout_id"`
	LatestWorkoutDraftSavedAt        pgtype.Timestamptz `json:"latest_workout_draft_saved_at"`
}

func (q *Queries) MarkAIChatConversationLatestWorkoutDraftSaved(ctx context.Context, arg MarkAIChatConversationLatestWorkoutDraftSavedParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, markAIChatConversationLatestWorkoutDraftSaved,
		arg.ID,
		arg.UserID,
		arg.LatestWorkoutDraftSourceRunID,
		arg.LatestWorkoutDraftSavedWorkoutID,
		arg.LatestWorkoutDraftSavedAt,
	)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const ownsAIChatRunGeneration = `-- name: OwnsAIChatRunGeneration :one
SELECT EXISTS (
    SELECT 1
    FROM ai_chat_run
    WHERE id = $1
      AND user_id = $2
      AND status = 'streaming'
      AND generation_status = 'generating'
      AND generation_owner = $3
)
`

type OwnsAIChatRunGenerationParams struct {
	ID              int32       `json:"id"`
	UserID          string      `json:"user_id"`
	GenerationOwner pgtype.Text `json:"generation_owner"`
}

func (q *Queries) OwnsAIChatRunGeneration(ctx context.Context, arg OwnsAIChatRunGenerationParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownsAIChatRunGeneration, arg.ID, arg.UserID, arg.GenerationOwner)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setAIChatConversationLatestWorkoutDraft = `-- name: SetAIChatConversationLatestWorkoutDraft :exec
UPDATE ai_chat_conversation
SET latest_workout_draft = NULLIF($3::text, '')::jsonb,
    latest_workout_draft_source_run_id = $4,
    latest_workout_draft_saved_workout_id = NULL,
    latest_workout_draft_saved_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type SetAIChatConversationLatestWorkoutDraftParams struct {
	ID                            int32       `json:"id"`
	UserID                        string      `json:"user_id"`
	Column3                       string      `json:"column_3"`
	LatestWorkoutDraftSourceRunID pgtype.Int4 `json:"latest_workout_draft_source_run_id"`
}

func (q *Queries) SetAIChatConversationLatestWorkoutDraft(ctx context.Context, arg SetAIChatConversationLatestWorkoutDraftParams) error {
	_, err := q.db.Exec(ctx, setAIChatConversationLatestWorkoutDraft,
		arg.ID,
		arg.UserID,
		arg.Column3,
		arg.LatestWorkoutDraftSourceRunID,
	)
	return err
}

const setAIChatConversationTitleIfEmpty = `-- name: SetAIChatConversationTitleIfEmpty :execrows
UPDATE ai_chat_conversation
SET title = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND title IS NULL
  AND $3::text IS NOT NULL
  AND btrim($3::text) <> ''
`

type SetAIChatConversationTitleIfEmptyParams struct {
	ID     int32       `json:"id"`
	UserID string      `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) SetAIChatConversationTitleIfEmpty(ctx context.Context, arg SetAIChatConversationTitleIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAIChatConversationTitleIfEmpty, arg.ID, arg.UserID, arg.Title)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAIChatConversation = `-- name: TouchAIChatConversation :exec
UPDATE ai_chat_conversation
SET updated_at = CURRENT_TIMESTAMP,
    last_message_at = $3
WHERE id = $1 AND user_id = $2
`

type TouchAIChatConversationParams struct {
	ID            int32              `json:"id"`
	UserID        string             `json:"user_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) TouchAIChatConversation(ctx context.Context, arg TouchAIChatConversationParams) error {
	_, err := q.db.Exec(ctx, touchAIChatConversation, arg.ID, arg.UserID, arg.LastMessageAt)
	return err
}

const touchAIChatRun = `-- name: TouchAIChatRun :exec
UPDATE ai_chat_run
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
`

type TouchAIChatRunParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) TouchAIChatRun(ctx context.Context, arg TouchAIChatRunParams) error {
	_, err := q.db.Exec(ctx, touchAIChatRun, arg.ID, arg.UserID)
	return err
}

const updateAIChatMessageCompleted = `-- name: UpdateAIChatMessageCompleted :one
UPDATE ai_chat_message
SET content = $3,
    status = 'completed',
    error_message = NULL,
    completed_at = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type UpdateAIChatMessageCompletedParams struct {
	ID          int32              `json:"id"`
	UserID      string             `json:"user_id"`
	Content     string             `json:"content"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAIChatMessageCompleted(ctx context.Context, arg UpdateAIChatMessageCompletedParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, updateAIChatMessageCompleted,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.CompletedAt,
	)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatMessageFailed = `-- name: UpdateAIChatMessageFailed :one
UPDATE ai_chat_message
SET content = $3,
    status = 'failed',
    error_message = $4,
    completed_at = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type UpdateAIChatMessageFailedParams struct {
	ID           int32              `json:"id"`
	UserID       string             `json:"user_id"`
	Content      string             `json:"content"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAIChatMessageFailed(ctx context.Context, arg UpdateAIChatMessageFailedParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, updateAIChatMessageFailed,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatMessageStopped = `-- name: UpdateAIChatMessageStopped :one
UPDATE ai_chat_message
SET status = 'stopped', error_message = NULL, completed_at = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND status = 'streaming'
RETURNING id, conversation_id, user_id, role, content, status, error_message,
          created_at, updated_at, completed_at
`

type UpdateAIChatMessageStoppedParams struct {
	ID          int32              `json:"id"`
	UserID      string             `json:"user_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAIChatMessageStopped(ctx context.Context, arg UpdateAIChatMessageStoppedParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, updateAIChatMessageStopped, arg.ID, arg.UserID, arg.CompletedAt)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatMessageStreaming = `-- name: UpdateAIChatMessageStreaming :one
UPDATE ai_chat_message
SET content = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type UpdateAIChatMessageStreamingParams struct {
	ID      int32  `json:"id"`
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateAIChatMessageStreaming(ctx context.Context, arg UpdateAIChatMessageStreamingParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, updateAIChatMessageStreaming, arg.ID, arg.UserID, arg.Content)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatRunCompleted = `-- name: UpdateAIChatRunCompleted :one
UPDATE ai_chat_run
SET status = 'completed',
    error_message = NULL,
    completed_at = $3,
    workout_draft = NULLIF($4::text, '')::jsonb,
    generation_status = 'completed',
    generation_owner = NULL,
    generation_lease_expires_at = NULL,
    generation_heartbeat_at = NULL,
    interrupted_at = NULL,
    interruption_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND (NULLIF($5::text, '') IS NULL OR generation_owner = $5)
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type UpdateAIChatRunCompletedParams struct {
	ID          int32              `json:"id"`
	UserID      string             `json:"user_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
}

func (q *Queries) UpdateAIChatRunCompleted(ctx context.Context, arg UpdateAIChatRunCompletedParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, updateAIChatRunCompleted,
		arg.ID,
		arg.UserID,
		arg.CompletedAt,
		arg.Column4,
		arg.Column5,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatRunFailed = `-- name: UpdateAIChatRunFailed :one
UPDATE ai_chat_run
SET status = 'failed',
    error_message = $3,
    completed_at = $4,
    workout_draft = NULL,
    generation_status = 'failed',
    generation_owner = NULL,
    generation_lease_expires_at = NULL,
    generation_heartbeat_at = NULL,
    interrupted_at = NULL,
    interruption_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND (NULLIF($5::text, '') IS NULL OR generation_owner = $5)
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type UpdateAIChatRunFailedParams struct {
	ID           int32              `json:"id"`
	UserID       string             `json:"user_id"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Column5      string             `json:"column_5"`
}

func (q *Queries) UpdateAIChatRunFailed(ctx context.Context, arg UpdateAIChatRunFailedParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, updateAIChatRunFailed,
		arg.ID,
		arg.UserID,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.Column5,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatRunInterrupted = `-- name: UpdateAIChatRunInterrupted :one
UPDATE ai_chat_run
SET status = 'failed',
    error_message = $3,
    completed_at = $4,
    workout_draft = NULL,
    generation_status = 'interrupted',
    generation_owner = NULL,
    generation_lease_expires_at = NULL,
    generation_heartbeat_at = NULL,
    interrupted_at = $4,
    interruption_reason = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND generation_status = $6
  AND generation_owner IS NOT DISTINCT FROM $7
  AND generation_lease_expires_at IS NOT DISTINCT FROM $8
  AND generation_attempt = $9
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type UpdateAIChatRunInterruptedParams struct {
	ID                               int32              `json:"id"`
	UserID                           string             `json:"user_id"`
	ErrorMessage                     pgtype.Text        `json:"error_message"`
	CompletedAt                      pgtype.Timestamptz `json:"completed_at"`
	InterruptionReason               pgtype.Text        `json:"interruption_reason"`
	ExpectedGenerationStatus         string             `json:"expected_generation_status"`
	ExpectedGenerationOwner          pgtype.Text        `json:"expected_generation_owner"`
	ExpectedGenerationLeaseExpiresAt pgtype.Timestamptz `json:"expected_generation_lease_expires_at"`
	ExpectedGenerationAttempt        int32              `json:"expected_generation_attempt"`
}

func (q *Queries) UpdateAIChatRunInterrupted(ctx context.Context, arg UpdateAIChatRunInterruptedParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, updateAIChatRunInterrupted,
		arg.ID,
		arg.UserID,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.InterruptionReason,
		arg.ExpectedGenerationStatus,
		arg.ExpectedGenerationOwner,
		arg.ExpectedGenerationLeaseExpiresAt,
		arg.ExpectedGenerationAttempt,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatRunStopped = `-- name: UpdateAIChatRunStopped :one
UPDATE ai_chat_run
SET status = 'stopped', error_message = NULL, completed_at = $3,
    workout_draft = NULL, generation_status = 'stopped',
    generation_owner = NULL, generation_lease_expires_at = NULL,
    generation_heartbeat_at = NULL, interrupted_at = NULL,
    interruption_reason = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND status = 'streaming'
RETURNING id, conversation_id, user_id, user_message_id, assistant_message_id,
          model, status, request_id, error_message, workout_draft,
          generation_status, generation_owner, generation_lease_expires_at,
          generation_heartbeat_at, generation_attempt, interrupted_at,
          interruption_reason, created_at, updated_at, started_at, completed_at
`

type UpdateAIChatRunStoppedParams struct {
	ID          int32              `json:"id"`
	UserID      string             `json:"user_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAIChatRunStopped(ctx context.Context, arg UpdateAIChatRunStoppedParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, updateAIChatRunStopped, arg.ID, arg.UserID, arg.CompletedAt)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
