// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAIChatTrialPrompt = `-- name: ConsumeAIChatTrialPrompt :one
INSERT INTO ai_chat_trial_prompt_usage (
    user_id,
    stripe_subscription_id,
    prompt_count
)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, stripe_subscription_id) DO UPDATE
SET prompt_count = ai_chat_trial_prompt_usage.prompt_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE ai_chat_trial_prompt_usage.prompt_count < $3
RETURNING user_id, stripe_subscription_id, prompt_count, created_at, updated_at
`

type ConsumeAIChatTrialPromptParams struct {
	UserID               string `json:"user_id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
	PromptCount          int32  `json:"prompt_count"`
}

func (q *Queries) ConsumeAIChatTrialPrompt(ctx context.Context, arg ConsumeAIChatTrialPromptParams) (AiChatTrialPromptUsage, error) {
	row := q.db.QueryRow(ctx, consumeAIChatTrialPrompt, arg.UserID, arg.StripeSubscriptionID, arg.PromptCount)
	var i AiChatTrialPromptUsage
	err := row.Scan(
		&i.UserID,
		&i.StripeSubscriptionID,
		&i.PromptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeAIChatTrialPromptForCurrentSubscription = `-- name: ConsumeAIChatTrialPromptForCurrentSubscription :one
WITH current_subscription AS (
    SELECT stripe_subscription_id, status
    FROM stripe_subscriptions
    WHERE stripe_subscriptions.user_id = $1
    ORDER BY
        stripe_event_created_at DESC,
        updated_at DESC,
        created_at DESC
    LIMIT 1
),
trial_subscription AS (
    SELECT stripe_subscription_id
    FROM current_subscription
    WHERE status = 'trialing'
),
consumed AS (
    INSERT INTO ai_chat_trial_prompt_usage (
        user_id,
        stripe_subscription_id,
        prompt_count
    )
    SELECT $1, stripe_subscription_id, 1
    FROM trial_subscription
    WHERE $2::integer > 0
    ON CONFLICT (user_id, stripe_subscription_id) DO UPDATE
    SET prompt_count = ai_chat_trial_prompt_usage.prompt_count + 1,
        updated_at = CURRENT_TIMESTAMP
    WHERE ai_chat_trial_prompt_usage.prompt_count < $2::integer
    RETURNING 1
)
SELECT
    NOT EXISTS (SELECT 1 FROM trial_subscription)
    OR EXISTS (SELECT 1 FROM consumed) AS allowed
`

type ConsumeAIChatTrialPromptForCurrentSubscriptionParams struct {
	UserID    string `json:"user_id"`
	PromptCap int32  `json:"prompt_cap"`
}

func (q *Queries) ConsumeAIChatTrialPromptForCurrentSubscription(ctx context.Context, arg ConsumeAIChatTrialPromptForCurrentSubscriptionParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, consumeAIChatTrialPromptForCurrentSubscription, arg.UserID, arg.PromptCap)
	var allowed pgtype.Bool
	err := row.Scan(&allowed)
	return allowed, err
}

const getAIChatTrialPromptUsage = `-- name: GetAIChatTrialPromptUsage :one
SELECT user_id, stripe_subscription_id, prompt_count, created_at, updated_at
FROM ai_chat_trial_prompt_usage
WHERE user_id = $1
  AND stripe_subscription_id = $2
`

type GetAIChatTrialPromptUsageParams struct {
	UserID               string `json:"user_id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
}

func (q *Queries) GetAIChatTrialPromptUsage(ctx context.Context, arg GetAIChatTrialPromptUsageParams) (AiChatTrialPromptUsage, error) {
	row := q.db.QueryRow(ctx, getAIChatTrialPromptUsage, arg.UserID, arg.StripeSubscriptionID)
	var i AiChatTrialPromptUsage
	err := row.Scan(
		&i.UserID,
		&i.StripeSubscriptionID,
		&i.PromptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingUserForUpdate = `-- name: GetBillingUserForUpdate :one
SELECT id, user_id, created_at
FROM users
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetBillingUserForUpdate(ctx context.Context, userID string) (Users, error) {
	row := q.db.QueryRow(ctx, getBillingUserForUpdate, userID)
	var i Users
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getCurrentStripeSubscriptionByUserID = `-- name: GetCurrentStripeSubscriptionByUserID :one
SELECT
    stripe_subscription_id,
    user_id,
    stripe_customer_id,
    stripe_price_id,
    stripe_event_created_at,
    status,
    cancel_at_period_end,
    cancel_at,
    current_period_start,
    current_period_end,
    trial_start,
    trial_end,
    created_at,
    updated_at
FROM stripe_subscriptions
WHERE user_id = $1
ORDER BY
    stripe_event_created_at DESC,
    updated_at DESC,
    created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentStripeSubscriptionByUserID(ctx context.Context, userID string) (StripeSubscriptions, error) {
	row := q.db.QueryRow(ctx, getCurrentStripeSubscriptionByUserID, userID)
	var i StripeSubscriptions
	err := row.Scan(
		&i.StripeSubscriptionID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripePriceID,
		&i.StripeEventCreatedAt,
		&i.Status,
		&i.CancelAtPeriodEnd,
		&i.CancelAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialStart,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStripeCustomerByUserID = `-- name: GetStripeCustomerByUserID :one

SELECT user_id, stripe_customer_id, created_at, updated_at
FROM stripe_customers
WHERE user_id = $1
`

// Billing queries
func (q *Queries) GetStripeCustomerByUserID(ctx context.Context, userID string) (StripeCustomers, error) {
	row := q.db.QueryRow(ctx, getStripeCustomerByUserID, userID)
	var i StripeCustomers
	err := row.Scan(
		&i.UserID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStripeCustomerUserIDByCustomerID = `-- name: GetStripeCustomerUserIDByCustomerID :one
SELECT user_id::text
FROM (SELECT lookup_stripe_customer_user_id($1::text) AS user_id) AS lookup
WHERE user_id IS NOT NULL
`

func (q *Queries) GetStripeCustomerUserIDByCustomerID(ctx context.Context, dollar_1 string) (string, error) {
	row := q.db.QueryRow(ctx, getStripeCustomerUserIDByCustomerID, dollar_1)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const grantStripeFeatureAccess = `-- name: GrantStripeFeatureAccess :exec
INSERT INTO user_feature_access (
    user_id,
    feature_key,
    source,
    source_reference,
    granted_by,
    note,
    starts_at,
    expires_at
)
VALUES ($1, $2, 'stripe', $3, 'stripe_webhook', $4, CURRENT_TIMESTAMP, $5)
`

type GrantStripeFeatureAccessParams struct {
	UserID          string             `json:"user_id"`
	FeatureKey      string             `json:"feature_key"`
	SourceReference pgtype.Text        `json:"source_reference"`
	Note            pgtype.Text        `json:"note"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GrantStripeFeatureAccess(ctx context.Context, arg GrantStripeFeatureAccessParams) error {
	_, err := q.db.Exec(ctx, grantStripeFeatureAccess,
		arg.UserID,
		arg.FeatureKey,
		arg.SourceReference,
		arg.Note,
		arg.ExpiresAt,
	)
	return err
}

const hasActiveFeatureAccess = `-- name: HasActiveFeatureAccess :one
SELECT EXISTS (
    SELECT 1
    FROM user_feature_access
    WHERE user_id = $1
      AND feature_key = $2
      AND revoked_at IS NULL
      AND starts_at <= NOW()
      AND (expires_at IS NULL OR expires_at > NOW())
)
`

type HasActiveFeatureAccessParams struct {
	UserID     string `json:"user_id"`
	FeatureKey string `json:"feature_key"`
}

func (q *Queries) HasActiveFeatureAccess(ctx context.Context, arg HasActiveFeatureAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveFeatureAccess, arg.UserID, arg.FeatureKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasProcessedStripeWebhookEvent = `-- name: HasProcessedStripeWebhookEvent :one
SELECT webhook_event.processed::boolean
FROM (
    SELECT public.has_processed_stripe_webhook_event(
        $1::TEXT
    ) AS processed
) AS webhook_event
`

func (q *Queries) HasProcessedStripeWebhookEvent(ctx context.Context, stripeEventID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasProcessedStripeWebhookEvent, stripeEventID)
	var webhook_event_processed bool
	err := row.Scan(&webhook_event_processed)
	return webhook_event_processed, err
}

const listActiveFeatureAccess = `-- name: ListActiveFeatureAccess :many
SELECT
    id,
    user_id,
    feature_key,
    source,
    source_reference,
    granted_by,
    note,
    starts_at,
    expires_at,
    revoked_at,
    created_at
FROM user_feature_access
WHERE user_id = $1
  AND revoked_at IS NULL
  AND starts_at <= NOW()
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY feature_key, starts_at DESC, id DESC
`

func (q *Queries) ListActiveFeatureAccess(ctx context.Context, userID string) ([]UserFeatureAccess, error) {
	rows, err := q.db.Query(ctx, listActiveFeatureAccess, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFeatureAccess
	for rows.Next() {
		var i UserFeatureAccess
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeatureKey,
			&i.Source,
			&i.SourceReference,
			&i.GrantedBy,
			&i.Note,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStripeWebhookEventProcessed = `-- name: MarkStripeWebhookEventProcessed :exec
SELECT public.record_stripe_webhook_event(
    $1::TEXT,
    $2::TEXT
)
`

type MarkStripeWebhookEventProcessedParams struct {
	StripeEventID string `json:"stripe_event_id"`
	EventType     string `json:"event_type"`
}

func (q *Queries) MarkStripeWebhookEventProcessed(ctx context.Context, arg MarkStripeWebhookEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markStripeWebhookEventProcessed, arg.StripeEventID, arg.EventType)
	return err
}

const revokeStripeFeatureAccess = `-- name: RevokeStripeFeatureAccess :exec
UPDATE user_feature_access
SET revoked_at = GREATEST(CURRENT_TIMESTAMP, starts_at)
WHERE user_id = $1
  AND feature_key = $2
  AND source = 'stripe'
  AND source_reference = $3
  AND revoked_at IS NULL
`

type RevokeStripeFeatureAccessParams struct {
	UserID          string      `json:"user_id"`
	FeatureKey      string      `json:"feature_key"`
	SourceReference pgtype.Text `json:"source_reference"`
}

func (q *Queries) RevokeStripeFeatureAccess(ctx context.Context, arg RevokeStripeFeatureAccessParams) error {
	_, err := q.db.Exec(ctx, revokeStripeFeatureAccess, arg.UserID, arg.FeatureKey, arg.SourceReference)
	return err
}

const upsertStripeCustomer = `-- name: UpsertStripeCustomer :one
INSERT INTO stripe_customers (
    user_id,
    stripe_customer_id
)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET stripe_customer_id = EXCLUDED.stripe_customer_id,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, stripe_customer_id, created_at, updated_at
`

type UpsertStripeCustomerParams struct {
	UserID           string `json:"user_id"`
	StripeCustomerID string `json:"stripe_customer_id"`
}

func (q *Queries) UpsertStripeCustomer(ctx context.Context, arg UpsertStripeCustomerParams) (StripeCustomers, error) {
	row := q.db.QueryRow(ctx, upsertStripeCustomer, arg.UserID, arg.StripeCustomerID)
	var i StripeCustomers
	err := row.Scan(
		&i.UserID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStripeSubscription = `-- name: UpsertStripeSubscription :one
INSERT INTO stripe_subscriptions (
    stripe_subscription_id,
    user_id,
    stripe_customer_id,
    stripe_price_id,
    stripe_event_created_at,
    status,
    cancel_at_period_end,
    cancel_at,
    current_period_start,
    current_period_end,
    trial_start,
    trial_end
)
VALUES (
    $1,
    $2,
    $3,
    NULLIF($4::text, ''),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (stripe_subscription_id) DO UPDATE
SET user_id = EXCLUDED.user_id,
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_price_id = EXCLUDED.stripe_price_id,
    stripe_event_created_at = EXCLUDED.stripe_event_created_at,
    status = EXCLUDED.status,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    cancel_at = EXCLUDED.cancel_at,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    trial_start = EXCLUDED.trial_start,
    trial_end = EXCLUDED.trial_end,
    updated_at = CURRENT_TIMESTAMP
WHERE stripe_subscriptions.stripe_event_created_at < EXCLUDED.stripe_event_created_at
   OR (
       stripe_subscriptions.stripe_event_created_at = EXCLUDED.stripe_event_created_at
       AND NOT (
           stripe_subscriptions.status IN ('past_due', 'unpaid', 'canceled', 'incomplete', 'incomplete_expired', 'paused')
           AND EXCLUDED.status IN ('trialing', 'active')
       )
   )
RETURNING
    stripe_subscription_id,
    user_id,
    stripe_customer_id,
    stripe_price_id,
    stripe_event_created_at,
    status,
    cancel_at_period_end,
    cancel_at,
    current_period_start,
    current_period_end,
    trial_start,
    trial_end,
    created_at,
    updated_at
`

type UpsertStripeSubscriptionParams struct {
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	UserID               string             `json:"user_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	StripeEventCreatedAt pgtype.Timestamptz `json:"stripe_event_created_at"`
	Status               string             `json:"status"`
	CancelAtPeriodEnd    bool               `json:"cancel_at_period_end"`
	CancelAt             pgtype.Timestamptz `json:"cancel_at"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	TrialStart           pgtype.Timestamptz `json:"trial_start"`
	TrialEnd             pgtype.Timestamptz `json:"trial_end"`
}

func (q *Queries) UpsertStripeSubscription(ctx context.Context, arg UpsertStripeSubscriptionParams) (StripeSubscriptions, error) {
	row := q.db.QueryRow(ctx, upsertStripeSubscription,
		arg.StripeSubscriptionID,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripePriceID,
		arg.StripeEventCreatedAt,
		arg.Status,
		arg.CancelAtPeriodEnd,
		arg.CancelAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialStart,
		arg.TrialEnd,
	)
	var i StripeSubscriptions
	err := row.Scan(
		&i.StripeSubscriptionID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripePriceID,
		&i.StripeEventCreatedAt,
		&i.Status,
		&i.CancelAtPeriodEnd,
		&i.CancelAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialStart,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
