// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercise WHERE id = $1 AND user_id = $2
`

type DeleteExerciseParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) error {
	_, err := q.db.Exec(ctx, deleteExercise, arg.ID, arg.UserID)
	return err
}

const getExercise = `-- name: GetExercise :one
SELECT id, name, catalog_id FROM exercise WHERE id = $1 AND user_id = $2
`

type GetExerciseParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type GetExerciseRow struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	CatalogID pgtype.Text `json:"catalog_id"`
}

func (q *Queries) GetExercise(ctx context.Context, arg GetExerciseParams) (GetExerciseRow, error) {
	row := q.db.QueryRow(ctx, getExercise, arg.ID, arg.UserID)
	var i GetExerciseRow
	err := row.Scan(&i.ID, &i.Name, &i.CatalogID)
	return i, err
}

const getExerciseBestE1rmWithWorkout = `-- name: GetExerciseBestE1rmWithWorkout :one
WITH working AS (
    SELECT
        s.workout_id,
        w.date AS workout_date,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))::numeric(8,2) AS e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    WHERE s.user_id = $1
      AND s.exercise_id = $2
      AND s.set_type = 'working'
)
SELECT workout_id, e1rm
FROM working
ORDER BY e1rm DESC, workout_date DESC, workout_id DESC
LIMIT 1
`

type GetExerciseBestE1rmWithWorkoutParams struct {
	UserID     string `json:"user_id"`
	ExerciseID int32  `json:"exercise_id"`
}

type GetExerciseBestE1rmWithWorkoutRow struct {
	WorkoutID int32          `json:"workout_id"`
	E1rm      pgtype.Numeric `json:"e1rm"`
}

func (q *Queries) GetExerciseBestE1rmWithWorkout(ctx context.Context, arg GetExerciseBestE1rmWithWorkoutParams) (GetExerciseBestE1rmWithWorkoutRow, error) {
	row := q.db.QueryRow(ctx, getExerciseBestE1rmWithWorkout, arg.UserID, arg.ExerciseID)
	var i GetExerciseBestE1rmWithWorkoutRow
	err := row.Scan(&i.WorkoutID, &i.E1rm)
	return i, err
}

const getExerciseBestE1rmWithWorkoutExcludingWorkout = `-- name: GetExerciseBestE1rmWithWorkoutExcludingWorkout :one
WITH working AS (
    SELECT
        s.workout_id,
        w.date AS workout_date,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))::numeric(8,2) AS e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    WHERE s.user_id = $1
      AND s.exercise_id = $2
      AND s.workout_id <> $3
      AND s.set_type = 'working'
)
SELECT workout_id, e1rm
FROM working
ORDER BY e1rm DESC, workout_date DESC, workout_id DESC
LIMIT 1
`

type GetExerciseBestE1rmWithWorkoutExcludingWorkoutParams struct {
	UserID     string `json:"user_id"`
	ExerciseID int32  `json:"exercise_id"`
	WorkoutID  int32  `json:"workout_id"`
}

type GetExerciseBestE1rmWithWorkoutExcludingWorkoutRow struct {
	WorkoutID int32          `json:"workout_id"`
	E1rm      pgtype.Numeric `json:"e1rm"`
}

func (q *Queries) GetExerciseBestE1rmWithWorkoutExcludingWorkout(ctx context.Context, arg GetExerciseBestE1rmWithWorkoutExcludingWorkoutParams) (GetExerciseBestE1rmWithWorkoutExcludingWorkoutRow, error) {
	row := q.db.QueryRow(ctx, getExerciseBestE1rmWithWorkoutExcludingWorkout, arg.UserID, arg.ExerciseID, arg.WorkoutID)
	var i GetExerciseBestE1rmWithWorkoutExcludingWorkoutRow
	err := row.Scan(&i.WorkoutID, &i.E1rm)
	return i, err
}

const getExerciseByName = `-- name: GetExerciseByName :one
SELECT id, name, catalog_id FROM exercise WHERE name = $1 AND user_id = $2
`

type GetExerciseByNameParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

type GetExerciseByNameRow struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	CatalogID pgtype.Text `json:"catalog_id"`
}

func (q *Queries) GetExerciseByName(ctx context.Context, arg GetExerciseByNameParams) (GetExerciseByNameRow, error) {
	row := q.db.QueryRow(ctx, getExerciseByName, arg.Name, arg.UserID)
	var i GetExerciseByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.CatalogID)
	return i, err
}

const getExerciseDetail = `-- name: GetExerciseDetail :one
SELECT
    e.id,
    e.name,
    e.catalog_id,
    e.created_at,
    e.updated_at,
    e.user_id,
    e.historical_1rm,
    e.historical_1rm_updated_at,
    e.historical_1rm_source_workout_id,
    (
        SELECT MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)))::numeric(8,2)
        FROM "set" s
        WHERE s.exercise_id = e.id
          AND s.user_id = e.user_id
          AND s.set_type = 'working'
    ) AS best_e1rm
FROM exercise e
WHERE e.id = $1 AND e.user_id = $2
`

type GetExerciseDetailParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type GetExerciseDetailRow struct {
	ID                           int32              `json:"id"`
	Name                         string             `json:"name"`
	CatalogID                    pgtype.Text        `json:"catalog_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	UserID                       string             `json:"user_id"`
	Historical1rm                pgtype.Numeric     `json:"historical_1rm"`
	Historical1rmUpdatedAt       pgtype.Timestamptz `json:"historical_1rm_updated_at"`
	Historical1rmSourceWorkoutID pgtype.Int4        `json:"historical_1rm_source_workout_id"`
	BestE1rm                     pgtype.Numeric     `json:"best_e1rm"`
}

func (q *Queries) GetExerciseDetail(ctx context.Context, arg GetExerciseDetailParams) (GetExerciseDetailRow, error) {
	row := q.db.QueryRow(ctx, getExerciseDetail, arg.ID, arg.UserID)
	var i GetExerciseDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CatalogID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Historical1rm,
		&i.Historical1rmUpdatedAt,
		&i.Historical1rmSourceWorkoutID,
		&i.BestE1rm,
	)
	return i, err
}

const getExerciseMetricsHistoryRaw6M = `-- name: GetExerciseMetricsHistoryRaw6M :many
WITH working_sets AS (
    SELECT
        w.id AS workout_id,
        w.date::date AS workout_day,
        COALESCE(s.weight, 0)::numeric AS weight,
        s.reps AS reps,
        (COALESCE(s.weight, 0)::numeric * s.reps::numeric) AS volume,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)) AS e1rm,
        e.historical_1rm AS historical_1rm,
        MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))) OVER (PARTITION BY w.id) AS session_best_e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    JOIN exercise e ON e.id = s.exercise_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
),
end_day AS (
    SELECT MAX(workout_day) AS end_day
    FROM working_sets
),
filtered AS (
    SELECT workout_id, workout_day, weight, reps, volume, e1rm, historical_1rm, session_best_e1rm, end_day
    FROM working_sets, end_day
    WHERE workout_day >= end_day - interval '6 months'
),
workout_metrics AS (
    SELECT
        workout_id,
        MIN(workout_day)::date AS workout_day,
        COALESCE(MAX(session_best_e1rm), 0)::float8 AS session_best_e1rm,
        COALESCE(AVG(e1rm), 0)::float8 AS session_avg_e1rm,
        COALESCE(AVG(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_avg_intensity,
        COALESCE(MAX(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_best_intensity,
        COALESCE(SUM(volume), 0)::float8 AS total_volume_working
    FROM filtered
    GROUP BY workout_id
)
SELECT workout_id, workout_day, session_best_e1rm, session_avg_e1rm, session_avg_intensity, session_best_intensity, total_volume_working
FROM workout_metrics
ORDER BY workout_day ASC, workout_id ASC
`

type GetExerciseMetricsHistoryRaw6MParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseMetricsHistoryRaw6MRow struct {
	WorkoutID            int32       `json:"workout_id"`
	WorkoutDay           pgtype.Date `json:"workout_day"`
	SessionBestE1rm      float64     `json:"session_best_e1rm"`
	SessionAvgE1rm       float64     `json:"session_avg_e1rm"`
	SessionAvgIntensity  float64     `json:"session_avg_intensity"`
	SessionBestIntensity float64     `json:"session_best_intensity"`
	TotalVolumeWorking   float64     `json:"total_volume_working"`
}

func (q *Queries) GetExerciseMetricsHistoryRaw6M(ctx context.Context, arg GetExerciseMetricsHistoryRaw6MParams) ([]GetExerciseMetricsHistoryRaw6MRow, error) {
	rows, err := q.db.Query(ctx, getExerciseMetricsHistoryRaw6M, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseMetricsHistoryRaw6MRow
	for rows.Next() {
		var i GetExerciseMetricsHistoryRaw6MRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDay,
			&i.SessionBestE1rm,
			&i.SessionAvgE1rm,
			&i.SessionAvgIntensity,
			&i.SessionBestIntensity,
			&i.TotalVolumeWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseMetricsHistoryRawAll = `-- name: GetExerciseMetricsHistoryRawAll :many
WITH working_sets AS (
    SELECT
        w.id AS workout_id,
        w.date::date AS workout_day,
        COALESCE(s.weight, 0)::numeric AS weight,
        s.reps AS reps,
        (COALESCE(s.weight, 0)::numeric * s.reps::numeric) AS volume,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)) AS e1rm,
        e.historical_1rm AS historical_1rm,
        MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))) OVER (PARTITION BY w.id) AS session_best_e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    JOIN exercise e ON e.id = s.exercise_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
),
workout_metrics AS (
    SELECT
        workout_id,
        MIN(workout_day)::date AS workout_day,
        COALESCE(MAX(session_best_e1rm), 0)::float8 AS session_best_e1rm,
        COALESCE(AVG(e1rm), 0)::float8 AS session_avg_e1rm,
        COALESCE(AVG(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_avg_intensity,
        COALESCE(MAX(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_best_intensity,
        COALESCE(SUM(volume), 0)::float8 AS total_volume_working
    FROM working_sets
    GROUP BY workout_id
)
SELECT workout_id, workout_day, session_best_e1rm, session_avg_e1rm, session_avg_intensity, session_best_intensity, total_volume_working
FROM workout_metrics
ORDER BY workout_day ASC, workout_id ASC
`

type GetExerciseMetricsHistoryRawAllParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseMetricsHistoryRawAllRow struct {
	WorkoutID            int32       `json:"workout_id"`
	WorkoutDay           pgtype.Date `json:"workout_day"`
	SessionBestE1rm      float64     `json:"session_best_e1rm"`
	SessionAvgE1rm       float64     `json:"session_avg_e1rm"`
	SessionAvgIntensity  float64     `json:"session_avg_intensity"`
	SessionBestIntensity float64     `json:"session_best_intensity"`
	TotalVolumeWorking   float64     `json:"total_volume_working"`
}

func (q *Queries) GetExerciseMetricsHistoryRawAll(ctx context.Context, arg GetExerciseMetricsHistoryRawAllParams) ([]GetExerciseMetricsHistoryRawAllRow, error) {
	rows, err := q.db.Query(ctx, getExerciseMetricsHistoryRawAll, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseMetricsHistoryRawAllRow
	for rows.Next() {
		var i GetExerciseMetricsHistoryRawAllRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDay,
			&i.SessionBestE1rm,
			&i.SessionAvgE1rm,
			&i.SessionAvgIntensity,
			&i.SessionBestIntensity,
			&i.TotalVolumeWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseMetricsHistoryRawYear = `-- name: GetExerciseMetricsHistoryRawYear :many
WITH working_sets AS (
    SELECT
        w.id AS workout_id,
        w.date::date AS workout_day,
        COALESCE(s.weight, 0)::numeric AS weight,
        s.reps AS reps,
        (COALESCE(s.weight, 0)::numeric * s.reps::numeric) AS volume,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)) AS e1rm,
        e.historical_1rm AS historical_1rm,
        MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))) OVER (PARTITION BY w.id) AS session_best_e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    JOIN exercise e ON e.id = s.exercise_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
),
end_day AS (
    SELECT MAX(workout_day) AS end_day
    FROM working_sets
),
filtered AS (
    SELECT workout_id, workout_day, weight, reps, volume, e1rm, historical_1rm, session_best_e1rm, end_day
    FROM working_sets, end_day
    WHERE workout_day >= end_day - interval '1 year'
),
workout_metrics AS (
    SELECT
        workout_id,
        MIN(workout_day)::date AS workout_day,
        COALESCE(MAX(session_best_e1rm), 0)::float8 AS session_best_e1rm,
        COALESCE(AVG(e1rm), 0)::float8 AS session_avg_e1rm,
        COALESCE(AVG(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_avg_intensity,
        COALESCE(MAX(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_best_intensity,
        COALESCE(SUM(volume), 0)::float8 AS total_volume_working
    FROM filtered
    GROUP BY workout_id
)
SELECT workout_id, workout_day, session_best_e1rm, session_avg_e1rm, session_avg_intensity, session_best_intensity, total_volume_working
FROM workout_metrics
ORDER BY workout_day ASC, workout_id ASC
`

type GetExerciseMetricsHistoryRawYearParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseMetricsHistoryRawYearRow struct {
	WorkoutID            int32       `json:"workout_id"`
	WorkoutDay           pgtype.Date `json:"workout_day"`
	SessionBestE1rm      float64     `json:"session_best_e1rm"`
	SessionAvgE1rm       float64     `json:"session_avg_e1rm"`
	SessionAvgIntensity  float64     `json:"session_avg_intensity"`
	SessionBestIntensity float64     `json:"session_best_intensity"`
	TotalVolumeWorking   float64     `json:"total_volume_working"`
}

func (q *Queries) GetExerciseMetricsHistoryRawYear(ctx context.Context, arg GetExerciseMetricsHistoryRawYearParams) ([]GetExerciseMetricsHistoryRawYearRow, error) {
	rows, err := q.db.Query(ctx, getExerciseMetricsHistoryRawYear, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseMetricsHistoryRawYearRow
	for rows.Next() {
		var i GetExerciseMetricsHistoryRawYearRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDay,
			&i.SessionBestE1rm,
			&i.SessionAvgE1rm,
			&i.SessionAvgIntensity,
			&i.SessionBestIntensity,
			&i.TotalVolumeWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseWithSets = `-- name: GetExerciseWithSets :many
SELECT 
    s.workout_id,
    w.date as workout_date,
    w.notes as workout_notes,
    w.workout_focus as workout_focus,
    s.id as set_id,
    s.weight,
    s.reps,
    s.set_type,
    e.id as exercise_id,
    e.name as exercise_name,
    s.exercise_order,
    s.set_order,
    (COALESCE(s.weight, 0) * s.reps)::NUMERIC(10,1) as volume
FROM "set" s
JOIN exercise e ON e.id = s.exercise_id
JOIN workout w ON w.id = s.workout_id
WHERE s.exercise_id = $1 AND s.user_id = $2
ORDER BY w.date DESC, s.exercise_order, s.set_order, s.created_at, s.id
`

type GetExerciseWithSetsParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseWithSetsRow struct {
	WorkoutID     int32              `json:"workout_id"`
	WorkoutDate   pgtype.Timestamptz `json:"workout_date"`
	WorkoutNotes  pgtype.Text        `json:"workout_notes"`
	WorkoutFocus  pgtype.Text        `json:"workout_focus"`
	SetID         int32              `json:"set_id"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	SetType       string             `json:"set_type"`
	ExerciseID    int32              `json:"exercise_id"`
	ExerciseName  string             `json:"exercise_name"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
	Volume        pgtype.Numeric     `json:"volume"`
}

func (q *Queries) GetExerciseWithSets(ctx context.Context, arg GetExerciseWithSetsParams) ([]GetExerciseWithSetsRow, error) {
	rows, err := q.db.Query(ctx, getExerciseWithSets, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseWithSetsRow
	for rows.Next() {
		var i GetExerciseWithSetsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.WorkoutNotes,
			&i.WorkoutFocus,
			&i.SetID,
			&i.Weight,
			&i.Reps,
			&i.SetType,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.ExerciseOrder,
			&i.SetOrder,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateCatalogExercise = `-- name: GetOrCreateCatalogExercise :one
INSERT INTO exercise (name, user_id, catalog_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type GetOrCreateCatalogExerciseParams struct {
	Name      string      `json:"name"`
	UserID    string      `json:"user_id"`
	CatalogID pgtype.Text `json:"catalog_id"`
}

func (q *Queries) GetOrCreateCatalogExercise(ctx context.Context, arg GetOrCreateCatalogExerciseParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateCatalogExercise, arg.Name, arg.UserID, arg.CatalogID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateExercise = `-- name: GetOrCreateExercise :one
INSERT INTO exercise (name, user_id)
VALUES ($1, $2)
ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type GetOrCreateExerciseParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetOrCreateExercise(ctx context.Context, arg GetOrCreateExerciseParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateExercise, arg.Name, arg.UserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRecentSetsForExercise = `-- name: GetRecentSetsForExercise :many

SELECT
    s.id AS set_id,
    w.id AS workout_id,
    w.date AS workout_date,
    w.workout_focus AS workout_focus,
    s.weight,
    s.reps,
    s.exercise_order,
    s.set_order,
    s.created_at
FROM "set" s
JOIN workout w ON w.id = s.workout_id
WHERE s.exercise_id = $1 AND s.user_id = $2
ORDER BY w.date DESC, s.set_order DESC
LIMIT 3
`

type GetRecentSetsForExerciseParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetRecentSetsForExerciseRow struct {
	SetID         int32              `json:"set_id"`
	WorkoutID     int32              `json:"workout_id"`
	WorkoutDate   pgtype.Timestamptz `json:"workout_date"`
	WorkoutFocus  pgtype.Text        `json:"workout_focus"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// User queries
func (q *Queries) GetRecentSetsForExercise(ctx context.Context, arg GetRecentSetsForExerciseParams) ([]GetRecentSetsForExerciseRow, error) {
	rows, err := q.db.Query(ctx, getRecentSetsForExercise, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentSetsForExerciseRow
	for rows.Next() {
		var i GetRecentSetsForExerciseRow
		if err := rows.Scan(
			&i.SetID,
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.WorkoutFocus,
			&i.Weight,
			&i.Reps,
			&i.ExerciseOrder,
			&i.SetOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutBestE1rmByExercise = `-- name: GetWorkoutBestE1rmByExercise :many
SELECT
    s.exercise_id,
    MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)))::numeric(8,2) AS best_e1rm
FROM "set" s
WHERE s.workout_id = $1
  AND s.user_id = $2
  AND s.set_type = 'working'
GROUP BY s.exercise_id
`

type GetWorkoutBestE1rmByExerciseParams struct {
	WorkoutID int32  `json:"workout_id"`
	UserID    string `json:"user_id"`
}

type GetWorkoutBestE1rmByExerciseRow struct {
	ExerciseID int32          `json:"exercise_id"`
	BestE1rm   pgtype.Numeric `json:"best_e1rm"`
}

func (q *Queries) GetWorkoutBestE1rmByExercise(ctx context.Context, arg GetWorkoutBestE1rmByExerciseParams) ([]GetWorkoutBestE1rmByExerciseRow, error) {
	rows, err := q.db.Query(ctx, getWorkoutBestE1rmByExercise, arg.WorkoutID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkoutBestE1rmByExerciseRow
	for rows.Next() {
		var i GetWorkoutBestE1rmByExerciseRow
		if err := rows.Scan(&i.ExerciseID, &i.BestE1rm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercises = `-- name: ListExercises :many
SELECT id, name, catalog_id FROM exercise WHERE user_id = $1 ORDER BY name
`

type ListExercisesRow struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	CatalogID pgtype.Text `json:"catalog_id"`
}

func (q *Queries) ListExercises(ctx context.Context, userID string) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesRow
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CatalogID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesWithHistorical1RMSourceWorkout = `-- name: ListExercisesWithHistorical1RMSourceWorkout :many
SELECT id
FROM exercise
WHERE user_id = $1 AND historical_1rm_source_workout_id = $2
`

type ListExercisesWithHistorical1RMSourceWorkoutParams struct {
	UserID                       string      `json:"user_id"`
	Historical1rmSourceWorkoutID pgtype.Int4 `json:"historical_1rm_source_workout_id"`
}

func (q *Queries) ListExercisesWithHistorical1RMSourceWorkout(ctx context.Context, arg ListExercisesWithHistorical1RMSourceWorkoutParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listExercisesWithHistorical1RMSourceWorkout, arg.UserID, arg.Historical1rmSourceWorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExerciseHistorical1RM = `-- name: SetExerciseHistorical1RM :exec
UPDATE exercise
SET
    historical_1rm = $2,
    historical_1rm_updated_at = NOW(),
    historical_1rm_source_workout_id = $3,
    updated_at = NOW()
WHERE id = $1 AND user_id = $4
`

type SetExerciseHistorical1RMParams struct {
	ID                           int32          `json:"id"`
	Historical1rm                pgtype.Numeric `json:"historical_1rm"`
	Historical1rmSourceWorkoutID pgtype.Int4    `json:"historical_1rm_source_workout_id"`
	UserID                       string         `json:"user_id"`
}

func (q *Queries) SetExerciseHistorical1RM(ctx context.Context, arg SetExerciseHistorical1RMParams) error {
	_, err := q.db.Exec(ctx, setExerciseHistorical1RM,
		arg.ID,
		arg.Historical1rm,
		arg.Historical1rmSourceWorkoutID,
		arg.UserID,
	)
	return err
}

const updateExerciseCatalog = `-- name: UpdateExerciseCatalog :one
UPDATE exercise SET catalog_id = $3, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id
`

type UpdateExerciseCatalogParams struct {
	ID        int32       `json:"id"`
	UserID    string      `json:"user_id"`
	CatalogID pgtype.Text `json:"catalog_id"`
}

func (q *Queries) UpdateExerciseCatalog(ctx context.Context, arg UpdateExerciseCatalogParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateExerciseCatalog, arg.ID, arg.UserID, arg.CatalogID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateExerciseHistorical1RMFromWorkoutIfBetter = `-- name: UpdateExerciseHistorical1RMFromWorkoutIfBetter :exec
UPDATE exercise
SET
    historical_1rm = $2,
    historical_1rm_updated_at = NOW(),
    historical_1rm_source_workout_id = $3,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $4
  AND (historical_1rm IS NULL OR historical_1rm < $2)
`

type UpdateExerciseHistorical1RMFromWorkoutIfBetterParams struct {
	ID                           int32          `json:"id"`
	Historical1rm                pgtype.Numeric `json:"historical_1rm"`
	Historical1rmSourceWorkoutID pgtype.Int4    `json:"historical_1rm_source_workout_id"`
	UserID                       string         `json:"user_id"`
}

func (q *Queries) UpdateExerciseHistorical1RMFromWorkoutIfBetter(ctx context.Context, arg UpdateExerciseHistorical1RMFromWorkoutIfBetterParams) error {
	_, err := q.db.Exec(ctx, updateExerciseHistorical1RMFromWorkoutIfBetter,
		arg.ID,
		arg.Historical1rm,
		arg.Historical1rmSourceWorkoutID,
		arg.UserID,
	)
	return err
}

const updateExerciseHistorical1RMManual = `-- name: UpdateExerciseHistorical1RMManual :exec
UPDATE exercise
SET
    historical_1rm = $2,
    historical_1rm_updated_at = NOW(),
    historical_1rm_source_workout_id = NULL,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
`

type UpdateExerciseHistorical1RMManualParams struct {
	ID            int32          `json:"id"`
	Historical1rm pgtype.Numeric `json:"historical_1rm"`
	UserID        string         `json:"user_id"`
}

func (q *Queries) UpdateExerciseHistorical1RMManual(ctx context.Context, arg UpdateExerciseHistorical1RMManualParams) error {
	_, err := q.db.Exec(ctx, updateExerciseHistorical1RMManual, arg.ID, arg.Historical1rm, arg.UserID)
	return err
}

const updateExerciseName = `-- name: UpdateExerciseName :exec
UPDATE exercise
SET name = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
`

type UpdateExerciseNameParams struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateExerciseName(ctx context.Context, arg UpdateExerciseNameParams) error {
	_, err := q.db.Exec(ctx, updateExerciseName, arg.ID, arg.Name, arg.UserID)
	return err
}
