// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.Text        `json:"user_id"`
}

type Set struct {
	ID         int32              `json:"id"`
	ExerciseID int32              `json:"exercise_id"`
	WorkoutID  int32              `json:"workout_id"`
	Weight     pgtype.Int4        `json:"weight"`
	Reps       int32              `json:"reps"`
	SetType    string             `json:"set_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Users struct {
	ID        int32              `json:"id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workout struct {
	ID        int32              `json:"id"`
	Date      pgtype.Timestamptz `json:"date"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.Text        `json:"user_id"`
}
