// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiChatConversation struct {
	ID            int32              `json:"id"`
	UserID        string             `json:"user_id"`
	Title         pgtype.Text        `json:"title"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

type AiChatMessage struct {
	ID             int32              `json:"id"`
	ConversationID int32              `json:"conversation_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type AiChatRun struct {
	ID                 int32              `json:"id"`
	ConversationID     int32              `json:"conversation_id"`
	UserID             string             `json:"user_id"`
	UserMessageID      int32              `json:"user_message_id"`
	AssistantMessageID int32              `json:"assistant_message_id"`
	Model              string             `json:"model"`
	Status             string             `json:"status"`
	RequestID          pgtype.Text        `json:"request_id"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

type Exercise struct {
	ID                           int32              `json:"id"`
	Name                         string             `json:"name"`
	Historical1rm                pgtype.Numeric     `json:"historical_1rm"`
	Historical1rmUpdatedAt       pgtype.Timestamptz `json:"historical_1rm_updated_at"`
	Historical1rmSourceWorkoutID pgtype.Int4        `json:"historical_1rm_source_workout_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	UserID                       string             `json:"user_id"`
}

type Set struct {
	ID            int32              `json:"id"`
	ExerciseID    int32              `json:"exercise_id"`
	WorkoutID     int32              `json:"workout_id"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	SetType       string             `json:"set_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserID        string             `json:"user_id"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
}

type UserFeatureAccess struct {
	ID              int32              `json:"id"`
	UserID          string             `json:"user_id"`
	FeatureKey      string             `json:"feature_key"`
	Source          string             `json:"source"`
	SourceReference pgtype.Text        `json:"source_reference"`
	GrantedBy       pgtype.Text        `json:"granted_by"`
	Note            pgtype.Text        `json:"note"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Users struct {
	ID        int32              `json:"id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workout struct {
	ID           int32              `json:"id"`
	Date         pgtype.Timestamptz `json:"date"`
	Notes        pgtype.Text        `json:"notes"`
	WorkoutFocus pgtype.Text        `json:"workout_focus"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UserID       string             `json:"user_id"`
}
