// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiChatConversation struct {
	ID                               int32              `json:"id"`
	UserID                           string             `json:"user_id"`
	Title                            pgtype.Text        `json:"title"`
	LatestWorkoutDraft               []byte             `json:"latest_workout_draft"`
	LatestWorkoutDraftSourceRunID    pgtype.Int4        `json:"latest_workout_draft_source_run_id"`
	LatestWorkoutDraftSavedWorkoutID pgtype.Int4        `json:"latest_workout_draft_saved_workout_id"`
	LatestWorkoutDraftSavedAt        pgtype.Timestamptz `json:"latest_workout_draft_saved_at"`
	CreatedAt                        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                        pgtype.Timestamptz `json:"updated_at"`
	LastMessageAt                    pgtype.Timestamptz `json:"last_message_at"`
}

type AiChatMessage struct {
	ID             int32              `json:"id"`
	ConversationID int32              `json:"conversation_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type AiChatRun struct {
	ID                       int32              `json:"id"`
	ConversationID           int32              `json:"conversation_id"`
	UserID                   string             `json:"user_id"`
	UserMessageID            int32              `json:"user_message_id"`
	AssistantMessageID       int32              `json:"assistant_message_id"`
	Model                    string             `json:"model"`
	Status                   string             `json:"status"`
	RequestID                pgtype.Text        `json:"request_id"`
	ErrorMessage             pgtype.Text        `json:"error_message"`
	WorkoutDraft             []byte             `json:"workout_draft"`
	GenerationStatus         string             `json:"generation_status"`
	GenerationOwner          pgtype.Text        `json:"generation_owner"`
	GenerationLeaseExpiresAt pgtype.Timestamptz `json:"generation_lease_expires_at"`
	GenerationHeartbeatAt    pgtype.Timestamptz `json:"generation_heartbeat_at"`
	GenerationAttempt        int32              `json:"generation_attempt"`
	InterruptedAt            pgtype.Timestamptz `json:"interrupted_at"`
	InterruptionReason       pgtype.Text        `json:"interruption_reason"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	StartedAt                pgtype.Timestamptz `json:"started_at"`
	CompletedAt              pgtype.Timestamptz `json:"completed_at"`
}

type AiChatStreamChunk struct {
	RunID     int32              `json:"run_id"`
	UserID    string             `json:"user_id"`
	Sequence  int32              `json:"sequence"`
	DeltaText string             `json:"delta_text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AiChatTrialPromptUsage struct {
	UserID               string             `json:"user_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	PromptCount          int32              `json:"prompt_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Exercise struct {
	ID                           int32              `json:"id"`
	Name                         string             `json:"name"`
	Historical1rm                pgtype.Numeric     `json:"historical_1rm"`
	Historical1rmUpdatedAt       pgtype.Timestamptz `json:"historical_1rm_updated_at"`
	Historical1rmSourceWorkoutID pgtype.Int4        `json:"historical_1rm_source_workout_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	UserID                       string             `json:"user_id"`
}

type Set struct {
	ID            int32              `json:"id"`
	ExerciseID    int32              `json:"exercise_id"`
	WorkoutID     int32              `json:"workout_id"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	SetType       string             `json:"set_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserID        string             `json:"user_id"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
}

type StripeCustomers struct {
	UserID           string             `json:"user_id"`
	StripeCustomerID string             `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type StripeSubscriptions struct {
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	UserID               string             `json:"user_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripePriceID        pgtype.Text        `json:"stripe_price_id"`
	StripeEventCreatedAt pgtype.Timestamptz `json:"stripe_event_created_at"`
	Status               string             `json:"status"`
	CancelAtPeriodEnd    bool               `json:"cancel_at_period_end"`
	CancelAt             pgtype.Timestamptz `json:"cancel_at"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	TrialStart           pgtype.Timestamptz `json:"trial_start"`
	TrialEnd             pgtype.Timestamptz `json:"trial_end"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type StripeWebhookEvents struct {
	StripeEventID string             `json:"stripe_event_id"`
	EventType     string             `json:"event_type"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
}

type UserFeatureAccess struct {
	ID              int32              `json:"id"`
	UserID          string             `json:"user_id"`
	FeatureKey      string             `json:"feature_key"`
	Source          string             `json:"source"`
	SourceReference pgtype.Text        `json:"source_reference"`
	GrantedBy       pgtype.Text        `json:"granted_by"`
	Note            pgtype.Text        `json:"note"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type UserTrainingProfile struct {
	UserID                          string             `json:"user_id"`
	PrimaryGoal                     pgtype.Text        `json:"primary_goal"`
	ExperienceLevel                 pgtype.Text        `json:"experience_level"`
	PreferredSessionDurationMinutes pgtype.Int4        `json:"preferred_session_duration_minutes"`
	UsualTrainingLocation           pgtype.Text        `json:"usual_training_location"`
	AvailableEquipment              []byte             `json:"available_equipment"`
	AvoidedExercises                []byte             `json:"avoided_exercises"`
	MovementLimitations             []byte             `json:"movement_limitations"`
	SourceConversationID            pgtype.Int4        `json:"source_conversation_id"`
	SourceMessageID                 pgtype.Int4        `json:"source_message_id"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
}

type Users struct {
	ID        int32              `json:"id"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workout struct {
	ID           int32              `json:"id"`
	Date         pgtype.Timestamptz `json:"date"`
	Notes        pgtype.Text        `json:"notes"`
	WorkoutFocus pgtype.Text        `json:"workout_focus"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UserID       string             `json:"user_id"`
}
