// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAIChatRunGeneration = `-- name: ClaimAIChatRunGeneration :one
UPDATE ai_chat_run
SET generation_status = 'generating',
    generation_owner = $3,
    generation_lease_expires_at = $4,
    generation_heartbeat_at = $5,
    generation_attempt = generation_attempt + 1,
    error_message = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND generation_attempt < $6
  AND (
    generation_status = 'queued'
    OR (
      generation_status = 'generating'
      AND generation_lease_expires_at IS NOT NULL
      AND generation_lease_expires_at < $5
    )
  )
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type ClaimAIChatRunGenerationParams struct {
	ID                       int32              `json:"id"`
	UserID                   string             `json:"user_id"`
	GenerationOwner          pgtype.Text        `json:"generation_owner"`
	GenerationLeaseExpiresAt pgtype.Timestamptz `json:"generation_lease_expires_at"`
	GenerationHeartbeatAt    pgtype.Timestamptz `json:"generation_heartbeat_at"`
	GenerationAttempt        int32              `json:"generation_attempt"`
}

func (q *Queries) ClaimAIChatRunGeneration(ctx context.Context, arg ClaimAIChatRunGenerationParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, claimAIChatRunGeneration,
		arg.ID,
		arg.UserID,
		arg.GenerationOwner,
		arg.GenerationLeaseExpiresAt,
		arg.GenerationHeartbeatAt,
		arg.GenerationAttempt,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const consumeAIChatTrialPrompt = `-- name: ConsumeAIChatTrialPrompt :one
INSERT INTO ai_chat_trial_prompt_usage (
    user_id,
    stripe_subscription_id,
    prompt_count
)
VALUES ($1, $2, 1)
ON CONFLICT (user_id, stripe_subscription_id) DO UPDATE
SET prompt_count = ai_chat_trial_prompt_usage.prompt_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE ai_chat_trial_prompt_usage.prompt_count < $3
RETURNING user_id, stripe_subscription_id, prompt_count, created_at, updated_at
`

type ConsumeAIChatTrialPromptParams struct {
	UserID               string `json:"user_id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
	PromptCount          int32  `json:"prompt_count"`
}

func (q *Queries) ConsumeAIChatTrialPrompt(ctx context.Context, arg ConsumeAIChatTrialPromptParams) (AiChatTrialPromptUsage, error) {
	row := q.db.QueryRow(ctx, consumeAIChatTrialPrompt, arg.UserID, arg.StripeSubscriptionID, arg.PromptCount)
	var i AiChatTrialPromptUsage
	err := row.Scan(
		&i.UserID,
		&i.StripeSubscriptionID,
		&i.PromptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumeAIChatTrialPromptForCurrentSubscription = `-- name: ConsumeAIChatTrialPromptForCurrentSubscription :one
WITH current_subscription AS (
    SELECT stripe_subscription_id, status
    FROM stripe_subscriptions
    WHERE stripe_subscriptions.user_id = $1
    ORDER BY
        stripe_event_created_at DESC,
        updated_at DESC,
        created_at DESC
    LIMIT 1
),
trial_subscription AS (
    SELECT stripe_subscription_id
    FROM current_subscription
    WHERE status = 'trialing'
),
consumed AS (
    INSERT INTO ai_chat_trial_prompt_usage (
        user_id,
        stripe_subscription_id,
        prompt_count
    )
    SELECT $1, stripe_subscription_id, 1
    FROM trial_subscription
    WHERE $2::integer > 0
    ON CONFLICT (user_id, stripe_subscription_id) DO UPDATE
    SET prompt_count = ai_chat_trial_prompt_usage.prompt_count + 1,
        updated_at = CURRENT_TIMESTAMP
    WHERE ai_chat_trial_prompt_usage.prompt_count < $2::integer
    RETURNING 1
)
SELECT
    NOT EXISTS (SELECT 1 FROM trial_subscription)
    OR EXISTS (SELECT 1 FROM consumed) AS allowed
`

type ConsumeAIChatTrialPromptForCurrentSubscriptionParams struct {
	UserID    string `json:"user_id"`
	PromptCap int32  `json:"prompt_cap"`
}

func (q *Queries) ConsumeAIChatTrialPromptForCurrentSubscription(ctx context.Context, arg ConsumeAIChatTrialPromptForCurrentSubscriptionParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, consumeAIChatTrialPromptForCurrentSubscription, arg.UserID, arg.PromptCap)
	var allowed pgtype.Bool
	err := row.Scan(&allowed)
	return allowed, err
}

const createAIChatConversation = `-- name: CreateAIChatConversation :one
INSERT INTO ai_chat_conversation (
    user_id,
    title
)
VALUES ($1, $2)
RETURNING
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
`

type CreateAIChatConversationParams struct {
	UserID string      `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) CreateAIChatConversation(ctx context.Context, arg CreateAIChatConversationParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, createAIChatConversation, arg.UserID, arg.Title)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const createAIChatMessage = `-- name: CreateAIChatMessage :one
INSERT INTO ai_chat_message (
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type CreateAIChatMessageParams struct {
	ConversationID int32              `json:"conversation_id"`
	UserID         string             `json:"user_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Status         string             `json:"status"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateAIChatMessage(ctx context.Context, arg CreateAIChatMessageParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, createAIChatMessage,
		arg.ConversationID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.Status,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAIChatRun = `-- name: CreateAIChatRun :one
INSERT INTO ai_chat_run (
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type CreateAIChatRunParams struct {
	ConversationID     int32              `json:"conversation_id"`
	UserID             string             `json:"user_id"`
	UserMessageID      int32              `json:"user_message_id"`
	AssistantMessageID int32              `json:"assistant_message_id"`
	Model              string             `json:"model"`
	Status             string             `json:"status"`
	RequestID          pgtype.Text        `json:"request_id"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateAIChatRun(ctx context.Context, arg CreateAIChatRunParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, createAIChatRun,
		arg.ConversationID,
		arg.UserID,
		arg.UserMessageID,
		arg.AssistantMessageID,
		arg.Model,
		arg.Status,
		arg.RequestID,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAIChatStreamChunk = `-- name: CreateAIChatStreamChunk :one
INSERT INTO ai_chat_stream_chunk (
    run_id,
    user_id,
    sequence,
    delta_text
)
SELECT $1, $2, $3, $4
WHERE (
    NULLIF($5::text, '') IS NULL
    OR EXISTS (
        SELECT 1
        FROM ai_chat_run
        WHERE id = $1
          AND user_id = $2
          AND status = 'streaming'
          AND generation_status = 'generating'
          AND generation_owner = $5
    )
)
RETURNING
    run_id,
    user_id,
    sequence,
    delta_text,
    created_at
`

type CreateAIChatStreamChunkParams struct {
	RunID     int32  `json:"run_id"`
	UserID    string `json:"user_id"`
	Sequence  int32  `json:"sequence"`
	DeltaText string `json:"delta_text"`
	Column5   string `json:"column_5"`
}

func (q *Queries) CreateAIChatStreamChunk(ctx context.Context, arg CreateAIChatStreamChunkParams) (AiChatStreamChunk, error) {
	row := q.db.QueryRow(ctx, createAIChatStreamChunk,
		arg.RunID,
		arg.UserID,
		arg.Sequence,
		arg.DeltaText,
		arg.Column5,
	)
	var i AiChatStreamChunk
	err := row.Scan(
		&i.RunID,
		&i.UserID,
		&i.Sequence,
		&i.DeltaText,
		&i.CreatedAt,
	)
	return i, err
}

const createSet = `-- name: CreateSet :one
INSERT INTO "set" (exercise_id, workout_id, weight, reps, set_type, user_id, exercise_order, set_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateSetParams struct {
	ExerciseID    int32          `json:"exercise_id"`
	WorkoutID     int32          `json:"workout_id"`
	Weight        pgtype.Numeric `json:"weight"`
	Reps          int32          `json:"reps"`
	SetType       string         `json:"set_type"`
	UserID        string         `json:"user_id"`
	ExerciseOrder int32          `json:"exercise_order"`
	SetOrder      int32          `json:"set_order"`
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSet,
		arg.ExerciseID,
		arg.WorkoutID,
		arg.Weight,
		arg.Reps,
		arg.SetType,
		arg.UserID,
		arg.ExerciseOrder,
		arg.SetOrder,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workout (date, notes, workout_focus, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateWorkoutParams struct {
	Date         pgtype.Timestamptz `json:"date"`
	Notes        pgtype.Text        `json:"notes"`
	WorkoutFocus pgtype.Text        `json:"workout_focus"`
	UserID       string             `json:"user_id"`
}

// INSERT queries for form submission
func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (int32, error) {
	row := q.db.QueryRow(ctx, createWorkout,
		arg.Date,
		arg.Notes,
		arg.WorkoutFocus,
		arg.UserID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercise WHERE id = $1 AND user_id = $2
`

type DeleteExerciseParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteExercise(ctx context.Context, arg DeleteExerciseParams) error {
	_, err := q.db.Exec(ctx, deleteExercise, arg.ID, arg.UserID)
	return err
}

const deleteSetsByWorkout = `-- name: DeleteSetsByWorkout :exec
DELETE FROM "set" 
WHERE workout_id = $1 AND user_id = $2
`

type DeleteSetsByWorkoutParams struct {
	WorkoutID int32  `json:"workout_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteSetsByWorkout(ctx context.Context, arg DeleteSetsByWorkoutParams) error {
	_, err := q.db.Exec(ctx, deleteSetsByWorkout, arg.WorkoutID, arg.UserID)
	return err
}

const deleteSetsByWorkoutAndExercise = `-- name: DeleteSetsByWorkoutAndExercise :exec
DELETE FROM "set" 
WHERE workout_id = $1 
  AND exercise_id = $2
  AND user_id = $3
`

type DeleteSetsByWorkoutAndExerciseParams struct {
	WorkoutID  int32  `json:"workout_id"`
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) DeleteSetsByWorkoutAndExercise(ctx context.Context, arg DeleteSetsByWorkoutAndExerciseParams) error {
	_, err := q.db.Exec(ctx, deleteSetsByWorkoutAndExercise, arg.WorkoutID, arg.ExerciseID, arg.UserID)
	return err
}

const deleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workout 
WHERE id = $1 
  AND user_id = $2
`

type DeleteWorkoutParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) error {
	_, err := q.db.Exec(ctx, deleteWorkout, arg.ID, arg.UserID)
	return err
}

const getAIChatConversation = `-- name: GetAIChatConversation :one
SELECT
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
FROM ai_chat_conversation
WHERE id = $1 AND user_id = $2
`

type GetAIChatConversationParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatConversation(ctx context.Context, arg GetAIChatConversationParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, getAIChatConversation, arg.ID, arg.UserID)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getAIChatConversationForUpdate = `-- name: GetAIChatConversationForUpdate :one
SELECT
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
FROM ai_chat_conversation
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetAIChatConversationForUpdateParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatConversationForUpdate(ctx context.Context, arg GetAIChatConversationForUpdateParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, getAIChatConversationForUpdate, arg.ID, arg.UserID)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const getAIChatMessage = `-- name: GetAIChatMessage :one
SELECT
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
FROM ai_chat_message
WHERE id = $1 AND user_id = $2
`

type GetAIChatMessageParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatMessage(ctx context.Context, arg GetAIChatMessageParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, getAIChatMessage, arg.ID, arg.UserID)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAIChatRun = `-- name: GetAIChatRun :one
SELECT
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
FROM ai_chat_run
WHERE id = $1
  AND user_id = $2
`

type GetAIChatRunParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAIChatRun(ctx context.Context, arg GetAIChatRunParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, getAIChatRun, arg.ID, arg.UserID)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAIChatTrialPromptUsage = `-- name: GetAIChatTrialPromptUsage :one
SELECT user_id, stripe_subscription_id, prompt_count, created_at, updated_at
FROM ai_chat_trial_prompt_usage
WHERE user_id = $1
  AND stripe_subscription_id = $2
`

type GetAIChatTrialPromptUsageParams struct {
	UserID               string `json:"user_id"`
	StripeSubscriptionID string `json:"stripe_subscription_id"`
}

func (q *Queries) GetAIChatTrialPromptUsage(ctx context.Context, arg GetAIChatTrialPromptUsageParams) (AiChatTrialPromptUsage, error) {
	row := q.db.QueryRow(ctx, getAIChatTrialPromptUsage, arg.UserID, arg.StripeSubscriptionID)
	var i AiChatTrialPromptUsage
	err := row.Scan(
		&i.UserID,
		&i.StripeSubscriptionID,
		&i.PromptCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAIChatRunForConversation = `-- name: GetActiveAIChatRunForConversation :one
SELECT
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
FROM ai_chat_run
WHERE conversation_id = $1
  AND user_id = $2
  AND status = 'streaming'
ORDER BY id DESC
LIMIT 1
`

type GetActiveAIChatRunForConversationParams struct {
	ConversationID int32  `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetActiveAIChatRunForConversation(ctx context.Context, arg GetActiveAIChatRunForConversationParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, getActiveAIChatRunForConversation, arg.ConversationID, arg.UserID)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getContributionData = `-- name: GetContributionData :many
WITH workout_totals AS (
    SELECT
        w.id,
        w.date,
        w.workout_focus,
        COUNT(s.id) FILTER (WHERE s.set_type = 'working')::INTEGER AS working_set_count,
        COALESCE(
            SUM(
                CASE
                    WHEN s.set_type = 'working' THEN COALESCE(s.weight, 0)::NUMERIC * s.reps::NUMERIC
                    ELSE 0
                END
            ),
            0
        )::FLOAT8 AS volume
    FROM workout w
    LEFT JOIN "set" s ON s.workout_id = w.id
    WHERE w.user_id = $1
      AND w.date >= CURRENT_DATE - INTERVAL '52 weeks'
    GROUP BY w.id, w.date, w.workout_focus
)
SELECT
    DATE_TRUNC('day', wt.date)::DATE as date,
    SUM(wt.working_set_count)::INTEGER as count,
    JSON_AGG(JSONB_BUILD_OBJECT(
        'id', wt.id,
        'time', wt.date,
        'focus', wt.workout_focus,
        'volume', wt.volume
    ) ORDER BY wt.date, wt.id) as workouts
FROM workout_totals wt
GROUP BY DATE_TRUNC('day', wt.date)
ORDER BY date
`

type GetContributionDataRow struct {
	Date     pgtype.Date `json:"date"`
	Count    int32       `json:"count"`
	Workouts []byte      `json:"workouts"`
}

// Security: This query is protected by both application-level filtering and RLS policies.
// The WHERE clause filters by user_id (parameter $1), ensuring only the authenticated user's
// workouts are retrieved. RLS policies on the workout table provide defense-in-depth.
// The GROUP BY on date and JSON_AGG of workout metadata ensures no cross-user data leakage.
func (q *Queries) GetContributionData(ctx context.Context, userID string) ([]GetContributionDataRow, error) {
	rows, err := q.db.Query(ctx, getContributionData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContributionDataRow
	for rows.Next() {
		var i GetContributionDataRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Workouts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentStripeSubscriptionByUserID = `-- name: GetCurrentStripeSubscriptionByUserID :one
SELECT
    stripe_subscription_id,
    user_id,
    stripe_customer_id,
    stripe_price_id,
    stripe_event_created_at,
    status,
    cancel_at_period_end,
    current_period_start,
    current_period_end,
    trial_start,
    trial_end,
    created_at,
    updated_at
FROM stripe_subscriptions
WHERE user_id = $1
ORDER BY
    stripe_event_created_at DESC,
    updated_at DESC,
    created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentStripeSubscriptionByUserID(ctx context.Context, userID string) (StripeSubscriptions, error) {
	row := q.db.QueryRow(ctx, getCurrentStripeSubscriptionByUserID, userID)
	var i StripeSubscriptions
	err := row.Scan(
		&i.StripeSubscriptionID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripePriceID,
		&i.StripeEventCreatedAt,
		&i.Status,
		&i.CancelAtPeriodEnd,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialStart,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExercise = `-- name: GetExercise :one
SELECT id, name FROM exercise WHERE id = $1 AND user_id = $2
`

type GetExerciseParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type GetExerciseRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetExercise(ctx context.Context, arg GetExerciseParams) (GetExerciseRow, error) {
	row := q.db.QueryRow(ctx, getExercise, arg.ID, arg.UserID)
	var i GetExerciseRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getExerciseBestE1rmWithWorkout = `-- name: GetExerciseBestE1rmWithWorkout :one
WITH working AS (
    SELECT
        s.workout_id,
        w.date AS workout_date,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))::numeric(8,2) AS e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    WHERE s.user_id = $1
      AND s.exercise_id = $2
      AND s.set_type = 'working'
)
SELECT workout_id, e1rm
FROM working
ORDER BY e1rm DESC, workout_date DESC, workout_id DESC
LIMIT 1
`

type GetExerciseBestE1rmWithWorkoutParams struct {
	UserID     string `json:"user_id"`
	ExerciseID int32  `json:"exercise_id"`
}

type GetExerciseBestE1rmWithWorkoutRow struct {
	WorkoutID int32          `json:"workout_id"`
	E1rm      pgtype.Numeric `json:"e1rm"`
}

func (q *Queries) GetExerciseBestE1rmWithWorkout(ctx context.Context, arg GetExerciseBestE1rmWithWorkoutParams) (GetExerciseBestE1rmWithWorkoutRow, error) {
	row := q.db.QueryRow(ctx, getExerciseBestE1rmWithWorkout, arg.UserID, arg.ExerciseID)
	var i GetExerciseBestE1rmWithWorkoutRow
	err := row.Scan(&i.WorkoutID, &i.E1rm)
	return i, err
}

const getExerciseBestE1rmWithWorkoutExcludingWorkout = `-- name: GetExerciseBestE1rmWithWorkoutExcludingWorkout :one
WITH working AS (
    SELECT
        s.workout_id,
        w.date AS workout_date,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))::numeric(8,2) AS e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    WHERE s.user_id = $1
      AND s.exercise_id = $2
      AND s.workout_id <> $3
      AND s.set_type = 'working'
)
SELECT workout_id, e1rm
FROM working
ORDER BY e1rm DESC, workout_date DESC, workout_id DESC
LIMIT 1
`

type GetExerciseBestE1rmWithWorkoutExcludingWorkoutParams struct {
	UserID     string `json:"user_id"`
	ExerciseID int32  `json:"exercise_id"`
	WorkoutID  int32  `json:"workout_id"`
}

type GetExerciseBestE1rmWithWorkoutExcludingWorkoutRow struct {
	WorkoutID int32          `json:"workout_id"`
	E1rm      pgtype.Numeric `json:"e1rm"`
}

func (q *Queries) GetExerciseBestE1rmWithWorkoutExcludingWorkout(ctx context.Context, arg GetExerciseBestE1rmWithWorkoutExcludingWorkoutParams) (GetExerciseBestE1rmWithWorkoutExcludingWorkoutRow, error) {
	row := q.db.QueryRow(ctx, getExerciseBestE1rmWithWorkoutExcludingWorkout, arg.UserID, arg.ExerciseID, arg.WorkoutID)
	var i GetExerciseBestE1rmWithWorkoutExcludingWorkoutRow
	err := row.Scan(&i.WorkoutID, &i.E1rm)
	return i, err
}

const getExerciseByName = `-- name: GetExerciseByName :one
SELECT id, name FROM exercise WHERE name = $1 AND user_id = $2
`

type GetExerciseByNameParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

type GetExerciseByNameRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetExerciseByName(ctx context.Context, arg GetExerciseByNameParams) (GetExerciseByNameRow, error) {
	row := q.db.QueryRow(ctx, getExerciseByName, arg.Name, arg.UserID)
	var i GetExerciseByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getExerciseDetail = `-- name: GetExerciseDetail :one
SELECT
    e.id,
    e.name,
    e.created_at,
    e.updated_at,
    e.user_id,
    e.historical_1rm,
    e.historical_1rm_updated_at,
    e.historical_1rm_source_workout_id,
    (
        SELECT MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)))::numeric(8,2)
        FROM "set" s
        WHERE s.exercise_id = e.id
          AND s.user_id = e.user_id
          AND s.set_type = 'working'
    ) AS best_e1rm
FROM exercise e
WHERE e.id = $1 AND e.user_id = $2
`

type GetExerciseDetailParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type GetExerciseDetailRow struct {
	ID                           int32              `json:"id"`
	Name                         string             `json:"name"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	UserID                       string             `json:"user_id"`
	Historical1rm                pgtype.Numeric     `json:"historical_1rm"`
	Historical1rmUpdatedAt       pgtype.Timestamptz `json:"historical_1rm_updated_at"`
	Historical1rmSourceWorkoutID pgtype.Int4        `json:"historical_1rm_source_workout_id"`
	BestE1rm                     pgtype.Numeric     `json:"best_e1rm"`
}

func (q *Queries) GetExerciseDetail(ctx context.Context, arg GetExerciseDetailParams) (GetExerciseDetailRow, error) {
	row := q.db.QueryRow(ctx, getExerciseDetail, arg.ID, arg.UserID)
	var i GetExerciseDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Historical1rm,
		&i.Historical1rmUpdatedAt,
		&i.Historical1rmSourceWorkoutID,
		&i.BestE1rm,
	)
	return i, err
}

const getExerciseMetricsHistoryRaw6M = `-- name: GetExerciseMetricsHistoryRaw6M :many
WITH working_sets AS (
    SELECT
        w.id AS workout_id,
        w.date::date AS workout_day,
        COALESCE(s.weight, 0)::numeric AS weight,
        s.reps AS reps,
        (COALESCE(s.weight, 0)::numeric * s.reps::numeric) AS volume,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)) AS e1rm,
        e.historical_1rm AS historical_1rm,
        MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))) OVER (PARTITION BY w.id) AS session_best_e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    JOIN exercise e ON e.id = s.exercise_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
),
end_day AS (
    SELECT MAX(workout_day) AS end_day
    FROM working_sets
),
filtered AS (
    SELECT workout_id, workout_day, weight, reps, volume, e1rm, historical_1rm, session_best_e1rm, end_day
    FROM working_sets, end_day
    WHERE workout_day >= end_day - interval '6 months'
),
workout_metrics AS (
    SELECT
        workout_id,
        MIN(workout_day)::date AS workout_day,
        COALESCE(MAX(session_best_e1rm), 0)::float8 AS session_best_e1rm,
        COALESCE(AVG(e1rm), 0)::float8 AS session_avg_e1rm,
        COALESCE(AVG(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_avg_intensity,
        COALESCE(MAX(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_best_intensity,
        COALESCE(SUM(volume), 0)::float8 AS total_volume_working
    FROM filtered
    GROUP BY workout_id
)
SELECT workout_id, workout_day, session_best_e1rm, session_avg_e1rm, session_avg_intensity, session_best_intensity, total_volume_working
FROM workout_metrics
ORDER BY workout_day ASC, workout_id ASC
`

type GetExerciseMetricsHistoryRaw6MParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseMetricsHistoryRaw6MRow struct {
	WorkoutID            int32       `json:"workout_id"`
	WorkoutDay           pgtype.Date `json:"workout_day"`
	SessionBestE1rm      float64     `json:"session_best_e1rm"`
	SessionAvgE1rm       float64     `json:"session_avg_e1rm"`
	SessionAvgIntensity  float64     `json:"session_avg_intensity"`
	SessionBestIntensity float64     `json:"session_best_intensity"`
	TotalVolumeWorking   float64     `json:"total_volume_working"`
}

func (q *Queries) GetExerciseMetricsHistoryRaw6M(ctx context.Context, arg GetExerciseMetricsHistoryRaw6MParams) ([]GetExerciseMetricsHistoryRaw6MRow, error) {
	rows, err := q.db.Query(ctx, getExerciseMetricsHistoryRaw6M, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseMetricsHistoryRaw6MRow
	for rows.Next() {
		var i GetExerciseMetricsHistoryRaw6MRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDay,
			&i.SessionBestE1rm,
			&i.SessionAvgE1rm,
			&i.SessionAvgIntensity,
			&i.SessionBestIntensity,
			&i.TotalVolumeWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseMetricsHistoryRawMonth = `-- name: GetExerciseMetricsHistoryRawMonth :many
WITH working_sets AS (
    SELECT
        w.id AS workout_id,
        w.date::date AS workout_day,
        COALESCE(s.weight, 0)::numeric AS weight,
        s.reps AS reps,
        (COALESCE(s.weight, 0)::numeric * s.reps::numeric) AS volume,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)) AS e1rm,
        e.historical_1rm AS historical_1rm,
        MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))) OVER (PARTITION BY w.id) AS session_best_e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    JOIN exercise e ON e.id = s.exercise_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
),
end_day AS (
    SELECT MAX(workout_day) AS end_day
    FROM working_sets
),
filtered AS (
    SELECT workout_id, workout_day, weight, reps, volume, e1rm, historical_1rm, session_best_e1rm, end_day
    FROM working_sets, end_day
    WHERE workout_day >= end_day - interval '30 days'
),
workout_metrics AS (
    SELECT
        workout_id,
        MIN(workout_day)::date AS workout_day,
        COALESCE(MAX(session_best_e1rm), 0)::float8 AS session_best_e1rm,
        COALESCE(AVG(e1rm), 0)::float8 AS session_avg_e1rm,
        COALESCE(AVG(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_avg_intensity,
        COALESCE(MAX(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_best_intensity,
        COALESCE(SUM(volume), 0)::float8 AS total_volume_working
    FROM filtered
    GROUP BY workout_id
)
SELECT workout_id, workout_day, session_best_e1rm, session_avg_e1rm, session_avg_intensity, session_best_intensity, total_volume_working
FROM workout_metrics
ORDER BY workout_day ASC
`

type GetExerciseMetricsHistoryRawMonthParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseMetricsHistoryRawMonthRow struct {
	WorkoutID            int32       `json:"workout_id"`
	WorkoutDay           pgtype.Date `json:"workout_day"`
	SessionBestE1rm      float64     `json:"session_best_e1rm"`
	SessionAvgE1rm       float64     `json:"session_avg_e1rm"`
	SessionAvgIntensity  float64     `json:"session_avg_intensity"`
	SessionBestIntensity float64     `json:"session_best_intensity"`
	TotalVolumeWorking   float64     `json:"total_volume_working"`
}

func (q *Queries) GetExerciseMetricsHistoryRawMonth(ctx context.Context, arg GetExerciseMetricsHistoryRawMonthParams) ([]GetExerciseMetricsHistoryRawMonthRow, error) {
	rows, err := q.db.Query(ctx, getExerciseMetricsHistoryRawMonth, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseMetricsHistoryRawMonthRow
	for rows.Next() {
		var i GetExerciseMetricsHistoryRawMonthRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDay,
			&i.SessionBestE1rm,
			&i.SessionAvgE1rm,
			&i.SessionAvgIntensity,
			&i.SessionBestIntensity,
			&i.TotalVolumeWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseMetricsHistoryRawWeek = `-- name: GetExerciseMetricsHistoryRawWeek :many
WITH working_sets AS (
    SELECT
        w.id AS workout_id,
        w.date::date AS workout_day,
        COALESCE(s.weight, 0)::numeric AS weight,
        s.reps AS reps,
        (COALESCE(s.weight, 0)::numeric * s.reps::numeric) AS volume,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)) AS e1rm,
        e.historical_1rm AS historical_1rm,
        MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))) OVER (PARTITION BY w.id) AS session_best_e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    JOIN exercise e ON e.id = s.exercise_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
),
end_day AS (
    SELECT MAX(workout_day) AS end_day
    FROM working_sets
),
filtered AS (
    SELECT workout_id, workout_day, weight, reps, volume, e1rm, historical_1rm, session_best_e1rm, end_day
    FROM working_sets, end_day
    WHERE workout_day >= end_day - interval '7 days'
),
workout_metrics AS (
    SELECT
        workout_id,
        MIN(workout_day)::date AS workout_day,
        COALESCE(MAX(session_best_e1rm), 0)::float8 AS session_best_e1rm,
        COALESCE(AVG(e1rm), 0)::float8 AS session_avg_e1rm,
        COALESCE(AVG(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_avg_intensity,
        COALESCE(MAX(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_best_intensity,
        COALESCE(SUM(volume), 0)::float8 AS total_volume_working
    FROM filtered
    GROUP BY workout_id
)
SELECT workout_id, workout_day, session_best_e1rm, session_avg_e1rm, session_avg_intensity, session_best_intensity, total_volume_working
FROM workout_metrics
ORDER BY workout_day ASC
`

type GetExerciseMetricsHistoryRawWeekParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseMetricsHistoryRawWeekRow struct {
	WorkoutID            int32       `json:"workout_id"`
	WorkoutDay           pgtype.Date `json:"workout_day"`
	SessionBestE1rm      float64     `json:"session_best_e1rm"`
	SessionAvgE1rm       float64     `json:"session_avg_e1rm"`
	SessionAvgIntensity  float64     `json:"session_avg_intensity"`
	SessionBestIntensity float64     `json:"session_best_intensity"`
	TotalVolumeWorking   float64     `json:"total_volume_working"`
}

func (q *Queries) GetExerciseMetricsHistoryRawWeek(ctx context.Context, arg GetExerciseMetricsHistoryRawWeekParams) ([]GetExerciseMetricsHistoryRawWeekRow, error) {
	rows, err := q.db.Query(ctx, getExerciseMetricsHistoryRawWeek, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseMetricsHistoryRawWeekRow
	for rows.Next() {
		var i GetExerciseMetricsHistoryRawWeekRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDay,
			&i.SessionBestE1rm,
			&i.SessionAvgE1rm,
			&i.SessionAvgIntensity,
			&i.SessionBestIntensity,
			&i.TotalVolumeWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseMetricsHistoryRawYear = `-- name: GetExerciseMetricsHistoryRawYear :many
WITH working_sets AS (
    SELECT
        w.id AS workout_id,
        w.date::date AS workout_day,
        COALESCE(s.weight, 0)::numeric AS weight,
        s.reps AS reps,
        (COALESCE(s.weight, 0)::numeric * s.reps::numeric) AS volume,
        (COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)) AS e1rm,
        e.historical_1rm AS historical_1rm,
        MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30))) OVER (PARTITION BY w.id) AS session_best_e1rm
    FROM "set" s
    JOIN workout w ON w.id = s.workout_id
    JOIN exercise e ON e.id = s.exercise_id
    WHERE s.exercise_id = $1
      AND s.user_id = $2
      AND s.set_type = 'working'
),
end_day AS (
    SELECT MAX(workout_day) AS end_day
    FROM working_sets
),
filtered AS (
    SELECT workout_id, workout_day, weight, reps, volume, e1rm, historical_1rm, session_best_e1rm, end_day
    FROM working_sets, end_day
    WHERE workout_day >= end_day - interval '1 year'
),
workout_metrics AS (
    SELECT
        workout_id,
        MIN(workout_day)::date AS workout_day,
        COALESCE(MAX(session_best_e1rm), 0)::float8 AS session_best_e1rm,
        COALESCE(AVG(e1rm), 0)::float8 AS session_avg_e1rm,
        COALESCE(AVG(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_avg_intensity,
        COALESCE(MAX(
            CASE
                WHEN (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) > 0
                THEN (weight / (CASE WHEN historical_1rm > 0 THEN historical_1rm ELSE session_best_e1rm END) * 100)
            END
        ), 0)::float8 AS session_best_intensity,
        COALESCE(SUM(volume), 0)::float8 AS total_volume_working
    FROM filtered
    GROUP BY workout_id
)
SELECT workout_id, workout_day, session_best_e1rm, session_avg_e1rm, session_avg_intensity, session_best_intensity, total_volume_working
FROM workout_metrics
ORDER BY workout_day ASC, workout_id ASC
`

type GetExerciseMetricsHistoryRawYearParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseMetricsHistoryRawYearRow struct {
	WorkoutID            int32       `json:"workout_id"`
	WorkoutDay           pgtype.Date `json:"workout_day"`
	SessionBestE1rm      float64     `json:"session_best_e1rm"`
	SessionAvgE1rm       float64     `json:"session_avg_e1rm"`
	SessionAvgIntensity  float64     `json:"session_avg_intensity"`
	SessionBestIntensity float64     `json:"session_best_intensity"`
	TotalVolumeWorking   float64     `json:"total_volume_working"`
}

func (q *Queries) GetExerciseMetricsHistoryRawYear(ctx context.Context, arg GetExerciseMetricsHistoryRawYearParams) ([]GetExerciseMetricsHistoryRawYearRow, error) {
	rows, err := q.db.Query(ctx, getExerciseMetricsHistoryRawYear, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseMetricsHistoryRawYearRow
	for rows.Next() {
		var i GetExerciseMetricsHistoryRawYearRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDay,
			&i.SessionBestE1rm,
			&i.SessionAvgE1rm,
			&i.SessionAvgIntensity,
			&i.SessionBestIntensity,
			&i.TotalVolumeWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseWithSets = `-- name: GetExerciseWithSets :many
SELECT 
    s.workout_id,
    w.date as workout_date,
    w.notes as workout_notes,
    w.workout_focus as workout_focus,
    s.id as set_id,
    s.weight,
    s.reps,
    s.set_type,
    e.id as exercise_id,
    e.name as exercise_name,
    s.exercise_order,
    s.set_order,
    (COALESCE(s.weight, 0) * s.reps)::NUMERIC(10,1) as volume
FROM "set" s
JOIN exercise e ON e.id = s.exercise_id
JOIN workout w ON w.id = s.workout_id
WHERE s.exercise_id = $1 AND s.user_id = $2
ORDER BY w.date DESC, s.exercise_order, s.set_order, s.created_at, s.id
`

type GetExerciseWithSetsParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetExerciseWithSetsRow struct {
	WorkoutID     int32              `json:"workout_id"`
	WorkoutDate   pgtype.Timestamptz `json:"workout_date"`
	WorkoutNotes  pgtype.Text        `json:"workout_notes"`
	WorkoutFocus  pgtype.Text        `json:"workout_focus"`
	SetID         int32              `json:"set_id"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	SetType       string             `json:"set_type"`
	ExerciseID    int32              `json:"exercise_id"`
	ExerciseName  string             `json:"exercise_name"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
	Volume        pgtype.Numeric     `json:"volume"`
}

func (q *Queries) GetExerciseWithSets(ctx context.Context, arg GetExerciseWithSetsParams) ([]GetExerciseWithSetsRow, error) {
	rows, err := q.db.Query(ctx, getExerciseWithSets, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseWithSetsRow
	for rows.Next() {
		var i GetExerciseWithSetsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.WorkoutNotes,
			&i.WorkoutFocus,
			&i.SetID,
			&i.Weight,
			&i.Reps,
			&i.SetType,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.ExerciseOrder,
			&i.SetOrder,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAIChatStreamChunkSequence = `-- name: GetLatestAIChatStreamChunkSequence :one
SELECT COALESCE(MAX(sequence), 0)::INTEGER
FROM ai_chat_stream_chunk
WHERE run_id = $1
  AND user_id = $2
`

type GetLatestAIChatStreamChunkSequenceParams struct {
	RunID  int32  `json:"run_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetLatestAIChatStreamChunkSequence(ctx context.Context, arg GetLatestAIChatStreamChunkSequenceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestAIChatStreamChunkSequence, arg.RunID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getLatestWorkoutNote = `-- name: GetLatestWorkoutNote :one
SELECT id AS workout_id, date, notes
FROM workout
WHERE user_id = $1
  AND notes IS NOT NULL
  AND BTRIM(notes) <> ''
ORDER BY date DESC, id DESC
LIMIT 1
`

type GetLatestWorkoutNoteRow struct {
	WorkoutID int32              `json:"workout_id"`
	Date      pgtype.Timestamptz `json:"date"`
	Notes     pgtype.Text        `json:"notes"`
}

func (q *Queries) GetLatestWorkoutNote(ctx context.Context, userID string) (GetLatestWorkoutNoteRow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkoutNote, userID)
	var i GetLatestWorkoutNoteRow
	err := row.Scan(&i.WorkoutID, &i.Date, &i.Notes)
	return i, err
}

const getOrCreateExercise = `-- name: GetOrCreateExercise :one
INSERT INTO exercise (name, user_id)
VALUES ($1, $2)
ON CONFLICT (user_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type GetOrCreateExerciseParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetOrCreateExercise(ctx context.Context, arg GetOrCreateExerciseParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateExercise, arg.Name, arg.UserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRecentSetsForExercise = `-- name: GetRecentSetsForExercise :many
SELECT
    s.id AS set_id,
    w.id AS workout_id,
    w.date AS workout_date,
    w.workout_focus AS workout_focus,
    s.weight,
    s.reps,
    s.exercise_order,
    s.set_order,
    s.created_at
FROM "set" s
JOIN workout w ON w.id = s.workout_id
WHERE s.exercise_id = $1 AND s.user_id = $2
ORDER BY w.date DESC, s.set_order DESC
LIMIT 3
`

type GetRecentSetsForExerciseParams struct {
	ExerciseID int32  `json:"exercise_id"`
	UserID     string `json:"user_id"`
}

type GetRecentSetsForExerciseRow struct {
	SetID         int32              `json:"set_id"`
	WorkoutID     int32              `json:"workout_id"`
	WorkoutDate   pgtype.Timestamptz `json:"workout_date"`
	WorkoutFocus  pgtype.Text        `json:"workout_focus"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentSetsForExercise(ctx context.Context, arg GetRecentSetsForExerciseParams) ([]GetRecentSetsForExerciseRow, error) {
	rows, err := q.db.Query(ctx, getRecentSetsForExercise, arg.ExerciseID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentSetsForExerciseRow
	for rows.Next() {
		var i GetRecentSetsForExerciseRow
		if err := rows.Scan(
			&i.SetID,
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.WorkoutFocus,
			&i.Weight,
			&i.Reps,
			&i.ExerciseOrder,
			&i.SetOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSet = `-- name: GetSet :one
SELECT id, exercise_id, workout_id, weight, reps, set_type, created_at, updated_at, exercise_order, set_order FROM "set"
WHERE id = $1 AND user_id = $2
`

type GetSetParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type GetSetRow struct {
	ID            int32              `json:"id"`
	ExerciseID    int32              `json:"exercise_id"`
	WorkoutID     int32              `json:"workout_id"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	SetType       string             `json:"set_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
}

func (q *Queries) GetSet(ctx context.Context, arg GetSetParams) (GetSetRow, error) {
	row := q.db.QueryRow(ctx, getSet, arg.ID, arg.UserID)
	var i GetSetRow
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.WorkoutID,
		&i.Weight,
		&i.Reps,
		&i.SetType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExerciseOrder,
		&i.SetOrder,
	)
	return i, err
}

const getStripeCustomerByCustomerID = `-- name: GetStripeCustomerByCustomerID :one
SELECT user_id, stripe_customer_id, created_at, updated_at
FROM stripe_customers
WHERE stripe_customer_id = $1
`

func (q *Queries) GetStripeCustomerByCustomerID(ctx context.Context, stripeCustomerID string) (StripeCustomers, error) {
	row := q.db.QueryRow(ctx, getStripeCustomerByCustomerID, stripeCustomerID)
	var i StripeCustomers
	err := row.Scan(
		&i.UserID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStripeCustomerByUserID = `-- name: GetStripeCustomerByUserID :one
SELECT user_id, stripe_customer_id, created_at, updated_at
FROM stripe_customers
WHERE user_id = $1
`

// Billing queries
func (q *Queries) GetStripeCustomerByUserID(ctx context.Context, userID string) (StripeCustomers, error) {
	row := q.db.QueryRow(ctx, getStripeCustomerByUserID, userID)
	var i StripeCustomers
	err := row.Scan(
		&i.UserID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, user_id, created_at FROM users WHERE id = $1
`

// User queries
func (q *Queries) GetUser(ctx context.Context, id int32) (Users, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i Users
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, created_at FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, userID)
	var i Users
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getWorkout = `-- name: GetWorkout :one
SELECT id, date, notes, workout_focus, created_at, updated_at FROM workout WHERE id = $1 AND user_id = $2
`

type GetWorkoutParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type GetWorkoutRow struct {
	ID           int32              `json:"id"`
	Date         pgtype.Timestamptz `json:"date"`
	Notes        pgtype.Text        `json:"notes"`
	WorkoutFocus pgtype.Text        `json:"workout_focus"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Basic SELECT queries
func (q *Queries) GetWorkout(ctx context.Context, arg GetWorkoutParams) (GetWorkoutRow, error) {
	row := q.db.QueryRow(ctx, getWorkout, arg.ID, arg.UserID)
	var i GetWorkoutRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Notes,
		&i.WorkoutFocus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkoutBestE1rmByExercise = `-- name: GetWorkoutBestE1rmByExercise :many
SELECT
    s.exercise_id,
    MAX((COALESCE(s.weight, 0)::numeric * (1 + s.reps::numeric / 30)))::numeric(8,2) AS best_e1rm
FROM "set" s
WHERE s.workout_id = $1
  AND s.user_id = $2
  AND s.set_type = 'working'
GROUP BY s.exercise_id
`

type GetWorkoutBestE1rmByExerciseParams struct {
	WorkoutID int32  `json:"workout_id"`
	UserID    string `json:"user_id"`
}

type GetWorkoutBestE1rmByExerciseRow struct {
	ExerciseID int32          `json:"exercise_id"`
	BestE1rm   pgtype.Numeric `json:"best_e1rm"`
}

func (q *Queries) GetWorkoutBestE1rmByExercise(ctx context.Context, arg GetWorkoutBestE1rmByExerciseParams) ([]GetWorkoutBestE1rmByExerciseRow, error) {
	rows, err := q.db.Query(ctx, getWorkoutBestE1rmByExercise, arg.WorkoutID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkoutBestE1rmByExerciseRow
	for rows.Next() {
		var i GetWorkoutBestE1rmByExerciseRow
		if err := rows.Scan(&i.ExerciseID, &i.BestE1rm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutWithSets = `-- name: GetWorkoutWithSets :many
SELECT 
    w.id as workout_id,
    w.date as workout_date,
    w.notes as workout_notes,
    w.workout_focus as workout_focus,
    s.id as set_id,
    s.weight,
    s.reps,
    s.set_type,
    e.id as exercise_id,
    e.name as exercise_name,
    s.exercise_order,
    s.set_order,
    (COALESCE(s.weight, 0) * s.reps)::NUMERIC(10,1) as volume
FROM workout w
JOIN "set" s ON w.id = s.workout_id
JOIN exercise e ON s.exercise_id = e.id
WHERE w.id = $1 AND w.user_id = $2
ORDER BY s.exercise_order, s.set_order, s.id
`

type GetWorkoutWithSetsParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

type GetWorkoutWithSetsRow struct {
	WorkoutID     int32              `json:"workout_id"`
	WorkoutDate   pgtype.Timestamptz `json:"workout_date"`
	WorkoutNotes  pgtype.Text        `json:"workout_notes"`
	WorkoutFocus  pgtype.Text        `json:"workout_focus"`
	SetID         int32              `json:"set_id"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	SetType       string             `json:"set_type"`
	ExerciseID    int32              `json:"exercise_id"`
	ExerciseName  string             `json:"exercise_name"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
	Volume        pgtype.Numeric     `json:"volume"`
}

// Complex queries for joining data
func (q *Queries) GetWorkoutWithSets(ctx context.Context, arg GetWorkoutWithSetsParams) ([]GetWorkoutWithSetsRow, error) {
	rows, err := q.db.Query(ctx, getWorkoutWithSets, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkoutWithSetsRow
	for rows.Next() {
		var i GetWorkoutWithSetsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutDate,
			&i.WorkoutNotes,
			&i.WorkoutFocus,
			&i.SetID,
			&i.Weight,
			&i.Reps,
			&i.SetType,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.ExerciseOrder,
			&i.SetOrder,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantStripeFeatureAccess = `-- name: GrantStripeFeatureAccess :exec
INSERT INTO user_feature_access (
    user_id,
    feature_key,
    source,
    source_reference,
    granted_by,
    note,
    starts_at,
    expires_at
)
VALUES ($1, $2, 'stripe', $3, 'stripe_webhook', $4, CURRENT_TIMESTAMP, $5)
`

type GrantStripeFeatureAccessParams struct {
	UserID          string             `json:"user_id"`
	FeatureKey      string             `json:"feature_key"`
	SourceReference pgtype.Text        `json:"source_reference"`
	Note            pgtype.Text        `json:"note"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GrantStripeFeatureAccess(ctx context.Context, arg GrantStripeFeatureAccessParams) error {
	_, err := q.db.Exec(ctx, grantStripeFeatureAccess,
		arg.UserID,
		arg.FeatureKey,
		arg.SourceReference,
		arg.Note,
		arg.ExpiresAt,
	)
	return err
}

const hasActiveFeatureAccess = `-- name: HasActiveFeatureAccess :one
SELECT EXISTS (
    SELECT 1
    FROM user_feature_access
    WHERE user_id = $1
      AND feature_key = $2
      AND revoked_at IS NULL
      AND starts_at <= NOW()
      AND (expires_at IS NULL OR expires_at > NOW())
)
`

type HasActiveFeatureAccessParams struct {
	UserID     string `json:"user_id"`
	FeatureKey string `json:"feature_key"`
}

func (q *Queries) HasActiveFeatureAccess(ctx context.Context, arg HasActiveFeatureAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveFeatureAccess, arg.UserID, arg.FeatureKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasProcessedStripeWebhookEvent = `-- name: HasProcessedStripeWebhookEvent :one
SELECT EXISTS (
    SELECT 1
    FROM stripe_webhook_events
    WHERE stripe_event_id = $1
)
`

func (q *Queries) HasProcessedStripeWebhookEvent(ctx context.Context, stripeEventID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasProcessedStripeWebhookEvent, stripeEventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const heartbeatAIChatRunGeneration = `-- name: HeartbeatAIChatRunGeneration :execrows
UPDATE ai_chat_run
SET generation_lease_expires_at = $3,
    generation_heartbeat_at = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND generation_status = 'generating'
  AND generation_owner = $5
`

type HeartbeatAIChatRunGenerationParams struct {
	ID                       int32              `json:"id"`
	UserID                   string             `json:"user_id"`
	GenerationLeaseExpiresAt pgtype.Timestamptz `json:"generation_lease_expires_at"`
	GenerationHeartbeatAt    pgtype.Timestamptz `json:"generation_heartbeat_at"`
	GenerationOwner          pgtype.Text        `json:"generation_owner"`
}

func (q *Queries) HeartbeatAIChatRunGeneration(ctx context.Context, arg HeartbeatAIChatRunGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatAIChatRunGeneration,
		arg.ID,
		arg.UserID,
		arg.GenerationLeaseExpiresAt,
		arg.GenerationHeartbeatAt,
		arg.GenerationOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAIChatMessagesByConversation = `-- name: ListAIChatMessagesByConversation :many
SELECT
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
FROM ai_chat_message
WHERE conversation_id = $1 AND user_id = $2
ORDER BY id ASC
`

type ListAIChatMessagesByConversationParams struct {
	ConversationID int32  `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) ListAIChatMessagesByConversation(ctx context.Context, arg ListAIChatMessagesByConversationParams) ([]AiChatMessage, error) {
	rows, err := q.db.Query(ctx, listAIChatMessagesByConversation, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiChatMessage
	for rows.Next() {
		var i AiChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIChatStreamChunksAfter = `-- name: ListAIChatStreamChunksAfter :many
SELECT
    run_id,
    user_id,
    sequence,
    delta_text,
    created_at
FROM ai_chat_stream_chunk
WHERE run_id = $1
  AND user_id = $2
  AND sequence > $3
ORDER BY sequence ASC
`

type ListAIChatStreamChunksAfterParams struct {
	RunID    int32  `json:"run_id"`
	UserID   string `json:"user_id"`
	Sequence int32  `json:"sequence"`
}

func (q *Queries) ListAIChatStreamChunksAfter(ctx context.Context, arg ListAIChatStreamChunksAfterParams) ([]AiChatStreamChunk, error) {
	rows, err := q.db.Query(ctx, listAIChatStreamChunksAfter, arg.RunID, arg.UserID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiChatStreamChunk
	for rows.Next() {
		var i AiChatStreamChunk
		if err := rows.Scan(
			&i.RunID,
			&i.UserID,
			&i.Sequence,
			&i.DeltaText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveFeatureAccess = `-- name: ListActiveFeatureAccess :many
SELECT
    id,
    user_id,
    feature_key,
    source,
    source_reference,
    granted_by,
    note,
    starts_at,
    expires_at,
    revoked_at,
    created_at
FROM user_feature_access
WHERE user_id = $1
  AND revoked_at IS NULL
  AND starts_at <= NOW()
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY feature_key, starts_at DESC, id DESC
`

// Feature access queries
func (q *Queries) ListActiveFeatureAccess(ctx context.Context, userID string) ([]UserFeatureAccess, error) {
	rows, err := q.db.Query(ctx, listActiveFeatureAccess, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFeatureAccess
	for rows.Next() {
		var i UserFeatureAccess
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeatureKey,
			&i.Source,
			&i.SourceReference,
			&i.GrantedBy,
			&i.Note,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercises = `-- name: ListExercises :many
SELECT id, name FROM exercise WHERE user_id = $1 ORDER BY name
`

type ListExercisesRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListExercises(ctx context.Context, userID string) ([]ListExercisesRow, error) {
	rows, err := q.db.Query(ctx, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesRow
	for rows.Next() {
		var i ListExercisesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExercisesWithHistorical1RMSourceWorkout = `-- name: ListExercisesWithHistorical1RMSourceWorkout :many
SELECT id
FROM exercise
WHERE user_id = $1 AND historical_1rm_source_workout_id = $2
`

type ListExercisesWithHistorical1RMSourceWorkoutParams struct {
	UserID                       string      `json:"user_id"`
	Historical1rmSourceWorkoutID pgtype.Int4 `json:"historical_1rm_source_workout_id"`
}

func (q *Queries) ListExercisesWithHistorical1RMSourceWorkout(ctx context.Context, arg ListExercisesWithHistorical1RMSourceWorkoutParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listExercisesWithHistorical1RMSourceWorkout, arg.UserID, arg.Historical1rmSourceWorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSets = `-- name: ListSets :many
SELECT id, exercise_id, workout_id, weight, reps, set_type, created_at, updated_at, exercise_order, set_order FROM "set"
WHERE user_id = $1
ORDER BY exercise_order, set_order, id
`

type ListSetsRow struct {
	ID            int32              `json:"id"`
	ExerciseID    int32              `json:"exercise_id"`
	WorkoutID     int32              `json:"workout_id"`
	Weight        pgtype.Numeric     `json:"weight"`
	Reps          int32              `json:"reps"`
	SetType       string             `json:"set_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ExerciseOrder int32              `json:"exercise_order"`
	SetOrder      int32              `json:"set_order"`
}

func (q *Queries) ListSets(ctx context.Context, userID string) ([]ListSetsRow, error) {
	rows, err := q.db.Query(ctx, listSets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSetsRow
	for rows.Next() {
		var i ListSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.WorkoutID,
			&i.Weight,
			&i.Reps,
			&i.SetType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExerciseOrder,
			&i.SetOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutFocusTemplates = `-- name: ListWorkoutFocusTemplates :many
WITH ranked_focus_workouts AS (
    SELECT
        id AS workout_id,
        date,
        BTRIM(workout_focus)::VARCHAR(256) AS workout_focus,
        ROW_NUMBER() OVER (
            PARTITION BY LOWER(BTRIM(workout_focus))
            ORDER BY date DESC, id DESC
        ) AS rank
    FROM workout
    WHERE user_id = $1
      AND workout_focus IS NOT NULL
      AND BTRIM(workout_focus) <> ''
)
SELECT workout_id, date, workout_focus
FROM ranked_focus_workouts
WHERE rank = 1
ORDER BY date DESC, workout_id DESC
`

type ListWorkoutFocusTemplatesRow struct {
	WorkoutID    int32              `json:"workout_id"`
	Date         pgtype.Timestamptz `json:"date"`
	WorkoutFocus string             `json:"workout_focus"`
}

func (q *Queries) ListWorkoutFocusTemplates(ctx context.Context, userID string) ([]ListWorkoutFocusTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listWorkoutFocusTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutFocusTemplatesRow
	for rows.Next() {
		var i ListWorkoutFocusTemplatesRow
		if err := rows.Scan(&i.WorkoutID, &i.Date, &i.WorkoutFocus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutFocusValues = `-- name: ListWorkoutFocusValues :many
SELECT DISTINCT workout_focus
FROM workout
WHERE user_id = $1
  AND workout_focus IS NOT NULL
ORDER BY workout_focus
`

func (q *Queries) ListWorkoutFocusValues(ctx context.Context, userID string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listWorkoutFocusValues, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var workout_focus pgtype.Text
		if err := rows.Scan(&workout_focus); err != nil {
			return nil, err
		}
		items = append(items, workout_focus)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkouts = `-- name: ListWorkouts :many
SELECT id, date, notes, workout_focus, created_at, updated_at FROM workout WHERE user_id = $1 ORDER BY date DESC
`

type ListWorkoutsRow struct {
	ID           int32              `json:"id"`
	Date         pgtype.Timestamptz `json:"date"`
	Notes        pgtype.Text        `json:"notes"`
	WorkoutFocus pgtype.Text        `json:"workout_focus"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkouts(ctx context.Context, userID string) ([]ListWorkoutsRow, error) {
	rows, err := q.db.Query(ctx, listWorkouts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkoutsRow
	for rows.Next() {
		var i ListWorkoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Notes,
			&i.WorkoutFocus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAIChatConversationLatestWorkoutDraftSaved = `-- name: MarkAIChatConversationLatestWorkoutDraftSaved :one
UPDATE ai_chat_conversation
SET latest_workout_draft_saved_workout_id = $4,
    latest_workout_draft_saved_at = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND latest_workout_draft IS NOT NULL
  AND (
    latest_workout_draft_source_run_id = $3
    OR ($3::integer IS NULL AND latest_workout_draft_source_run_id IS NULL)
  )
RETURNING
    id,
    user_id,
    title,
    latest_workout_draft,
    latest_workout_draft_source_run_id,
    latest_workout_draft_saved_workout_id,
    latest_workout_draft_saved_at,
    created_at,
    updated_at,
    last_message_at
`

type MarkAIChatConversationLatestWorkoutDraftSavedParams struct {
	ID                               int32              `json:"id"`
	UserID                           string             `json:"user_id"`
	LatestWorkoutDraftSourceRunID    pgtype.Int4        `json:"latest_workout_draft_source_run_id"`
	LatestWorkoutDraftSavedWorkoutID pgtype.Int4        `json:"latest_workout_draft_saved_workout_id"`
	LatestWorkoutDraftSavedAt        pgtype.Timestamptz `json:"latest_workout_draft_saved_at"`
}

func (q *Queries) MarkAIChatConversationLatestWorkoutDraftSaved(ctx context.Context, arg MarkAIChatConversationLatestWorkoutDraftSavedParams) (AiChatConversation, error) {
	row := q.db.QueryRow(ctx, markAIChatConversationLatestWorkoutDraftSaved,
		arg.ID,
		arg.UserID,
		arg.LatestWorkoutDraftSourceRunID,
		arg.LatestWorkoutDraftSavedWorkoutID,
		arg.LatestWorkoutDraftSavedAt,
	)
	var i AiChatConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.LatestWorkoutDraft,
		&i.LatestWorkoutDraftSourceRunID,
		&i.LatestWorkoutDraftSavedWorkoutID,
		&i.LatestWorkoutDraftSavedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const markStripeWebhookEventProcessed = `-- name: MarkStripeWebhookEventProcessed :exec
INSERT INTO stripe_webhook_events (
    stripe_event_id,
    event_type
)
VALUES ($1, $2)
ON CONFLICT (stripe_event_id) DO NOTHING
`

type MarkStripeWebhookEventProcessedParams struct {
	StripeEventID string `json:"stripe_event_id"`
	EventType     string `json:"event_type"`
}

func (q *Queries) MarkStripeWebhookEventProcessed(ctx context.Context, arg MarkStripeWebhookEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markStripeWebhookEventProcessed, arg.StripeEventID, arg.EventType)
	return err
}

const revokeStripeFeatureAccess = `-- name: RevokeStripeFeatureAccess :exec
UPDATE user_feature_access
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND feature_key = $2
  AND source = 'stripe'
  AND source_reference = $3
  AND revoked_at IS NULL
`

type RevokeStripeFeatureAccessParams struct {
	UserID          string      `json:"user_id"`
	FeatureKey      string      `json:"feature_key"`
	SourceReference pgtype.Text `json:"source_reference"`
}

func (q *Queries) RevokeStripeFeatureAccess(ctx context.Context, arg RevokeStripeFeatureAccessParams) error {
	_, err := q.db.Exec(ctx, revokeStripeFeatureAccess, arg.UserID, arg.FeatureKey, arg.SourceReference)
	return err
}

const setAIChatConversationLatestWorkoutDraft = `-- name: SetAIChatConversationLatestWorkoutDraft :exec
UPDATE ai_chat_conversation
SET latest_workout_draft = NULLIF($3::text, '')::jsonb,
    latest_workout_draft_source_run_id = $4,
    latest_workout_draft_saved_workout_id = NULL,
    latest_workout_draft_saved_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type SetAIChatConversationLatestWorkoutDraftParams struct {
	ID                            int32       `json:"id"`
	UserID                        string      `json:"user_id"`
	Column3                       string      `json:"column_3"`
	LatestWorkoutDraftSourceRunID pgtype.Int4 `json:"latest_workout_draft_source_run_id"`
}

func (q *Queries) SetAIChatConversationLatestWorkoutDraft(ctx context.Context, arg SetAIChatConversationLatestWorkoutDraftParams) error {
	_, err := q.db.Exec(ctx, setAIChatConversationLatestWorkoutDraft,
		arg.ID,
		arg.UserID,
		arg.Column3,
		arg.LatestWorkoutDraftSourceRunID,
	)
	return err
}

const setAIChatConversationTitleIfEmpty = `-- name: SetAIChatConversationTitleIfEmpty :execrows
UPDATE ai_chat_conversation
SET title = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND title IS NULL
  AND $3::text IS NOT NULL
  AND btrim($3::text) <> ''
`

type SetAIChatConversationTitleIfEmptyParams struct {
	ID     int32       `json:"id"`
	UserID string      `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) SetAIChatConversationTitleIfEmpty(ctx context.Context, arg SetAIChatConversationTitleIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAIChatConversationTitleIfEmpty, arg.ID, arg.UserID, arg.Title)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setExerciseHistorical1RM = `-- name: SetExerciseHistorical1RM :exec
UPDATE exercise
SET
    historical_1rm = $2,
    historical_1rm_updated_at = NOW(),
    historical_1rm_source_workout_id = $3,
    updated_at = NOW()
WHERE id = $1 AND user_id = $4
`

type SetExerciseHistorical1RMParams struct {
	ID                           int32          `json:"id"`
	Historical1rm                pgtype.Numeric `json:"historical_1rm"`
	Historical1rmSourceWorkoutID pgtype.Int4    `json:"historical_1rm_source_workout_id"`
	UserID                       string         `json:"user_id"`
}

func (q *Queries) SetExerciseHistorical1RM(ctx context.Context, arg SetExerciseHistorical1RMParams) error {
	_, err := q.db.Exec(ctx, setExerciseHistorical1RM,
		arg.ID,
		arg.Historical1rm,
		arg.Historical1rmSourceWorkoutID,
		arg.UserID,
	)
	return err
}

const touchAIChatConversation = `-- name: TouchAIChatConversation :exec
UPDATE ai_chat_conversation
SET updated_at = CURRENT_TIMESTAMP,
    last_message_at = $3
WHERE id = $1 AND user_id = $2
`

type TouchAIChatConversationParams struct {
	ID            int32              `json:"id"`
	UserID        string             `json:"user_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

func (q *Queries) TouchAIChatConversation(ctx context.Context, arg TouchAIChatConversationParams) error {
	_, err := q.db.Exec(ctx, touchAIChatConversation, arg.ID, arg.UserID, arg.LastMessageAt)
	return err
}

const touchAIChatRun = `-- name: TouchAIChatRun :exec
UPDATE ai_chat_run
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
`

type TouchAIChatRunParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) TouchAIChatRun(ctx context.Context, arg TouchAIChatRunParams) error {
	_, err := q.db.Exec(ctx, touchAIChatRun, arg.ID, arg.UserID)
	return err
}

const updateAIChatMessageCompleted = `-- name: UpdateAIChatMessageCompleted :one
UPDATE ai_chat_message
SET content = $3,
    status = 'completed',
    error_message = NULL,
    completed_at = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type UpdateAIChatMessageCompletedParams struct {
	ID          int32              `json:"id"`
	UserID      string             `json:"user_id"`
	Content     string             `json:"content"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAIChatMessageCompleted(ctx context.Context, arg UpdateAIChatMessageCompletedParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, updateAIChatMessageCompleted,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.CompletedAt,
	)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatMessageFailed = `-- name: UpdateAIChatMessageFailed :one
UPDATE ai_chat_message
SET content = $3,
    status = 'failed',
    error_message = $4,
    completed_at = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type UpdateAIChatMessageFailedParams struct {
	ID           int32              `json:"id"`
	UserID       string             `json:"user_id"`
	Content      string             `json:"content"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAIChatMessageFailed(ctx context.Context, arg UpdateAIChatMessageFailedParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, updateAIChatMessageFailed,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatMessageStreaming = `-- name: UpdateAIChatMessageStreaming :one
UPDATE ai_chat_message
SET content = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
RETURNING
    id,
    conversation_id,
    user_id,
    role,
    content,
    status,
    error_message,
    created_at,
    updated_at,
    completed_at
`

type UpdateAIChatMessageStreamingParams struct {
	ID      int32  `json:"id"`
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateAIChatMessageStreaming(ctx context.Context, arg UpdateAIChatMessageStreamingParams) (AiChatMessage, error) {
	row := q.db.QueryRow(ctx, updateAIChatMessageStreaming, arg.ID, arg.UserID, arg.Content)
	var i AiChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatRunCompleted = `-- name: UpdateAIChatRunCompleted :one
UPDATE ai_chat_run
SET status = 'completed',
    error_message = NULL,
    completed_at = $3,
    workout_draft = NULLIF($4::text, '')::jsonb,
    generation_status = 'completed',
    generation_owner = NULL,
    generation_lease_expires_at = NULL,
    generation_heartbeat_at = NULL,
    interrupted_at = NULL,
    interruption_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND (NULLIF($5::text, '') IS NULL OR generation_owner = $5)
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type UpdateAIChatRunCompletedParams struct {
	ID          int32              `json:"id"`
	UserID      string             `json:"user_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Column4     string             `json:"column_4"`
	Column5     string             `json:"column_5"`
}

func (q *Queries) UpdateAIChatRunCompleted(ctx context.Context, arg UpdateAIChatRunCompletedParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, updateAIChatRunCompleted,
		arg.ID,
		arg.UserID,
		arg.CompletedAt,
		arg.Column4,
		arg.Column5,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatRunFailed = `-- name: UpdateAIChatRunFailed :one
UPDATE ai_chat_run
SET status = 'failed',
    error_message = $3,
    completed_at = $4,
    workout_draft = NULL,
    generation_status = 'failed',
    generation_owner = NULL,
    generation_lease_expires_at = NULL,
    generation_heartbeat_at = NULL,
    interrupted_at = NULL,
    interruption_reason = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND (NULLIF($5::text, '') IS NULL OR generation_owner = $5)
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type UpdateAIChatRunFailedParams struct {
	ID           int32              `json:"id"`
	UserID       string             `json:"user_id"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Column5      string             `json:"column_5"`
}

func (q *Queries) UpdateAIChatRunFailed(ctx context.Context, arg UpdateAIChatRunFailedParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, updateAIChatRunFailed,
		arg.ID,
		arg.UserID,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.Column5,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateAIChatRunInterrupted = `-- name: UpdateAIChatRunInterrupted :one
UPDATE ai_chat_run
SET status = 'failed',
    error_message = $3,
    completed_at = $4,
    workout_draft = NULL,
    generation_status = 'interrupted',
    generation_owner = NULL,
    generation_lease_expires_at = NULL,
    generation_heartbeat_at = NULL,
    interrupted_at = $4,
    interruption_reason = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND user_id = $2
  AND status = 'streaming'
  AND generation_status = $6
  AND generation_owner IS NOT DISTINCT FROM $7
  AND generation_lease_expires_at IS NOT DISTINCT FROM $8
  AND generation_attempt = $9
RETURNING
    id,
    conversation_id,
    user_id,
    user_message_id,
    assistant_message_id,
    model,
    status,
    request_id,
    error_message,
    workout_draft,
    generation_status,
    generation_owner,
    generation_lease_expires_at,
    generation_heartbeat_at,
    generation_attempt,
    interrupted_at,
    interruption_reason,
    created_at,
    updated_at,
    started_at,
    completed_at
`

type UpdateAIChatRunInterruptedParams struct {
	ID                               int32              `json:"id"`
	UserID                           string             `json:"user_id"`
	ErrorMessage                     pgtype.Text        `json:"error_message"`
	CompletedAt                      pgtype.Timestamptz `json:"completed_at"`
	InterruptionReason               pgtype.Text        `json:"interruption_reason"`
	ExpectedGenerationStatus         string             `json:"expected_generation_status"`
	ExpectedGenerationOwner          pgtype.Text        `json:"expected_generation_owner"`
	ExpectedGenerationLeaseExpiresAt pgtype.Timestamptz `json:"expected_generation_lease_expires_at"`
	ExpectedGenerationAttempt        int32              `json:"expected_generation_attempt"`
}

func (q *Queries) UpdateAIChatRunInterrupted(ctx context.Context, arg UpdateAIChatRunInterruptedParams) (AiChatRun, error) {
	row := q.db.QueryRow(ctx, updateAIChatRunInterrupted,
		arg.ID,
		arg.UserID,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.InterruptionReason,
		arg.ExpectedGenerationStatus,
		arg.ExpectedGenerationOwner,
		arg.ExpectedGenerationLeaseExpiresAt,
		arg.ExpectedGenerationAttempt,
	)
	var i AiChatRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.Model,
		&i.Status,
		&i.RequestID,
		&i.ErrorMessage,
		&i.WorkoutDraft,
		&i.GenerationStatus,
		&i.GenerationOwner,
		&i.GenerationLeaseExpiresAt,
		&i.GenerationHeartbeatAt,
		&i.GenerationAttempt,
		&i.InterruptedAt,
		&i.InterruptionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateExerciseHistorical1RMFromWorkoutIfBetter = `-- name: UpdateExerciseHistorical1RMFromWorkoutIfBetter :exec
UPDATE exercise
SET
    historical_1rm = $2,
    historical_1rm_updated_at = NOW(),
    historical_1rm_source_workout_id = $3,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $4
  AND (historical_1rm IS NULL OR historical_1rm < $2)
`

type UpdateExerciseHistorical1RMFromWorkoutIfBetterParams struct {
	ID                           int32          `json:"id"`
	Historical1rm                pgtype.Numeric `json:"historical_1rm"`
	Historical1rmSourceWorkoutID pgtype.Int4    `json:"historical_1rm_source_workout_id"`
	UserID                       string         `json:"user_id"`
}

func (q *Queries) UpdateExerciseHistorical1RMFromWorkoutIfBetter(ctx context.Context, arg UpdateExerciseHistorical1RMFromWorkoutIfBetterParams) error {
	_, err := q.db.Exec(ctx, updateExerciseHistorical1RMFromWorkoutIfBetter,
		arg.ID,
		arg.Historical1rm,
		arg.Historical1rmSourceWorkoutID,
		arg.UserID,
	)
	return err
}

const updateExerciseHistorical1RMManual = `-- name: UpdateExerciseHistorical1RMManual :exec
UPDATE exercise
SET
    historical_1rm = $2,
    historical_1rm_updated_at = NOW(),
    historical_1rm_source_workout_id = NULL,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
`

type UpdateExerciseHistorical1RMManualParams struct {
	ID            int32          `json:"id"`
	Historical1rm pgtype.Numeric `json:"historical_1rm"`
	UserID        string         `json:"user_id"`
}

func (q *Queries) UpdateExerciseHistorical1RMManual(ctx context.Context, arg UpdateExerciseHistorical1RMManualParams) error {
	_, err := q.db.Exec(ctx, updateExerciseHistorical1RMManual, arg.ID, arg.Historical1rm, arg.UserID)
	return err
}

const updateExerciseName = `-- name: UpdateExerciseName :exec
UPDATE exercise
SET name = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
`

type UpdateExerciseNameParams struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateExerciseName(ctx context.Context, arg UpdateExerciseNameParams) error {
	_, err := q.db.Exec(ctx, updateExerciseName, arg.ID, arg.Name, arg.UserID)
	return err
}

const updateSet = `-- name: UpdateSet :one
UPDATE "set"
SET
    weight = COALESCE($2, weight),
    reps = COALESCE($3, reps),
    set_type = COALESCE($4, set_type),
    updated_at = NOW()
WHERE id = $1 AND user_id = $5
RETURNING id
`

type UpdateSetParams struct {
	ID      int32          `json:"id"`
	Weight  pgtype.Numeric `json:"weight"`
	Reps    int32          `json:"reps"`
	SetType string         `json:"set_type"`
	UserID  string         `json:"user_id"`
}

func (q *Queries) UpdateSet(ctx context.Context, arg UpdateSetParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateSet,
		arg.ID,
		arg.Weight,
		arg.Reps,
		arg.SetType,
		arg.UserID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateWorkout = `-- name: UpdateWorkout :one
UPDATE workout
SET
    date = COALESCE($2, date),
    notes = COALESCE($3, notes),
    workout_focus = COALESCE($4, workout_focus),
    updated_at = NOW()
WHERE id = $1 AND user_id = $5
RETURNING id
`

type UpdateWorkoutParams struct {
	ID           int32              `json:"id"`
	Date         pgtype.Timestamptz `json:"date"`
	Notes        pgtype.Text        `json:"notes"`
	WorkoutFocus pgtype.Text        `json:"workout_focus"`
	UserID       string             `json:"user_id"`
}

// UPDATE queries for PUT endpoint
func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateWorkout,
		arg.ID,
		arg.Date,
		arg.Notes,
		arg.WorkoutFocus,
		arg.UserID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertStripeCustomer = `-- name: UpsertStripeCustomer :one
INSERT INTO stripe_customers (
    user_id,
    stripe_customer_id
)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET stripe_customer_id = EXCLUDED.stripe_customer_id,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, stripe_customer_id, created_at, updated_at
`

type UpsertStripeCustomerParams struct {
	UserID           string `json:"user_id"`
	StripeCustomerID string `json:"stripe_customer_id"`
}

func (q *Queries) UpsertStripeCustomer(ctx context.Context, arg UpsertStripeCustomerParams) (StripeCustomers, error) {
	row := q.db.QueryRow(ctx, upsertStripeCustomer, arg.UserID, arg.StripeCustomerID)
	var i StripeCustomers
	err := row.Scan(
		&i.UserID,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStripeSubscription = `-- name: UpsertStripeSubscription :one
INSERT INTO stripe_subscriptions (
    stripe_subscription_id,
    user_id,
    stripe_customer_id,
    stripe_price_id,
    stripe_event_created_at,
    status,
    cancel_at_period_end,
    current_period_start,
    current_period_end,
    trial_start,
    trial_end
)
VALUES (
    $1,
    $2,
    $3,
    NULLIF($4::text, ''),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (stripe_subscription_id) DO UPDATE
SET user_id = EXCLUDED.user_id,
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_price_id = EXCLUDED.stripe_price_id,
    stripe_event_created_at = EXCLUDED.stripe_event_created_at,
    status = EXCLUDED.status,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    trial_start = EXCLUDED.trial_start,
    trial_end = EXCLUDED.trial_end,
    updated_at = CURRENT_TIMESTAMP
WHERE stripe_subscriptions.stripe_event_created_at < EXCLUDED.stripe_event_created_at
   OR (
       stripe_subscriptions.stripe_event_created_at = EXCLUDED.stripe_event_created_at
       AND NOT (
           stripe_subscriptions.status IN ('past_due', 'unpaid', 'canceled', 'incomplete', 'incomplete_expired')
           AND EXCLUDED.status IN ('trialing', 'active')
       )
   )
RETURNING
    stripe_subscription_id,
    user_id,
    stripe_customer_id,
    stripe_price_id,
    stripe_event_created_at,
    status,
    cancel_at_period_end,
    current_period_start,
    current_period_end,
    trial_start,
    trial_end,
    created_at,
    updated_at
`

type UpsertStripeSubscriptionParams struct {
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	UserID               string             `json:"user_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	StripeEventCreatedAt pgtype.Timestamptz `json:"stripe_event_created_at"`
	Status               string             `json:"status"`
	CancelAtPeriodEnd    bool               `json:"cancel_at_period_end"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	TrialStart           pgtype.Timestamptz `json:"trial_start"`
	TrialEnd             pgtype.Timestamptz `json:"trial_end"`
}

func (q *Queries) UpsertStripeSubscription(ctx context.Context, arg UpsertStripeSubscriptionParams) (StripeSubscriptions, error) {
	row := q.db.QueryRow(ctx, upsertStripeSubscription,
		arg.StripeSubscriptionID,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripePriceID,
		arg.StripeEventCreatedAt,
		arg.Status,
		arg.CancelAtPeriodEnd,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialStart,
		arg.TrialEnd,
	)
	var i StripeSubscriptions
	err := row.Scan(
		&i.StripeSubscriptionID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripePriceID,
		&i.StripeEventCreatedAt,
		&i.Status,
		&i.CancelAtPeriodEnd,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.TrialStart,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
