// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recommendations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRecommendationTrainingHistory = `-- name: GetRecommendationTrainingHistory :many
WITH recent_sessions AS (
    SELECT DISTINCT w.id AS workout_id, w.date
    FROM workout w
    JOIN "set" observed ON observed.workout_id = w.id AND observed.user_id = w.user_id
    WHERE observed.exercise_id = $1
      AND w.user_id = $2
      AND w.date <= $3
    ORDER BY w.date DESC, w.id DESC
    LIMIT 2
)
SELECT
    recent_sessions.workout_id,
    recent_sessions.date,
    working.id AS working_set_id,
    working.weight,
    working.reps
FROM recent_sessions
LEFT JOIN "set" working
    ON working.workout_id = recent_sessions.workout_id
    AND working.exercise_id = $1
    AND working.user_id = $2
    AND working.set_type = 'working'
ORDER BY recent_sessions.date DESC, recent_sessions.workout_id DESC, working.set_order, working.id
`

type GetRecommendationTrainingHistoryParams struct {
	ExerciseID int32              `json:"exercise_id"`
	UserID     string             `json:"user_id"`
	AsOf       pgtype.Timestamptz `json:"as_of"`
}

type GetRecommendationTrainingHistoryRow struct {
	WorkoutID    int32              `json:"workout_id"`
	Date         pgtype.Timestamptz `json:"date"`
	WorkingSetID pgtype.Int4        `json:"working_set_id"`
	Weight       pgtype.Numeric     `json:"weight"`
	Reps         pgtype.Int4        `json:"reps"`
}

func (q *Queries) GetRecommendationTrainingHistory(ctx context.Context, arg GetRecommendationTrainingHistoryParams) ([]GetRecommendationTrainingHistoryRow, error) {
	rows, err := q.db.Query(ctx, getRecommendationTrainingHistory, arg.ExerciseID, arg.UserID, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecommendationTrainingHistoryRow
	for rows.Next() {
		var i GetRecommendationTrainingHistoryRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.Date,
			&i.WorkingSetID,
			&i.Weight,
			&i.Reps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutRecommendationContext = `-- name: GetWorkoutRecommendationContext :one
SELECT recommendation_context FROM workout WHERE id = $1 AND user_id = $2
`

type GetWorkoutRecommendationContextParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetWorkoutRecommendationContext(ctx context.Context, arg GetWorkoutRecommendationContextParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorkoutRecommendationContext, arg.ID, arg.UserID)
	var recommendation_context []byte
	err := row.Scan(&recommendation_context)
	return recommendation_context, err
}

const saveWorkoutRecommendationContext = `-- name: SaveWorkoutRecommendationContext :exec
UPDATE workout SET recommendation_context = $1::text::jsonb
WHERE id = $2 AND user_id = $3
`

type SaveWorkoutRecommendationContextParams struct {
	RecommendationContext string `json:"recommendation_context"`
	WorkoutID             int32  `json:"workout_id"`
	UserID                string `json:"user_id"`
}

func (q *Queries) SaveWorkoutRecommendationContext(ctx context.Context, arg SaveWorkoutRecommendationContextParams) error {
	_, err := q.db.Exec(ctx, saveWorkoutRecommendationContext, arg.RecommendationContext, arg.WorkoutID, arg.UserID)
	return err
}
