// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: training_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserTrainingProfile = `-- name: GetUserTrainingProfile :one
SELECT
    user_id,
    primary_goal,
    goals,
    experience_level,
    preferred_session_duration_minutes,
    usual_training_location,
    available_equipment,
    avoided_exercises,
    movement_limitations,
    source_conversation_id,
    source_message_id,
    created_at,
    updated_at
FROM user_training_profile
WHERE user_id = $1
`

func (q *Queries) GetUserTrainingProfile(ctx context.Context, userID string) (UserTrainingProfile, error) {
	row := q.db.QueryRow(ctx, getUserTrainingProfile, userID)
	var i UserTrainingProfile
	err := row.Scan(
		&i.UserID,
		&i.PrimaryGoal,
		&i.Goals,
		&i.ExperienceLevel,
		&i.PreferredSessionDurationMinutes,
		&i.UsualTrainingLocation,
		&i.AvailableEquipment,
		&i.AvoidedExercises,
		&i.MovementLimitations,
		&i.SourceConversationID,
		&i.SourceMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserTrainingProfileForChat = `-- name: UpsertUserTrainingProfileForChat :one
INSERT INTO user_training_profile (
    user_id,
    primary_goal,
    goals,
    experience_level,
    preferred_session_duration_minutes,
    usual_training_location,
    available_equipment,
    avoided_exercises,
    movement_limitations,
    source_conversation_id,
    source_message_id
)
VALUES (
    $1,
    NULLIF($2::text, ''),
    COALESCE($3::text[], CASE WHEN NULLIF($2::text, '') IS NULL THEN '{}'::text[] ELSE ARRAY[$2::text] END),
    NULLIF($4::text, ''),
    CASE
        WHEN $5::integer IS NULL THEN NULL
        WHEN $5::integer <= 0 THEN NULL
        ELSE $5::integer
    END,
    NULLIF($6::text, ''),
    COALESCE($7::jsonb, '[]'::jsonb),
    COALESCE($8::jsonb, '[]'::jsonb),
    $9::jsonb,
    $10,
    $11
)
ON CONFLICT (user_id) DO UPDATE SET
    -- Omitted or unchanged legacy goals preserve a newer multi-goal selection.
    goals = CASE
        WHEN $3::text[] IS NOT NULL THEN $3::text[]
        WHEN $2::text IS NULL THEN user_training_profile.goals
        WHEN $2::text = user_training_profile.primary_goal THEN user_training_profile.goals
        WHEN $2::text = '' THEN '{}'::text[]
        ELSE ARRAY[$2::text]
    END,
    primary_goal = CASE
        WHEN $2::text IS NULL THEN user_training_profile.primary_goal
        ELSE NULLIF($2::text, '')
    END,
    experience_level = CASE
        WHEN $4::text IS NULL THEN user_training_profile.experience_level
        ELSE NULLIF($4::text, '')
    END,
    preferred_session_duration_minutes = CASE
        WHEN $5::integer IS NULL THEN user_training_profile.preferred_session_duration_minutes
        WHEN $5::integer <= 0 THEN NULL
        ELSE $5::integer
    END,
    usual_training_location = CASE
        WHEN $6::text IS NULL THEN user_training_profile.usual_training_location
        ELSE NULLIF($6::text, '')
    END,
    available_equipment = COALESCE($7::jsonb, user_training_profile.available_equipment),
    avoided_exercises = COALESCE($8::jsonb, user_training_profile.avoided_exercises),
    movement_limitations = COALESCE($9::jsonb, user_training_profile.movement_limitations),
    source_conversation_id = COALESCE($10, user_training_profile.source_conversation_id),
    source_message_id = COALESCE($11, user_training_profile.source_message_id),
    updated_at = CURRENT_TIMESTAMP
RETURNING
    user_id,
    primary_goal,
    goals,
    experience_level,
    preferred_session_duration_minutes,
    usual_training_location,
    available_equipment,
    avoided_exercises,
    movement_limitations,
    source_conversation_id,
    source_message_id,
    created_at,
    updated_at
`

type UpsertUserTrainingProfileForChatParams struct {
	UserID                          string      `json:"user_id"`
	PrimaryGoal                     pgtype.Text `json:"primary_goal"`
	Goals                           []string    `json:"goals"`
	ExperienceLevel                 pgtype.Text `json:"experience_level"`
	PreferredSessionDurationMinutes pgtype.Int4 `json:"preferred_session_duration_minutes"`
	UsualTrainingLocation           pgtype.Text `json:"usual_training_location"`
	AvailableEquipment              []byte      `json:"available_equipment"`
	AvoidedExercises                []byte      `json:"avoided_exercises"`
	MovementLimitations             []byte      `json:"movement_limitations"`
	SourceConversationID            pgtype.Int4 `json:"source_conversation_id"`
	SourceMessageID                 pgtype.Int4 `json:"source_message_id"`
}

func (q *Queries) UpsertUserTrainingProfileForChat(ctx context.Context, arg UpsertUserTrainingProfileForChatParams) (UserTrainingProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserTrainingProfileForChat,
		arg.UserID,
		arg.PrimaryGoal,
		arg.Goals,
		arg.ExperienceLevel,
		arg.PreferredSessionDurationMinutes,
		arg.UsualTrainingLocation,
		arg.AvailableEquipment,
		arg.AvoidedExercises,
		arg.MovementLimitations,
		arg.SourceConversationID,
		arg.SourceMessageID,
	)
	var i UserTrainingProfile
	err := row.Scan(
		&i.UserID,
		&i.PrimaryGoal,
		&i.Goals,
		&i.ExperienceLevel,
		&i.PreferredSessionDurationMinutes,
		&i.UsualTrainingLocation,
		&i.AvailableEquipment,
		&i.AvoidedExercises,
		&i.MovementLimitations,
		&i.SourceConversationID,
		&i.SourceMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserTrainingProfileForSettings = `-- name: UpsertUserTrainingProfileForSettings :one
INSERT INTO user_training_profile (
    user_id,
    primary_goal,
    goals,
    experience_level,
    preferred_session_duration_minutes,
    usual_training_location,
    available_equipment,
    avoided_exercises,
    movement_limitations,
    source_conversation_id,
    source_message_id
)
VALUES (
    $1,
    NULLIF($2::text, ''),
    COALESCE($3::text[], CASE WHEN NULLIF($2::text, '') IS NULL THEN '{}'::text[] ELSE ARRAY[$2::text] END),
    NULLIF($4::text, ''),
    $5::integer,
    NULLIF($6::text, ''),
    $7::text::jsonb,
    $8::text::jsonb,
    $9::text::jsonb,
    -- Manual settings saves supersede AI-written profile provenance.
    NULL,
    NULL
)
ON CONFLICT (user_id) DO UPDATE SET
    goals = CASE
        WHEN $3::text[] IS NOT NULL THEN $3::text[]
        WHEN $2::text = user_training_profile.primary_goal THEN user_training_profile.goals
        WHEN NULLIF($2::text, '') IS NULL THEN '{}'::text[]
        ELSE ARRAY[$2::text]
    END,
    primary_goal = NULLIF($2::text, ''),
    experience_level = NULLIF($4::text, ''),
    preferred_session_duration_minutes = $5::integer,
    usual_training_location = NULLIF($6::text, ''),
    available_equipment = $7::jsonb,
    avoided_exercises = $8::jsonb,
    movement_limitations = $9::jsonb,
    -- These columns only reference the chat message that last wrote the profile via AI.
    source_conversation_id = NULL,
    source_message_id = NULL,
    updated_at = CURRENT_TIMESTAMP
RETURNING
    user_id,
    primary_goal,
    goals,
    experience_level,
    preferred_session_duration_minutes,
    usual_training_location,
    available_equipment,
    avoided_exercises,
    movement_limitations,
    source_conversation_id,
    source_message_id,
    created_at,
    updated_at
`

type UpsertUserTrainingProfileForSettingsParams struct {
	UserID                          string      `json:"user_id"`
	PrimaryGoal                     pgtype.Text `json:"primary_goal"`
	Goals                           []string    `json:"goals"`
	ExperienceLevel                 pgtype.Text `json:"experience_level"`
	PreferredSessionDurationMinutes pgtype.Int4 `json:"preferred_session_duration_minutes"`
	UsualTrainingLocation           pgtype.Text `json:"usual_training_location"`
	AvailableEquipment              string      `json:"available_equipment"`
	AvoidedExercises                string      `json:"avoided_exercises"`
	MovementLimitations             pgtype.Text `json:"movement_limitations"`
}

func (q *Queries) UpsertUserTrainingProfileForSettings(ctx context.Context, arg UpsertUserTrainingProfileForSettingsParams) (UserTrainingProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserTrainingProfileForSettings,
		arg.UserID,
		arg.PrimaryGoal,
		arg.Goals,
		arg.ExperienceLevel,
		arg.PreferredSessionDurationMinutes,
		arg.UsualTrainingLocation,
		arg.AvailableEquipment,
		arg.AvoidedExercises,
		arg.MovementLimitations,
	)
	var i UserTrainingProfile
	err := row.Scan(
		&i.UserID,
		&i.PrimaryGoal,
		&i.Goals,
		&i.ExperienceLevel,
		&i.PreferredSessionDurationMinutes,
		&i.UsualTrainingLocation,
		&i.AvailableEquipment,
		&i.AvoidedExercises,
		&i.MovementLimitations,
		&i.SourceConversationID,
		&i.SourceMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
