// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, user_id, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (Users, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i Users
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, created_at FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, userID)
	var i Users
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}
